### ISSUE TITLE
Multiline strings: Show new line characters

### ISSUE THREAD

**Issue by Maxim-Filimonov** [darklang/dark#2402]
Right now it's hard to see where are existing newlines characters in the editor:

![](https://files.slack.com/files-pri/TNNBFLGDR-F012CQ4M79U/screen_shot_2020-04-27_at_15.25.33.png)
**Expected result:**
Newline characters(not wraps) are seen in the editor in some way.

**Comment by pbiggar** [comment]
Not applicable in darklang-next.
