### ISSUE TITLE
Multiline strings: Allowing people enter newlines directly

### ISSUE THREAD

**Issue by Maxim-Filimonov** [darklang/dark#2403]
Right now when a user types a string which exceeds certain number of characters(40 AFAIR) it will automatically wrap them on a new line. A user would like to control this behaviour by inserting new line characters in specific places.
**Expected results:**
Being able to insert newline character with a special shortcut(?) or command(?) TBC

**Comment by pbiggar** [comment]
Not applicable in darklang-next.

**Comment by Maxim-Filimonov** [comment]
Now I want to try darklang-next ;)

**Comment by pbiggar** [comment]
Working on it! Should have a blog post up about it this week.
