### ISSUE TITLE
Docstring in StaticAssets::serve is wrong

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#2408]

**Comment by StachuDotNet** [comment]
The docstring right now for `StaticAssets::serve` is `Return the specified file from the latest deploy - only works on UTF8-safe files for now`, both in OCaml and F# backends. Is this wrong, and if so - how?

**Comment by pbiggar** [comment]
I think it's the "latest" part, that's what serveLatest does.

**Comment by StachuDotNet** [comment]
Can you remind me our policy on updating docstrings? I couldn't find any guidance in our docs - may be worth adding, unless I simply missed it.

**Comment by pbiggar** [comment]
We can safely change any docstring, we just havent because we wanted to test that the output was identical to the old one.
