### ISSUE TITLE
Expand the standard library

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#2411]
The standard library has a batteries-included approach for the standard modules: List, String, Int, Float, Result, Option, UUID, Date, Dict, Bool, Bytes, DB, HTTPClient and HTTP (response) modules.

We generally copy the Elm standard library where it makes sense: https://package.elm-lang.org/packages/elm/core/1.0.5/. We no longer add functions that would make more sense in the package manager (such as calls to HTTP/REST/JSON APIs). We do add Crypto functions as they are very hard to do in userspace and have performance needs.

Contributions of just one function is very welcome, and is a great early bugs for contributors.

We have an internal document on how to write standard library functions, which I'll add to this ticket later.

This explains how to write docstrings: https://github.com/darklang/dark/blob/master/docs/writing-docstrings.md.

Requests for new functions should each be a separate issue.

https://github.com/darklang/dark/labels/stdlib

**Comment by StachuDotNet** [comment]
merged this into #5239
