### ISSUE TITLE
Add a way to refactor a fnCall into a pipeline

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#2412]
Given the function

```
List::append [1] [2]
```

I'd like to run a command to convert that into a pipe:

```
[1]
|> List::append [2]
```

Right now, this is really annoying to do, so add a command to the command palette to do this. It should only appear when on a function name for now.

Commands are in client/src/fluid/Commands.ml

**Comment by StachuDotNet** [comment]
Folded this into #5242
