### ISSUE TITLE
The display of HTTP responses in the return value is unclear

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#2414]
The return value for HTTP responses looks like this:

```
200 {
  some content
}
```

which is unclear. Instead, we should make it look like an actual HTTP response, such as:

```
HTTP/1.1 200 OK
Date: Sun, 10 Oct 2010 23:26:07 GMT
Last-Modified: Sun, 26 Sep 2010 22:04:35 GMT
Server: Apache/2.2.8 (Ubuntu) mod_ssl/2.2.8 OpenSSL/0.9.8g
ETag: "45b6-834-49130cc1182c0"
Accept-Ranges: bytes
Content-Length: 12
Connection: close
Content-Type: text/html

Hello world!
```

As a followup project, we should share the HTTP handling backend code (if that's even possible) in the client so that are showing the actual HTTP response that gets returned.

**Comment by StachuDotNet** [comment]
relevant just to old editor
