### ISSUE TITLE
Worker names should autocomplete

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#2418]
`emit` takes an argument which is the names of a worker to emit the event to. The autocomplete should offer the names of existing workers.

Note that the autocomplete does not show by default, and autocomplete does not show for strings, so before we implement this, we'll need someone to suggest a good behaviour.

We can also support the other way: autocomplete worker names based on the emits on the canvas  (or maybe the 404s).

**Comment by pbiggar** [comment]
In new Dark, workers should be real values, like datastores.

**Comment by StachuDotNet** [comment]
> In new Dark, workers should be real values, like datastores.

could you write a bit more what you mean by this?

**Comment by pbiggar** [comment]
Datastores are defined as `DDB of string` (really, they should be DDB of tlid but that's a topic for another day).

They have a specific type that represents the DB value.

Meanwhile, Queues/Workers do not - to add something into a queue you call `emit_v1 "workerName"`. This doesn't have static typing.

**Comment by StachuDotNet** [comment]
I folded this into #5237 - let's see how it comes up again when we get to Worker support in the new editor.
