### ISSUE TITLE
Add sub-second time precision

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#2420]
Users have asked for sub-second precision. However, our DateTimes (we call them dates in the product but I'll refer to them as DateTimes here to be unambiguous) only offer sub-second precision.

I'm not positive that adding sub-second precision to DateTimes is the right solution here. I'd be interested in perspectives on that. My sense is that sub-second precision is for timing things, and we could handle that without changing DateTimes, and in fact it isn't a great solution for timing things.

I'd be interested in some feedback on:
- what's the usecase for sub-second precision
- what's the usecase, if any, for specifically DateTimes to have sub-second precision
- what are other ways to solve these use cases (is this really a request for profiling, perhaps)?

**Comment by StachuDotNet** [comment]
folded into #5239 for now
