### ISSUE TITLE
Stabilize integration tests

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#2425]
Our integration tests (`./integration_tests`) are written in TestCafe. They are quite slow and reasonably flaky, and we have found that testcafe's technology does not let us test interesting parts of our code (such as copy/paste). Some ideas here:

- we are also interested in speeding up the testcafe tests and making them more reliable. We have not really looked at speed yet, we periodically look at reliability. Right now the tests take 7m in CI (despite being split 4 ways)

- we are interested in potentially converting from testcafe to [playwright](https://github.com/microsoft/playwright). Doing a technical evaluation (converting 1 test perhaps) and reporting back would be useful

**Comment by StachuDotNet** [comment]
I believe this can be closed

**Comment by pbiggar** [comment]
Ironically they're flakier now than before

**Comment by StachuDotNet** [comment]
> Ironically they're flakier now than before

Somehow I haven't noticed this recently. Which are you having issues with? We should create a new issue or reopen this.

**Comment by pbiggar** [comment]
Just every time we need to press `Rerun from failed` on circleci
