### ISSUE TITLE
Perhaps there should be some sort of safeguard around `DB::deleteAll`?

### ISSUE THREAD

**Issue by naclcaleb** [darklang/dark#2430]
When working with datastores, the "locking" system is great and keeps me from accidentally losing important data.
However, it seems eerily easy to accidentally call `DB::deleteAll`. Especially because there's only one parameter, and the autocomplete brings up the ~databases~ datastores right there.

I'm not really sure what this would look like, but I think it would be good to have something more required to run `DB::deleteAll` - perhaps there could be some sort of "production mode" switch that disallows certain functions like this until it's turned off (and possibly require a password to turn off)?

**Comment by StachuDotNet** [comment]
folded this into #5236 -- let's see how this comes up again in the new editor
