### ISSUE TITLE
Show both relative and absolute timestamps in traces

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#2464]
Right now we display "3m ago", "1 day ago", etc, in live values. When we mouseover the time, we should show the full date-time.

To get started, look in client/src/fluid/FluidView.ml:viewLivevalue

**Comment by pbiggar** [comment]
Not applicable in darklang-next.

**Comment by pbiggar** [comment]
Actually leaving open as a suggestion for the new editor.

**Comment by StachuDotNet** [comment]
merged into #5238
