### ISSUE TITLE
When creating a lambda, select the first variable name

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#2467]
When you create a lambda, the user often wants to type their own name instead of using our name. However, when they type their name, it's added to the front.

Based on what Lamdu does (they make editor-generated words in italics. Our equivalent I think would be selecting the variable name instead).

**Comment by StachuDotNet** [comment]
I took a quick peek at this as it was bugging me. I hope to revisit this when I work on #4339. Some quick notes:

`Fluid.insertInPlaceholderExpr` seems to be where to start.
Currently, that fn returns a tuple of (a)the Expr to replace the placeholder with, along with (b) a CT of where to leave the cursor. I imagine we could also return an `Option<CT>` representing where an appropriate selectionStart would be. And maybe translate that CT to pos?

Filling in a lambda's placeholder upon `\` keypress calls a local fn `lambdaArgs` which _may_ return multiple arguments. We could probably determine the length of the first result from that, and determine the pos within `insertInPlaceholderExpr` itself by offsetting from the already-determined CT?

**Comment by pbiggar** [comment]
Yeah, this sounds right, AFAICT.

**Comment by pbiggar** [comment]
Closing as it doesn't apply to darklang-next
