### ISSUE TITLE
Show return type in function references

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#2475]
This currently display like this:

![image](https://user-images.githubusercontent.com/181762/83468915-2eed6100-a44c-11ea-9549-4d7545ad5c7c.png)

They should show the return type as well.

**Comment by OceanOak** [comment]
I think this issue can be closed.
![image](https://user-images.githubusercontent.com/87861924/215633637-9042bb35-be08-489e-9d51-f73681692944.png)
