### ISSUE TITLE
A .mli file for every .ml file

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#2512]
We should have a .mli file for each .ml file, but we didn't do that initially. Advantages are better compile speed, better definition of interfaces, and reduces the frequency where the type checker can't figure out what's going on.

**Comment by StachuDotNet** [comment]
Should this be closed? I'm not sure if you have any intentions of .fsi files being created long-term (personally I'm not a fan, and they're not used often in the F# community afaik)
