### ISSUE TITLE
Deleting and retyping in the command palette enables invalid options

### ISSUE THREAD

**Issue by vkrauchunas** [darklang/dark#2529]
![commandpalette](https://user-images.githubusercontent.com/56368175/83930898-bb4e9b00-a74e-11ea-9da3-e1cc4df4820c.gif)

To reproduce:

1. Open the command palette and start to type something. 
2. Delete what you just typed.
3. Look at the command palette options - all of them seem to be available, even ones that are not valid.

**Comment by pbiggar** [comment]
Not applicable in darklang-next.
