### ISSUE TITLE
All fields at the top of handlers that can be edited should be selectable with double click

### ISSUE THREAD

**Issue by vkrauchunas** [darklang/dark#2530]
We've gotten feedback from a few users who struggle when they try to rename or change their handlers. Double click on the title, type, CRON interval, etc should all result in the text being highlighted and editable.

caveat: this should work the "normal" way which means the word would be highlighted - /party/:partyslug/:character you could select any of the three words.

Needs to work whether the cursor was already in the field or not.

Please make sure to add an integration test.

**Comment by pbiggar** [comment]
Should check this when redoing the handlers to use fluid

**Comment by pbiggar** [comment]
Not applicable in darklang-next.
