### ISSUE TITLE
Autocomplete reuses ids between invocations, which leads to duplicate AST ids. Duplicate AST ids break the editing experience

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#2541]
autocomplete shares ids for replacements between invocations. This means that the AST sometimes ends up with multiple items that have the same id (a fuzzer could be helpful to see if there's other cases where this happens), which confuses caret placement, variable renames, etc...

Example:

Given

```
match ___
|___ -> ___
___ -> ___
```

1) Type Jus and press enter to autocomplete:

```
match ___
Just |___ -> ___
___ -> ___
```

2) Use the arrow keys to move to the other match branch and repeat 1

```
match ___
Just ___ -> ___
Just |___ -> ___
```

3) Press backspace twice:

```
match ___
Jus| -> ___
Jus -> ___
```

Notice that the caret is in the wrong place and the 'Jus' variable now exists in two places!

**Comment by pbiggar** [comment]
Solved, right @StachuDotNet?

**Comment by StachuDotNet** [comment]
Yes! Cool, feels good to have resolved an Issue from so long ago.
