### ISSUE TITLE
Add support for tuples

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#2545]
We'd like to support tuples, like so: `let x = (1,2)`. These will be particularly useful for HTTP headers.

Steps:

- add a dval option for tuples
- add a FluidExpression.t option for tuples
- add a way to enter tuples (FluidToken.t, similar to TListOpen)
- add all the machinery: tests, execution (libexecution/ast.ml), serializers

**Comment by pbiggar** [comment]
Definitely 2 as a minimum.

The problem with having a maximum is that often you want just one more. Elm added a maximum size and personally I found it very very frustrating.

**Comment by StachuDotNet** [comment]
Ok, I'll go with `[2, infinite)`.
Down the road, we can support a user-/org-specific setting of "offer to convert tuples of length [X] or more to another type," providing a nice refactoring experience there.

**Comment by pbiggar** [comment]
Yeah, sounds good. Why a "user-/org-specific setting" though?

**Comment by StachuDotNet** [comment]
I might want the "encouragement" at 5 elements; someone else might want it at 9.

**Comment by StachuDotNet** [comment]
bit tangential, but I imagine long-term we have a number of org/user-specific editor settings, incl. formatting preferences, font, etc. This just feels like something in that space.

**Comment by pbiggar** [comment]
Yeah, font and formatting preferences will be user-based for sure.

Ah, so the idea was not so much that the semantics of tuples would be [2,5], but rather that orgs might like to set coding guidelines. In which case, the semantics would still need to be [2,infinite], right?

**Comment by StachuDotNet** [comment]
Right

**Comment by pbiggar** [comment]
I tend not to add versioning unless I know exactly how it will be versioned. We can always add it later.

**Comment by StachuDotNet** [comment]
#4182 took care of most of this Issue, but there's still work to be done. (i.e. users are currently prevented from _creating_ tuples, which is sort of important). I'll follow up soon with next steps.

**Comment by StachuDotNet** [comment]
Here's work to be done with tuples, at some point:
- add tuple stdlib fns #3309 
- tuple destructuring #3402 
- allow tuples as tuple return/param types for user fns #4239
- fluid bugfix: #4235 
- fluid bugfix: #4264
- type checking in backend (also covered in #4239 - maybe should be its own thing)

What the minimum needed before we allow users to create/use tuples by flipping/removing [this](https://github.com/darklang/dark/blob/a47dbb37ff460275e5c64911d0e02d58bfc8e6e5/client/src/fluid/Fluid.res#L34) switch?

Personally I think #4264 and #3402 are sufficient, with #3309 in the "maybe" pile.

**Comment by StachuDotNet** [comment]
Sounds good. Closing this in favor of #4265.
