### ISSUE TITLE
Show a warning when the code has not been committed

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#2563]
Changing code sends an AddOp to the server. The response is ignored. The response should indicate if the latest code has been properly saved or not. Code is occasionally not properly saved due to internet.

Should an indicator that code is not saved/not saved based on whether the response from the last AddOp (for functions/handlers/types) was successful. For DBs, any failed response is noteworthy.

**Comment by StachuDotNet** [comment]
No longer relevant - when editing in VS Code, it's clear what's been saved. Any breakages to that flow can result in new issues if they're hit.
