### ISSUE TITLE
Support deleting a canvas

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#2642]
In the settings page, add an option to delete a canvas (much like github's repo deletion). Add an API to do the deletion.

**Comment by pbiggar** [comment]
I think making a canvas to do this would work. An API would mark a canvas as deleted, and when searching for the canvas we would ignore deleted canvases.

Then we would have a dark canvas which goes through and deletes all the content. I think it would be useful to:

- send an email when a delete is requested
- wait a day or more to actually delete the data
- allow the deletion to be deleted


See integration-tests/clear-db for a list of everything which needs to be deleted in the DB. Events in the queue can expire naturally.

**Comment by StachuDotNet** [comment]
folded into #5235
