### ISSUE TITLE
Support contributing to a public canvas

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#2645]
Many of the changes we'd like to make to Dark need backends, which can themselves be written in Dark (eg various administration tasks and tooling).

To support this, we want to support setting canvases to be public, and also allow editing public canvases.

This needs a spec, and it quite a few moving parts:
- allow setting a repo as public
- allowing contributors to make an equivalent of a pull request (this alone is a big project)
- allowing contributors to edit without traces
- allowing some traces to be marked as "ok" for public consumption

**Comment by StachuDotNet** [comment]
folded into another Issue
