### ISSUE TITLE
String::split returns an incorrect value, only when used in a function

### ISSUE THREAD

**Issue by topher200** [darklang/dark#2665]
Using String::split in a function returns an incorrect value, while using it in a REPL returns the correct value. This is specifically for inputs where the output should have an empty string as the first value.

Steps to reproduce:
1. Write a function which uses String::split
 - Example: inputs: `str` (string), `sep` (string). code: `String::split str sep`
2. Call this function from a REPL. Pass input such that an empty string is the first value in the output.
 - Example: `splitStringFunc "asdf" "a"`
- ✔️Expected behavior: the output of the function is `["", "sdf"]`
- ❌Actual behavior: the output from String::split includes an empty string as the first value only when used directly in the REPL; any calls within a function are missing this empty string
  - Value returned by String::split in a REPL: `["", "sdf"]`
  - Value returned by String::split in a function: `["sdf"]`

Canvas which shows this error: https://darklang.com/a/topher200-return-value-repro. I created this canvas just to show off this bug; feel free to use it in any way. If I could make it public I would.

Repl:
```
let _ = "String::split returns the correct value 
        when called directly"
let raw = String::split "asdf" "a"
let correctRaw = raw == ["","sdf"]
let _ = _
let _ = "However, if we call String::split in a f
        unction it returns an incorrect value."
let function = stringSplit "asdf" "a"
let correctFunction = function == ["","sdf"]
let _ = _
let _ = "Observe that correctRaw is True while co
        rrectFunction is False"
List::map [correctRaw,correctFunction] \val -> val != false
```
Function `splitString`:
```
str
|>String::split separator
```
![image](https://user-images.githubusercontent.com/206988/86207677-e0eb7c00-bb23-11ea-8aa7-30bd8fa01201.png)
![image](https://user-images.githubusercontent.com/206988/86207531-9c5fe080-bb23-11ea-8217-0542ce18ba0e.png)
_This last image shows the weirdest part of this bug: the trace in the function shows the correct return value. However, any REPL which calls the function receives the incorrect value. I have reproduced this in two different canvases; this was very difficult to debug._

**Comment by tchak** [comment]
I fixed the issue in https://github.com/darklang/tablecloth thinking that it's what was used in dark. But the dark stdlib is separate implementation. The fix should be roughly the same though https://github.com/darklang/tablecloth/pull/144

**Comment by pbiggar** [comment]
I realized why this happens: the implementation of split is different in the JS vs in the OCaml code. I believe this will be fixed by the fsharp rewrite.

**Comment by strowk** [comment]
I have written function that behaves always the same:

```
let prefix = "8eb2d37d-e803-4e9b-b61b-623e56e46394"
List::filterMap
  String::split String::appendv1 prefix splitme separator
  \val -> if val == prefix
          then
            Nothing
          else
            Just String::replaceAll val prefix ""
```

It relies on the assumption that a particular uuid will not happen to be in the string though

**Comment by StachuDotNet** [comment]
> I believe this will be fixed by the fsharp rewrite.

It is fixed now, as of the F# rewrite.
