### ISSUE TITLE
Infix operators can't return Result or Option

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#2672]
We'd like to support returning Result or Option for infix operators, hopefully to allow `/` to return a result on division-by-zero. However:

- We don't support the command palette operations for the error rail for Binops
- A binop that returns Nothing or Error doesn't cause a circle to show up on the error rail. It returns a value visualized as <ErrorRail: ...> instead

If we fix these (with tests) then we should be able to support better error handling for infix operators.

**Comment by StachuDotNet** [comment]
I'm not sure this aligns with our current language design - operators like `?` and `!` in some form are likely to solve for this instead.
