### ISSUE TITLE
Support versioned infix operators / hide latest version

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#2673]
Functions are currently versioned, but infix operators (`Binops`) are not. We should support them.

I think the biggest issue is how to display it. We haven't added extra versions because it would look ugly and weird to always be typing `+_v23` or similar.

My thinking is that right now we don't show the version for v0. What if instead we didn't show the version for the latest version, and showed the version for all other versions (including v0).

I'd love someone to make a prototype and let us try it (or we could ship it behind a feature flag if we're unsure).

**Comment by StachuDotNet** [comment]
folded into #5243
