### ISSUE TITLE
Undefined functions should be highlighted

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#2677]
Although rare, sometimes undefined functions can appear (such as when copy/pasting). When this happens, we should highlight the functions and show an error saying "The function `myFunctionName` has not been defined".

Mockup (see `DarkInternal::checkPermission` in this image):

![image](https://user-images.githubusercontent.com/181762/86535688-0e338380-beb0-11ea-8682-6c67fe64787d.png)

**Comment by StachuDotNet** [comment]
folded into #5237
