### ISSUE TITLE
Enter to complete single-argument function within pipeline should create another pipe

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#2683]
Pressing enter to complete an autocomplete in pipes works fine (that is, it creates a new line in the pipe) for functions with a pipe argument (that is, for functions with 2 or more parameters):

![2019-12-12_15 34 17](https://user-images.githubusercontent.com/181762/86538691-91ab9f80-bec5-11ea-843e-b0e4336fed7e.gif)

However, it does not work properly for functions with no pipe arguments (that is, with 1 argument):

![2019-12-12_15 29 29](https://user-images.githubusercontent.com/181762/86539146-6d04f700-bec8-11ea-89ab-a5c6f64ccfb5.gif)

**Comment by br1anchen** [comment]
Tested with `a8651555b55896edcc5e357eaa4e1a0d748ba6f6` and production, single argument function in pipe works fine as you described:
![enter-single-pip-fun-2020-07-12](https://user-images.githubusercontent.com/1086461/87254154-c8168b00-c480-11ea-960c-6fd82c02273b.gif)

**Comment by pbiggar** [comment]
Great, thanks for confirming!
