### ISSUE TITLE
Refactoring command to extract all uses of an expression

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#2702]
I have code like this:

```
let _ = DB::setv1
          {
            name : request.body.name
            email : request.body.email
            username : request.body.username
            time : Date::now
            coc : request.body.coc == "on"
          }
          request.body.email
          Attendees
let query = "email=" ++ AWS::urlencode request.body.email
```

which reuses `request.body.email` three times. I want to extract `request.body.email` so the code is like this:

```
let email = request.body.email
let _ = DB::setv1
          {
            name : request.body.name
            email : email
            username : request.body.username
            time : Date::now
            coc : request.body.coc == "on"
          }
          email
          Attendees
let query = "email=" ++ AWS::urlencode email
```

There exists a refactoring command `extract-variable` which will just create the `let` and replace it in the current position. This new command should replace `request.body.email` in all places that are in scope.

**Comment by klebervirgilio** [comment]
@pbiggar would that be something that a newcomer could work on?

**Comment by pbiggar** [comment]
Yes, very much so (that's what the `good-early-bug` tag is intended to convey :)).

You can copy the `extract-variable` code and modify it, and that should get you most of the way there (see the [getting started guide](https://darklang.github.io/docs/contributing/getting-started) for getting the basics of contributing!

**Comment by StachuDotNet** [comment]
folded into #5242
