### ISSUE TITLE
Dark can't connect to ipv6 addresses

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#2715]
Unsure how to address this, possibly something with libcurl.

![image](https://user-images.githubusercontent.com/181762/87085972-c9388580-c1fe-11ea-9555-4fe53457082f.png)

**Comment by pbiggar** [comment]
This appears to still fail: `<ErrorRail: Error "The request was aborted. The response ended prematurely.">`

So we'll need to add support (what I'm hoping is a single flag) to a new httpclient.

We'll also need to check that we're not breaking any firewall rules.

**Comment by StachuDotNet** [comment]
merged into #4707
