### ISSUE TITLE
Remove duplicate dockerfile

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#2738]
Our docker container is built in the https://github.com/darklang/dockerfile repo, for use in CI. However, we currently have the dockerfile duplicated in both repos (we need it in the dark repo to build the container locally).

Ideally, the dockerfile would only be in one place (the other repo), and we would pull it or share it somehow (git submodules or whatever the modern version of that is, or even just calling curl on the file).

**Comment by StachuDotNet** [comment]
folded into #5246
