### ISSUE TITLE
Persist elapsed time with requests/traces, and display in Editor

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#2741]
We currently store the start time in traces, we could easily store the finish time as well, and display that in the editor.

This requires adding the end time to traces in the DB, and adding a place to save that data (for each of cron jobs, workers, and HTTP requests). Then, that information has to be sent to the frontend as part of traces, and then displayed as part of a live value.

This is a straight-forward PR, but beware that it touches a lot of systems and moving parts.

**Comment by StachuDotNet** [comment]
merged into #5238
