### ISSUE TITLE
Float:: functions should not crash when passed NaN

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#2746]
Floating-point functions should not crash when passed NaN.

We'd like to get to the point where all Floating point functions that would use NaNs would instead use results, but the error rail isn't really good enough for that at the moment.

As a partial step, functions which received NaNs and which currently crash, should instead return a `DError`

**Comment by nlao1** [comment]
Hi, is this still open? I'd like to try.

**Comment by pbiggar** [comment]
@nlao1 Awesome! At the moment I'm rewriting the backend in F#, and so new behaviour is on hold until I've fully replicated the old behaviour. The best place to get involved is in https://github.com/darklang/dark/issues/2976.

(PS apologies for the slow response, I was afk for a day)

**Comment by pbiggar** [comment]
I think this is solved
