### ISSUE TITLE
Add HTML parsing functionality to standard library

### ISSUE THREAD

**Issue by clintgibler** [darklang/dark#2811]
It would be quite useful to have basic HTML parsing in the standard library, so one could extract out relevant info via XPath, CSS selector, etc., a la jQuery, [BeautifulSoup](https://www.crummy.com/software/BeautifulSoup/bs4/doc/), or [nokogiri](https://nokogiri.org/).

Previously in the Darklang community Slack, @pbiggar referenced [this tweet](https://twitter.com/_glnarayanan/status/1306251360833167360), which lists 4 different scraping services.

Those are perhaps OK temporary workarounds, but I think in the medium and long term, a non trivial percentage of Darklang users (including myself) would appreciate being able to parse HTML directly in Darklang.

**Comment by samgreen** [comment]
Would really love this as well, I understand it might not be trivial.

**Comment by StachuDotNet** [comment]
folding this issue into #5239
