### ISSUE TITLE
Support deleting Secret Keys

### ISSUE THREAD

**Issue by clintgibler** [darklang/dark#2815]
Currently you can create Secret Keys but cannot delete or modify them.

This is a problem if someone needs to revoke or rotate a secret.

I'd propose adding a delete button in the UI next to the current "copy" secret name button.

**Comment by clintgibler** [comment]
That's a good point, probably best not to break existing code. 

Perhaps similar to other components, it can visually show you all the components where that secret is used so you can easily change them?

There might be some value in having a "panic override: delete the key immediately" button, for example: you just pushed your AWS key, a GitHub token, etc. to a public git repo, and an attacker could easily use that secret to do something that costs your company thousands of dollars, access your prod DB, or something similarly high impact and you need to change/revoke it everywhere. Or you realize your code is inadvertently leaking the secret to a third party and you need to change it immediately.

^ is probably a "maybe build someday," not a high priority, but I could imagine a few cases in which there could be a situation in which rapidly responding is important.

**Comment by pbiggar** [comment]
Yeah, I agree with both of those suggestions.

**Comment by StachuDotNet** [comment]
This has been recently discussed [here](https://github.com/darklang/dark/discussions/4605#discussioncomment-4182466).
At this point, we have an API endpoint to handle deleting Secrets, but it is not exposed in the UI.

**Comment by StachuDotNet** [comment]
merged this issue into #5260
