### ISSUE TITLE
Dark needs a mechanism & UI for profiling code

### ISSUE THREAD

**Issue by joconor** [darklang/dark#2825]
Start by specing requirements in https://roadmap.darklang.com/. Put placeholder in roadmap document ASAP so the specs can be defined at the appropriate time. 

Q: Does distributed tracing (see https://microservices.io/patterns/observability/distributed-tracing.html) also have a need in Dark?

**Comment by StachuDotNet** [comment]
Hi there - folding this old issue into #5238 as a bunch of reorg is happening. thank you!
