### ISSUE TITLE
Provide a self-hosted (on-premises) version

### ISSUE THREAD

**Issue by DemiMarie** [darklang/dark#2860]
Some organizations are simply not able to use the cloud, no matter how much they want to.  Others have compliance requirements that are impractical for a small company like Dark Inc to support.

For example, government contractors dealing with classified information cannot use Dark at all, and HIPAA compliance would likely be a significant overhead on Dark Inc’s part.  Many of these companies have large, in-house infrastructure teams, but they might still like Dark’s rapid development features.

**Comment by pbiggar** [comment]
Thanks for raising the issue. I think this is something we may do at some point in some way. While part of the goal of Dark is to have a single ecosystem, I think there may be something we can do that is self-hosted in some way to satisfy some compliance requirements (or we may make the hosted version HIPAA/etc compliant instead or aswell). That said, I don't expect to do this for several years, as I think it will be a distraction in the short/medium term, when we haven't gotten product market fit yet.

I'll close this issue for now as a result. Still appreciate you raising it, as this provides an answer to questions that people have around this.

**Comment by DemiMarie** [comment]
Thanks for your response, @pbiggar.  I will say that while you might be able to make the hosted version compliant with many regulations, there are some that simply won’t be possible.  Classified and air-gapped environments are the first two that come to mind ― there is no way to use the hosted version in an environment with no access to the Internet.

**Comment by JakubKoralewski** [comment]
Found this exploring the project for the first time, so this may be inaccurate but I'm guessing this is going to be a big issue one day, so I may be missing something, please correct me in such case.

Not necessarily for security purposes, but just being able to try it out by yourself at first, then see that it works the same but is a lot easier to use with the cloud-hosted deployment method you provide would be a good selling point for pragmatists and skeptics alike.
