### ISSUE TITLE
Dark editor does not allow you to create a list consisting of several values produced by |>

### ISSUE THREAD

**Issue by Stvad** [darklang/dark#2863]
You can construct list of one element, but if you are to add a coma after that element - editor won't understand it: 

![image](https://user-images.githubusercontent.com/81347/98492351-6d056280-21ec-11eb-9262-d04c6683b1e6.png)

If you just press enter - the editor wold extend the pipeline:
![image](https://user-images.githubusercontent.com/81347/98492358-6f67bc80-21ec-11eb-8433-cabb70113646.png)

Slack discussion: https://darkcommunity.slack.com/archives/CNTCWD6MP/p1604881807171700

**Comment by xtopherbrandt** [comment]
@pbiggar looking at this bug, I'd like to know your thinking about how to fix it. The main problem is that when the cursor is at the end of a variable within a list (and nothing is selected), createPipe (in Fluid.ml) is given the id of the list and no other context to know if the cursor is inside the list or outside.  The key handling code in updateKey uses getTopmostSelectionID which finds the list. 

One option would be to make the key handling code for ShiftEnter a bit smarter and set findParent to false if the cursor is inside a list. I think this would be a simpler change but spreads out the logic of finding the right thing to pipe from.

Another option would be to provide more context about the cursor location to createPipe and probably findAppropriateParentToWrap. This would be a bigger riskier change but may centralize the logic.

**Comment by pbiggar** [comment]
Thanks for looking at this @xtopherbrandt. I'm not sure which the correct solution is. This code is very hacky, but is held together by lots of unit tests, so if the tests pass you can consider it a decent solution. (you'll definitely want to add some tests too!)

The editor was designed with the knowledge that we're going to have to support lots of edge cases, though obviously if you find a way to clean it up sincely, that would be great. I'll note that getTopmostSelectionID might not be the best function to use for an "empty" selection, though to my knowledge it works quite well for non-empty selections.

**Comment by pbiggar** [comment]
This was fixed by @xtopherbrandt in #2930.
