### ISSUE TITLE
http response as XML

### ISSUE THREAD

**Issue by uxkjaer** [darklang/dark#2895]
Hi. 
I recently discovered dark and have been experimenting for local development usage to stub backend requests. In my scenario I would need to send a mix of json and xml responses. Is that possible to do via the canvas. I couldn't figure out how to return anything but text strings.

**Comment by pbiggar** [comment]
You can use the `Http::response` family of functions. In particular, you might want `Http::responseWithJson` or `Http::responseWithHeaders`.
