### ISSUE TITLE
Package manager should use owner ID

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#2929]
Dark programs store calls to package manager functions using strings to represent the owner. But, if the owner changes their username, that will break. Worse, if the owner changes their username, and a new user takes the old username, there could be a security incident.

Instead, stored programs should call package manager functions using the owner's UUID. (Similarly, functions should be stored in programs as TLIDs, not function names, to make it easier to change the names).

**Comment by StachuDotNet** [comment]
redundant with another issue, but folded into #5243
