### ISSUE TITLE
Passwords are determined to be equal in the editor when they're not

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#2971]
This only happens in the editor, not in "production".

This code returns true when it should return false. The bytes in the password are empty in the editor (as the password is redacted) so it's deemed to be true due to equality. We should make sure that password equality is false in this situation somehow.

![image](https://user-images.githubusercontent.com/181762/110831888-b2a06d80-8268-11eb-92a3-d87f8ec6dac5.png)

**Comment by JustusMoeller** [comment]
My suggestion is to just use another hashing algorithm like MD5 in the editor instead of redacting the password. This has caused me some issues in other places where code is straight up untestable because passwords are redacted.

**Comment by pbiggar** [comment]
That's a good idea, it would at least solve the equality problem here. Also, that's an editor-only fix so it should be backwards compatible.

**Comment by pbiggar** [comment]
Passwords have been removed
