### ISSUE TITLE
Upgrade Dockerfile to use ubuntu 20.04 image

### ISSUE THREAD

**Issue by asubiotto** [darklang/dark#3023]
Running the Dockerfile for the first time on https://github.com/darklang/dark/commit/e58711e56612a366c8891eeb14d0e234e764f307, I encountered some build errors:
```
#20 3.295 E: Package 'google-chrome-stable' has no installation candidate
#20 3.295 E: Package 'docker-ce' has no installation candidate
#20 3.295 E: Version '1.16.1-1~bionic' for 'nginx' was not found
```

I still have to investigate whether we can fix finding these packages on 18.04, but the recommendation from slack was to upgrade the Dockerfile to use ubuntu 20.04, the latest LTS version.

My WIP to do this is here: https://github.com/asubiotto/dark/commit/d510feb878a52e5c0fb46ae27636add81e31c630

Unfortunately, the current blocker is that the `pg_createcluster` fails with:
```
#29 2.701 running bootstrap script ... FATAL:  semop(id=25) failed: Function not implemented
```

Since I am running an Apple M1 laptop, my best guess is that this is a qemu virtualization bug running amd64 images on an m1 host. `semop` calls `semtimedop` which is not implemented in this case (https://bugs.launchpad.net/ubuntu/+source/qemu/+bug/1895456). There are also some known issues run amd64 images on apple silicon: https://github.com/docker/for-mac/issues/5321.

I am not familiar enough with docker/qemu to say what the best way forward here is, but it looks like the general workaround is to use arm64 images. However, some packages dark relies on like google chrome don't seem to be available for arm64 and it seems like a pretty big change.

**Comment by pbiggar** [comment]
The dockerfile is now updated to 20.04. There might be some issues on arm64 still, but we can see them when they come up.
