### ISSUE TITLE
Allow deleting accounts

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#3073]
Users occasionally ask to delete their accounts, and this should be a first-class thing we support without users having to ask us.

Add a button to the UI that points to a DarkInternal function that deletes the code. We probably want separate low-level functions for deleting assets, traces, DB data, code, ACLs, and then the user themselves, which we can combine in Dark code to provide an API.

**Comment by StachuDotNet** [comment]
folded into #5235
