### ISSUE TITLE
Make traces more readable

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#3080]
# Add syntax highlighting

![image](https://user-images.githubusercontent.com/181762/121549317-c0869b80-c9db-11eb-8d6d-40484eb40506.png)
**Style Guidelines:**

- Symbols are `$grey1`, so developers can focus on the content
- Strings are colored the same color as in strings in Dark code

## Render empty objects as `{}` instead them taking up 3 lines.

![image](https://user-images.githubusercontent.com/181762/121549667-10fdf900-c9dc-11eb-95e3-3712adfb43a1.png)

**Style Guidelines:**

- If the object is empty, render all in the same line.

**Comment by StachuDotNet** [comment]
folded into #5238
