### ISSUE TITLE
Put F# into k8s

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#3126]
- create deployment / pods
    - dont forget legacyserver
        - healthchecks for legacyserver
- add healthchecks and startup probes
- Go through https://andrewlock.net/deploying-asp-net-core-applications-to-kubernetes-part-6-adding-health-checks-with-liveness-readiness-and-startup-probes/
- check if nginx adds content-length header

**Comment by StachuDotNet** [comment]
I think this is done, @pbiggar?
