### ISSUE TITLE
Move away from Result(_, String) error types

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#3142]
At the moment, we're using a lot of different strings in the error types. This causes a number of different problems:

- if we want to add more context around errors, we must change the message
- users need to parse the error message to understand the problem
- the error message infrastructure is unified, causing risk to change it
- users cannot know if they have handled all possible problems

Instead, we will start to use enums. For example, in `JWT::verifyAndExtract_v1`, the errors are currently:
- "Unable to base64-decode signature"
- "Unable to verify signature"
- "Invalid token format

This would become:

```
type verifyAndExtractError_v1 =
| SignatureIsInvalidBase64
| CannotVerifySignature
| InvalidTokenFormat
```

We could also add specific fields to the error types/enums.

**Comment by StachuDotNet** [comment]
We've done a pretty good job of this. Let's have the rest of these come up naturally and create issues then.
