### ISSUE TITLE
Optimize / trim Blazor

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#3168]
You should be able to compile the Blazor files using RunAOTCompilation. However, it failed with the following error:

```
/usr/share/dotnet/sdk/6.0.100-rc.1.21417.9/Sdks/Microsoft.NET.Sdk.BlazorWebAssembly/targets/Microsoft.NET.Sdk.BlazorWebAssembly.6_0.targets(446,5): error : System.ArgumentException: An item with the same key has already been added. Key: /home/dark/.nuget/packages/fsharp.core/5.0.3-beta.21352.5/contentFiles/any/netstandard2.0/FSharp.Core.xml [/home/dark/app/fsharp-backend/src/Wasm/Wasm.fsproj]
/usr/share/dotnet/sdk/6.0.100-rc.1.21417.9/Sdks/Microsoft.NET.Sdk.BlazorWebAssembly/targets/Microsoft.NET.Sdk.BlazorWebAssembly.6_0.targets(446,5): error :    at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior) [/home/dark/app/fsharp-backend/src/Wasm/Wasm.fsproj]
/usr/share/dotnet/sdk/6.0.100-rc.1.21417.9/Sdks/Microsoft.NET.Sdk.BlazorWebAssembly/targets/Microsoft.NET.Sdk.BlazorWebAssembly.6_0.targets(446,5): error :    at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value) [/home/dark/app/fsharp-backend/src/Wasm/Wasm.fsproj]
/usr/share/dotnet/sdk/6.0.100-rc.1.21417.9/Sdks/Microsoft.NET.Sdk.BlazorWebAssembly/targets/Microsoft.NET.Sdk.BlazorWebAssembly.6_0.targets(446,5): error :    at Microsoft.NET.Sdk.BlazorWebAssembly.ComputeBlazorPublishAssets.GroupResolvedFilesToPublish(Dictionary`2 resolvedFilesToPublishToRemove, Dictionary`2 resolvedAssemblyToPublish, Dictionary`2 satelliteAssemblyToPublish, Dictionary`2 resolvedSymbolsToPublish, Dictionary`2 resolvedNativeAssetToPublish) [/home/dark/app/fsharp-backend/src/Wasm/Wasm.fsproj]
/usr/share/dotnet/sdk/6.0.100-rc.1.21417.9/Sdks/Microsoft.NET.Sdk.BlazorWebAssembly/targets/Microsoft.NET.Sdk.BlazorWebAssembly.6_0.targets(446,5): error :    at Microsoft.NET.Sdk.BlazorWebAssembly.ComputeBlazorPublishAssets.Execute() [/home/dark/app/fsharp-backend/src/Wasm/Wasm.fsproj]
```

Nothing I could do would make this work.

I suspect that once we're not on bleeding edge F# & .NET (we're on a nightly build to make something else work), this might work.

I doubt trimming will work, as we use reflection in the JSON serializers. It doesn't look like [source generators](https://www.stevejgordon.co.uk/playing-with-system-text-json-source-generators) are going to be in F# anytime soon, but it might be possible to write the source generator in C#.

**Comment by pbiggar** [comment]
Steps to test:
- add the wasm workload to the docker container: `sudo dotnet workload install wasm-tools`
- enable `IsPublishable` and `RunAotCompilation` in Wasm.fsproj
- make sure `IsTrimmable` is set to false in Wasm.fsproj
- from fsharp-backend run `dotnet publish -c Release`

**Comment by pbiggar** [comment]
The latest attempt gets further, but is now blocked by https://github.com/dotnet/aspnetcore/issues/37690

**Comment by StachuDotNet** [comment]
We made some discoveries made in a 1:1 with @pbiggar yesterday

Cloning the aspnetcore project (https://github.com/dotnet/aspnetcore/) and compiling the Web.JS project isn't too bad. We can use this to get a reasonable Blazor IO .js module to work with.

There are a few steps involved:
- follow instructions here https://github.com/dotnet/aspnetcore to clone recursively. ensure dependencies are installed, including java. (openjdk worked fine for me)
- edit `src/Components/Web.JS/webpack.config.js`; set `.optimization.minimize` to `false`
- `cd src/Components` and run `build.sh` here
- you'll find the output in `src/Components/Web.JS/dist/Release/blazor.webassembly.js`
- example output in a gist: https://gist.github.com/StachuDotNet/a6a5943823d1ad1603807b949eb72f5c
- we can import that file into our client code, with care to include `autostart="false"` in the script tag
- if we've done this^, we can call a fn on the exposed `Blazor` object: `Blazor.start(options)`
- next step here is to figure out what that `options` object should look like
- a combination of [an example by them](https://github.com/dotnet/aspnetcore/blob/a18aeb5dacbe473152da97fe8b289a89163b50f2/src/Components/WebAssembly/testassets/HostedInAspNet.Client/wwwroot/index.html#L17) and [our current hacked boot loader](https://github.com/darklang/dark/blob/6cbe95a69de39706ffd0b7e33653d1b10162721d/fsharp-backend/src/Wasm/static/BlazorWorker.js#L792) might do the trick
