### ISSUE TITLE
404 tab won't list 404s if an endpoint with that name ever existed

### ISSUE THREAD

**Issue by DestyNova** [darklang/dark#3225]
While half-following the tutorial, I created a POST endpoint named `/test` which returned a hard-coded value, then deleted it before coming to the "DataStore" section which explained how to use the 404 tab to create an endpoint based on a captured 404 response.
However, I was confused when the 404 tab was empty for me. I tried making a request to `/test2` instead, which produced an entry in the 404 tab and allowed me to create a new endpoint with that name.
Then I deleted that endpoint and tried the request for `/test2` again, which stored a 404 trace but did not repopulate the 404 tab.

It seems that Dark will never show an endpoint in the 404 tab if you ever had an endpoint matching that route spec, but this is counterintuitive and it should probably only do that if you _currently_ have a matching endpoint.

**Comment by pbiggar** [comment]
Thanks for the report.

I played around with it and it seems like the 404s don't appear if the deleted handler is in the trash - does that match your experience? that is, if you go to the "deleted" section and permanently remove them, do they re-appear in the 404 section?

Agreed this kinda sucks though.

**Comment by DestyNova** [comment]
Ah, I see -- I must admit not having looked at the "deleted" section or understanding what it was. Confirmed that they reappear in the 404 section after permanently removing them. :+1:

**Comment by pbiggar** [comment]
Going to do this differently in the new version so this bug won't apply
