### ISSUE TITLE
Plan for switching over to F# version

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#3239]
- [x] Switch Cronchecker (#3331)
- [x] switch APIServer
  - [x] #3255
  - [x] #2976
  - [x] Put a few APIServers in rotation, with a header to direct to them
  - [x] ensure that static assets always go to old editor-deployment servers
  - [x] Test new APIServers
  - [x] Switch over to APIservers, except for static assets upload
  - [x] observe error rate via rollbars
- [x] switch BWDServer (#3690)
- [x] Switch Queueworker (#3267)
- [x] switch editor (#3254)

**Comment by pbiggar** [comment]
Running for presence.darklang.com

**Comment by pbiggar** [comment]
BwdServer complete.

**Comment by pbiggar** [comment]
All backend pieces are now the F# versions!

**Comment by StachuDotNet** [comment]
Editor has been switched over

**Comment by pbiggar** [comment]
Done!
