### ISSUE TITLE
not open source? please clarify license

### ISSUE THREAD

**Issue by milahu** [darklang/dark#3241]
[readme](https://github.com/darklang/dark#readme) says

> Dark is source available, not open source.

"source available", so there are sources in

* https://github.com/darklang/dark/tree/main/fsharp-backend/src/LibBackend
* https://github.com/darklang/dark/tree/main/client/src/app
* (etc)

"not open source", what exactly does that mean?

[license](https://github.com/darklang/dark/blob/main/LICENSE.md) says

> These terms do not grant you any license to distribute the software.

for example:

* can i fork dark?
* can i modify my fork of dark?
* can i rename my fork of dark?
* can i publish binary releases of my fork?

how do you want to enforce your restrictions?
for example, i can easily publish my fork on a tor-hidden server

or is this intended to protect against other startup companies?
(large corporations will steal your code anyway)

my use case:
im trying to build a very similar tool, a [graphical nixos config editor](https://github.com/nix-gui/nix-gui/issues/176),
which has a similar backend, but a slightly different interface
&rarr; domain specific editor for a different domain
next to dark, my other candidate is the [hazel editor](https://hazel.org/)

**Comment by StachuDotNet** [comment]
this (from the license) feels pretty simple to me:

> Dark grants to the individual or entity agreeing to these terms (“you”) a license to use and modify the software, only for the purpose of creating and contributing improvements, bug fixes or other changes of the software (“Contributions”) to Dark.

So, your use case would not be supported under this license.

**Comment by pbiggar** [comment]
To clarify, "open source" and "source available" are both terms of art:
- https://opensource.org/osd
- https://en.wikipedia.org/wiki/Source-available_software

When we say that it's not open source, we want to make sure people know that even though the repo is public on github, the license does not allow reuse and Dark's code is all owned by Darklang, as described in the license: https://github.com/darklang/dark/blob/main/LICENSE.md

> can i fork dark?

The license says:

>  a license to use and modify the software, only for the purpose of creating and contributing improvements, bug fixes or other changes of the software (“Contributions”) to Dark. 

So you're not allowed to "fork" Dark in the OSS sense, which is what I think you mean. However, you are allowed create a github fork for the purpose of contributing to Dark.

> can i modify my fork of dark?

As above, "forking" in the OSS sense is not allowed.

> can i rename my fork of dark?

As above, "forking" in the OSS sense is not allowed.

> can i publish binary releases of my fork?

As above, "forking" in the OSS sense is not allowed.


> how do you want to enforce your restrictions?
> for example, i can easily publish my fork on a tor-hidden server

Yes, it is possible to do that - it isn't legal to do it though.

> or is this intended to protect against other startup companies?
> (large corporations will steal your code anyway)

It's intended to ensure a) big cloud providers don't run Dark and make all the money that would instead be used to sustain the Dark community, and b) that we have control over where and how Dark is run to ensure it matches the vision we have for Dark.

(Yes, big companies could steal portions of it without us knowing, but it would be a struggle for them to steal and sell the whole product without ramifications).



> my use case:

> im trying to build a very similar tool, a graphical nixos config editor,
> which has a similar backend, but a slightly different interface

> → domain specific editor for a different domain
> next to dark, my other candidate is the hazel editor

I'm not a lawyer, but if you read through the Dark editor code and get ideas from it for your editor, I don't think that violates the license. (Copyright covers the text of the code, not the ideas behind it).

The main idea behind the editor is that the program is represented as [an AST](https://github.com/darklang/dark/blob/c7bc0df64f2beedc994aad37d5c985716e1db37c/client/src/libshared/FluidExpression.resi#L7), then it is ["pretty-printed"](https://github.com/darklang/dark/blob/c7bc0df64f2beedc994aad37d5c985716e1db37c/client/src/fluid/FluidPrinter.res#L12) into [tokens](https://github.com/darklang/dark/blob/c7bc0df64f2beedc994aad37d5c985716e1db37c/client/src/fluid/FluidToken.res#L490), and when changes are made [the edits are made directly](https://github.com/darklang/dark/blob/c7bc0df64f2beedc994aad37d5c985716e1db37c/client/src/fluid/Fluid.res#L3950) on the AST.

I feel confident that the ideas behind the code are much more valuable for your use case than forking the actual code, which I'd recommend against even if it were allowed - it's honestly a bit of a nightmare in this area. But the ideas are sound!

**Comment by milahu** [comment]
so dark has a "monopoly license" and wants to be a [cathedral](https://en.wikipedia.org/wiki/The_Cathedral_and_the_Bazaar)

fine by me : )
i will simply use the general-purpose [hazel editor](https://hazel.org/) (MIT license) to create my domain-specific editor

last question: why not dual license? &rarr; commercial license + GPL
GPL would force all non-commercial forks to publish their full source ("passive" contributions to dark)
commercial license would allow megacorp to host dark instances without publishing their source
other projects with dual license: mysql, ghostscript, Qt, ...

**Comment by pbiggar** [comment]
> last question: why not dual license? → commercial license + GPL

The vision of Dark is that there's only one instance running anywhere (that is, the one at darklang.com). The reason for this is that we want to be able to have the ability to make automatic upgrades across the ecosystem without having to worry about breaking some installs somewhere. So we set the license to match the expectation.

Which is to say, we don't actually want any forks.

That said, if some of our code is useful to other projects, we might be happy to relicense components of it.
