### ISSUE TITLE
Port HttpClient v0 - v4 to F#

### ISSUE THREAD

**Issue by StachuDotNet** [darklang/dark#3242]
This is an issue around this project card: https://github.com/darklang/dark/projects/1#card-66955422

Notes:
- HttpClientV5 has already been ported; this ticket covers porting the earlier versions.
  - Before (OCaml) maybe [this](https://github.com/darklang/dark/blob/main/backend/libexecution/libhttpclient.ml)?
  - After (F#): [here](https://github.com/darklang/dark/blob/main/fsharp-backend/src/BackendOnlyStdLib/LibHttpClient5.fs)
- files to port live in [fsharp-backend/src/BackendOnlyStdLib](https://github.com/darklang/dark/tree/main/fsharp-backend/src/BackendOnlyStdLib)

**Comment by StachuDotNet** [comment]
I'm finding references of v0, v1, v2, and v5, but I'm not seeing anything related to a v3 or v4.

Have I somehow missed them? Did they get very quickly phased out, or is there some other history?

**Comment by pbiggar** [comment]
The ocaml versions are in https://github.com/darklang/dark/blob/main/backend/libbackend/libhttpclient.ml

**Comment by StachuDotNet** [comment]
Resolved a while back
