### ISSUE TITLE
Test every function

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#3262]
We want to make sure there are tests for every function. The list of functions without any tests is below.

Tests can be added in https://github.com/darklang/dark/tree/main/fsharp-backend/tests/testfiles. It's fairly self-explanatory, but the [readme](https://github.com/darklang/dark/blob/main/fsharp-backend/tests/testfiles/README.md) provides all the details.

<details

## How I created this list

To get the expected list of functions:

- log in to darklang.com, open the JS console, and type `copy(complete)`.
- paste this into a file: `pbpaste | jq '.[] | .name' -r | sort > expected`

To get the actually tested list of functions:
- `cd dark/fsharp-backend/tests/testfiles/ && grep -o -e "[A-Z][a-zA-Z0-9_]*\.[a-zA-Z0-9]\+_v[0-9]" * -h | sed 's/_v0//g' | sed 's/\./::/' | grep -v "Test::" | sort | uniq | sort > actual`

To see the list of functions that are not tested:
- ` comm -13 actual expected`

With some additional tweaking (remove Json::parse_v0, DarkInternal functions, and HttpClient functions that are tested elsewhere), we get the list of untested functions.

Note that the tested functions doesn't include any that don't have `::` in their names, so things like `assoc` or `||` won't be included. I manually removed those from the list.

</details>

- [x] DB::add_v0
- [x] DB::count
- [x] DB::delete
- [x] DB::deleteAll
- [x] DB::fetchAll
- [x] DB::fetchBy
- [x] DB::fetchByMany
- [x] DB::fetchOneBy
- [x] DB::fetchOneByMany
- [x] DB::get_v2
- [x] DB::insert
- [x] DB::keys
- [x] DB::queryExactFields
- [x] DB::queryExactFieldsWithKey
- [x] DB::queryOneWithExactFieldsWithKey
- [x] DB::queryOne_v2
- [x] DB::queryOne_v3
- [x] DB::schema
- [x] DB::schemaFields_v1
- [x] DB::schema_v1
- [x] DB::update
- [x] Date::<
- [x] Date::<=
- [x] Date::>
- [x] Date::>=
- [x] Date::greaterThanOrEqualTo
- [x] Date::lessThanOrEqualTo
- [x] Date::sub
- [x] Float::roundTowardsZero
- [ ] Http::redirectTo
- [ ] Http::respondWithHeaders
- [ ] StaticAssets::baseUrlFor
- [ ] StaticAssets::baseUrlForLatest
- [ ] StaticAssets::fetch
- [ ] StaticAssets::fetchBytes
- [ ] StaticAssets::fetchLatest
- [ ] StaticAssets::fetchLatestBytes
- [ ] StaticAssets::fetchLatest_v1
- [ ] StaticAssets::fetch_v1
- [ ] StaticAssets::serve
- [ ] StaticAssets::serveLatest
- [ ] StaticAssets::serveLatest_v1
- [ ] StaticAssets::serve_v1
- [ ] StaticAssets::urlFor
- [ ] StaticAssets::urlForLatest
- [ ] String::foreach
- [ ] String::fromChar
- [ ] String::toList
- [ ] Twilio::sendText
- [ ] Twilio::sendText_v1
- [ ] !=
- [ ] +
- [ ] /
- [ ] <
- [x] emit
- [x] emit_v1

**Comment by StachuDotNet** [comment]
Some of these can be removed:
- Float::roundTowardsZero was covered here https://github.com/darklang/dark/commit/bf9031b6dbd25aeb8586fcd500bdbe9719f05207 several months ago
- The Date module has been covered [here](https://github.com/darklang/dark/pull/3493) recently
- The DB module has a PR [in progress](https://github.com/darklang/dark/pull/3519)

Beyond those, these remain:
(making my own comment here so that I'm able to check the checkboxes)

- operators
  I haven't checked yet, but I have to imagine that they're already well-covered somewhere
	- [ ] `!=`
	- [ ] `+`
	- [ ] `/`
	- [ ] `<`

- `String`
  These look pretty straight-forward
	- [ ] `String::foreach`
	- [ ] `String::fromChar`
	- [ ] `String::toList`

- `Http`
	- [ ] `Http::redirectTo`
	  I believe this has been tested [here](https://github.com/darklang/dark/blob/main/fsharp-backend/tests/httptestfiles/response-redirect.test#L2)
	- [ ] `Http::respondWithHeaders`
	  This hasn't been tested. I think this should be straight-forward

- Events
  I believe these are tested [here](https://github.com/darklang/dark/blob/main/fsharp-backend/tests/Tests/EventQueue.Tests.fs)?
	- [ ] `emit`
	- [ ] `emit_v1`

- StaticAssets
  I'm not immediately sure how to go about testing these. That said, I haven't _used_ the static assets API yet, so maybe after some research it will become obvious.
	- [ ] `StaticAssets::baseUrlFor`
	- [ ] `StaticAssets::baseUrlForLatest`
	- [ ] `StaticAssets::fetch`
	- [ ] `StaticAssets::fetchBytes`
	- [ ] `StaticAssets::fetchLatest`
	- [ ] `StaticAssets::fetchLatestBytes`
	- [ ] `StaticAssets::fetchLatest_v1`
	- [ ] `StaticAssets::fetch_v1`
	- [ ] `StaticAssets::serve`
	- [ ] `StaticAssets::serveLatest`
	- [ ] `StaticAssets::serveLatest_v1`
	- [ ] `StaticAssets::serve_v1`
	- [ ] `StaticAssets::urlFor`
	- [ ] `StaticAssets::urlForLatest`

- `Twilio`
  I'm not immediately sure how to go about testing these, besides manually, with personal credentials/phone.
	- [ ] `Twilio::sendText`
	- [ ] `Twilio::sendText_v1`

**Comment by pbiggar** [comment]
> Some of these can be removed:
> 
> * `Float::roundTowardsZero` was covered here [bf9031b](https://github.com/darklang/dark/commit/bf9031b6dbd25aeb8586fcd500bdbe9719f05207) several months ago
> * The `Date` module has been covered [here](https://github.com/darklang/dark/pull/3493) recently
> * The `DB` module has been covered [here](https://github.com/darklang/dark/pull/3519) recently

Cool, I've checked them above.
 
> Beyond those, these remain: (making my own comment here so that I'm able to check the checkboxes)
> 
> * operators
>   I haven't checked yet, but I have to imagine that they're already well-covered somewhere
>   
>   * [ ]  `!=`
>   * [ ]  `+`
>   * [ ]  `/`
>   * [ ]  `<`

These should have explicit tests which duplicate the tests for `equals`, `Int::add`, etc.


> * `Http`
>   
>   * [ ]  `Http::redirectTo`
>     I believe this has been tested [here](https://github.com/darklang/dark/blob/main/fsharp-backend/tests/httptestfiles/response-redirect.test#L2)

I'd prefer to also have a test in testfiles if possible.

> * Events
>   I believe these are tested [here](https://github.com/darklang/dark/blob/main/fsharp-backend/tests/Tests/EventQueue.Tests.fs)?

The underlying functionality is, but not the functions themselves.

I think they could be tested by adding some functionality to LibTest which exposes the state of the queues. That said, it might not be worth the hassle.

   
> * StaticAssets
>   I'm not immediately sure how to go about testing these. That said, I haven't _used_ the static assets API yet, so maybe after some research it will become obvious.

I'm not sure either.

> * `Twilio`
>   I'm not immediately sure how to go about testing these, besides manually, with personal credentials/phone.
>   
>   * [ ]  `Twilio::sendText`
>   * [ ]  `Twilio::sendText_v1`

Yeah, I think that's right. It may be the same with static assets.

**Comment by StachuDotNet** [comment]
- I've manually tested `StaticAssets` functions and all looks good there (for a bit, I was attempting to write integration tests around this, but abandoned efforts)
- I've manually tested `Twilio` module functions and all looks good there
- The `emit` functions are handled with https://github.com/darklang/dark/pull/3538
- The `String` module functions are handled with https://github.com/darklang/dark/pull/3541
- Operator tests have been added here: https://github.com/darklang/dark/pull/3547
  note: `/` (`Float::divide`) was already handled here: https://github.com/darklang/dark/blob/11beee2d20761c8f92f80693096ebb3d39989989/fsharp-backend/tests/testfiles/float.tests#L74-L78

**Comment by StachuDotNet** [comment]
String::forEach_v0 is still missing

**Comment by pbiggar** [comment]
Just merged. So every function is tested now and we can close this issue?

**Comment by StachuDotNet** [comment]
Yes - I've just confirmed. This can be closed.

**Comment by pbiggar** [comment]
🎉
