### ISSUE TITLE
Port QueueWorker

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#3267]
- [x] Port the queueworker code from OCaml to F# (mostly done, but it doesn't actually start as the `main` method is empty)
- [x] Start the queueworker in main
- [x] Determine how the queueworker is going to run (multi-threaded?)
- [x] add queueworker container to containers/
- [x] add queueworker service to services/
- [x] add healthcheck
- [x] Add tests
- [x] determine how we're going to switch over to this

**Comment by pbiggar** [comment]
Deployment plan:

- [ ] Disable actually running the queueworker in code.
- [ ] Deploy 2 workers and see if they stay up
- [ ] Wait until after the security review to actually pull from the queue
- [ ] After the security review, change "dequeue" to only pick from a specific canvas
- [ ] Test that canvas
- [ ] Add 1 worker to the queue, watch it for a few days
- [ ] Add 10 workers to the queue, watch it for a few days
- [ ] Go to 32 workers, and remove 32 ocaml ones. Watch for a few days
- [ ] Go to 64 workers, and remove all the ocaml ones.

**Comment by pbiggar** [comment]
We can in the future look at running multithreaded stuff here, but not yet.

**Comment by pbiggar** [comment]
Given we actually need quite a bit of CPU/memory in these things, I think we should look at multithreading here. How many jobs should we run at once on a single 3 CPU node. Maybe 16, and have 4 nodes?

**Comment by pbiggar** [comment]
The new plan is to implement a new queue #3777, and the F# queueworker would pull from that queue. Then we set feature flags at `emit` and choose which canvases/handlers to send there then.

- [ ] implement new queue
- [ ] add tests and local emulator
  - [ ] tests needed for each state transition in the diagram, especially errors
- [ ] migrate DB
- [ ] deploy and get containers running in production
- [ ] add feature flag to `emit` on canvases
- [ ] do tests of the queue in production
- [ ] look at honeycomb and see if we have sufficient instrumentation
- [ ] add honeycomb triggers if something goes awry with the queue
- [ ] test disabling with admin rules in production
- [ ] watch each emiting/cron canvas switch to the new queueworker.

**Comment by StachuDotNet** [comment]
> ... Then we set feature flags at emit and choose which canvases/handlers to send there then.

This is to migrate slowly to the F# queueworker, rather than all at once?

**Comment by pbiggar** [comment]
> > ... Then we set feature flags at emit and choose which canvases/handlers to send there then.
> 
> This is to migrate slowly to the F# queueworker, rather than all at once?

Yes

> > test disabling with admin rules in production
> 
> What does this mean? Disabling the queueworker for general purposes? (what do we normally do that for? in case of emergencies?)

We have a way to disable a user's queues in case something goes awry (either abuse or operational issue).

**Comment by pbiggar** [comment]
Fyi, made a new version of the doc with the state diagram in a mermaid format!

https://github.com/darklang/dark/pull/3786/files#diff-5f242dada1ad8afc2b333f365391724a7d2d97e1b0a757f64f46a533df82eb64

**Comment by pbiggar** [comment]
Progress report: the first PR was merged and queue code is running in production. I ran a few tests by flipping the feature flag on the canvas, and it worked! Hoenstly a little surprised but there we go.

**Comment by pbiggar** [comment]
Progress report, have moved maybe 30 users over to the new queue. Doing it in larger chunks going forward.

**Comment by pbiggar** [comment]
Moving this here

## 4th version
- [x] run more than one queue at a time
- [x] validate users transitioned over work
- [x] check what operational stuff will go off if we move the queue
- [x] get a sense of what memory and cpu values are like (don't seem usable)
- [x] test out more than one queue at a time
- [x] fix pusher serialization with `libdarkinternal::pushStrollerEvent_v1`

## 5th version
- [ ] move the rest of the users over to the new queue
- [ ] Why is there a two minute gap where no events are run after a deploy
- [ ] why do i see exceptions in the log that aren't in rollbar and telemetry
- [ ] fix exception `Status(StatusCode="DeadlineExceeded"`

## finishing steps
- [ ] add honeycomb triggers if something goes awry with the queue

**Comment by pbiggar** [comment]
Done!
