### ISSUE TITLE
Infinite precision integers should be available, and possibly the default

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#3279]
Problem: Infinite precision integers are far more useful (lowr complexity) than ones limited to a particular size, as users do not have to deal with overflow or underflow.

The F# v1 integers initially used bigint, however since the behaviour of bigint did not extend to the database, it didn't make sense to switch over fully.

To be Evaluated:

We know how to implement this in the Dark engine, but we do not know how to implement this in the database. It's important that Dark values can be used in the database in much the same manner in which they're used in the runtime. This means we need to be able to implement storage and retrieval in the UserDB, as well as queries using the SQLCompiler. We are currently using postgres 9.6, but intend to migrate to a DB supporting live-migrations such as Google Spanner or CockroachDB.

- [ ] look at our next-gen potential DBs (CockroachDB and Google) and determine if either will support infinite-precision integers

Implementation:

- the field of EInt, PInt, and DInt should use a `bigint` (See #3186)
- check any implicit or explicit int conversions (those raise exception in .NET) (see #3186)
- the editor handles overflow - this can be removed
- determine how to support infinite precision integers in our DB

**Comment by StachuDotNet** [comment]
folding this into #5243 for now
