### ISSUE TITLE
Decide how to handle arithmetic errors (e.g. division by 0)

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#3282]
some arithmetic operations can lead to errors:

- division by 0
- modulus by 0

These should return `Result (Int, IntError)`:

```
Int::divide(Int: a, Int: b) -> Result (Int, Error)
Int::mod(Int: a, Int: b) -> Result (Int, Error)
Int::sum(List Int: a) -> Int
```

One problem here is that the error rail is a little cumbersome, and so making obvious `int` operations use `Results` will make them unweildy to use. So we need to iterate on the error rail before this makes sense, practically.

**Comment by StachuDotNet** [comment]
Avail two versions of each dangerous fn - one that's safe (Result) and one that's unsafe.

**Comment by StachuDotNet** [comment]
folding this into #5243
