### ISSUE TITLE
Support integers of other sizes

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#3283]
it can be useful to have integers of specific sizes, in order to better model specific values or enforce overflow

We should add int8, int16, int32, int64, uint8, uint16, uint32, uint64.

- [ ] design entry system for non-infinite-precision integers. How do we know something is an `int8` vs a `uint32`.

**Comment by StachuDotNet** [comment]
We've done this. Infinite/variable size integers tracked (for right now - will probably merge shortly) in #3279.
