### ISSUE TITLE
allow inserting unicode chars via escaping

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#3288]
Followup to #2565.

We should support unicode characters using the escape sequences. F# supports the following:

> Unicode character | \DDD (where D indicates a decimal digit; range of 000 - 255; for example, \231 = "ç")

> Unicode character | \xHH (where H indicates a hexadecimal digit; range of 00 - FF; for example, \xE7 = "ç")

> Unicode character | \uHHHH (UTF-16) (where H indicates a hexadecimal digit; range of 0000 - FFFF; for example, \u00E7 = "ç")

> Unicode character | \U00HHHHHH (UTF-32) (where H indicates a hexadecimal digit; range of 000000 - 10FFFF; for example, \U0001F47D = "👽")

**Steps:**

- [ ] Design unicode escaping system, preferably starting with a survey of languages that do this well
- [ ] implement #2565 
- [ ] Add unicode escaping system

**Comment by StachuDotNet** [comment]
folded into #5243
