### ISSUE TITLE
[roadmap] types and type system

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#3293]
- [Integer](https://github.com/darklang/dark/issues?q=label%3Atype%3Ainteger+label%3Av-next)
- [String](https://github.com/darklang/dark/issues?q=label%3Atype%3astring+label%3Av-next)
- [Character](https://github.com/darklang/dark/issues/?q=label%3Av-next+label%3Atype%3Acharacter)
- [Float](https://github.com/darklang/dark/issues/?q=label%3Av-next+label%3Atype%3Afloat)
- [Tuple](https://github.com/darklang/dark/issues/?q=label%3Av-next+label%3Atype%3Atuple)
- [Bool](https://github.com/darklang/dark/issues/?q=label%3Av-next+label%3Atype%3Abool)
- [List](https://github.com/darklang/dark/issues/?q=label%3Av-next+label%3Atype%3Alist)
- [Dictionary](https://github.com/darklang/dark/issues/?q=label%3Av-next+label%3Atype%3Adict)
- [Option/Result](https://github.com/darklang/dark/issues/?q=label%3Av-next+label%3Atype%3Aresult)
- [Set](https://github.com/darklang/dark/issues/?q=label%3Av-next+label%3Atype%3Aset)
- [Regex](https://github.com/darklang/dark/issues/?q=label%3Av-next+label%3Atype%3Aregex)
- [UUID](https://github.com/darklang/dark/issues/?q=label%3Av-next+label%3Atype%3Auuid)
- [Date](https://github.com/darklang/dark/issues/?q=label%3Av-next+label%3Atype%3Adate)
- [Bytes](https://github.com/darklang/dark/issues/?q=label%3Av-next+label%3Atype%3Abytes)

## Transitioning to new format, labels not added yet
- [Password](https://github.com/darklang/dark/issues/?q=label%3Av-next+label%3Atype%3Apassword)
- [Null](https://github.com/darklang/dark/issues/?q=label%3Av-next+label%3Atype%3Anull)
- [Record](https://github.com/darklang/dark/issues/?q=label%3Av-next+label%3Atype%3Arecords)
- [Enum](https://github.com/darklang/dark/issues/?q=label%3Av-next+label%3Aenums)
- [Typechecking](https://github.com/darklang/dark/issues/?q=label%3Av-next+label%3Atypechecking)
- [Type-aliases](https://github.com/darklang/dark/issues/?q=label%3Av-next+label%3Atype-aliases)
- [Traits](https://github.com/darklang/dark/issues/?q=label%3Av-next+label%3Atraits)
- [JSON-serialization](https://github.com/darklang/dark/issues/?q=label%3Av-next+label%3Ajson-serialization)
- [imperative-coding](https://github.com/darklang/dark/issues/?q=label%3Av-next+label%3Aimperative-coding)

- [x] #3414
- [x] #3415
- [ ] #3416
- [ ] v2 dates
- [ ] v2 passwords
- [ ] #3420
- [x] #3427
- [x] #3447
- [x] #3448
- [x] #3445
- [ ] Type aliases
- [x] #3451
- [x] #3449

**Comment by StachuDotNet** [comment]
these are all captured elsewhere at this point, especially in #5243
