### ISSUE TITLE
Float operators are not yet supported

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#3303]
Dark's operators (`+`, `-`, `*`, etc) work on integers. In Dark v1, we use `Float::+` instead, which doesn't suck but isn't great

**Non-solution**: We speculated that we could use the editor to simply hide the Float:: part. However, that doesn't allow polymorphism, you can't have a library that takes numbers of any kind and (for example) sums them.

**Solution**: use traits to support reuse of common operators for different types

**Comment by StachuDotNet** [comment]
folded into #5243
