### ISSUE TITLE
Add functions for tuples

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#3309]
After tuples are added, we need library support for them. These functions should be added

```
// Access
Tuple2::first ('a,'b) -> 'a
Tuple2::second ('a,'b) -> 'b

// Creation
Tuple2::pair ('a, 'b) -> ('a,'b)

// Manipulation
Tuple2::mapFirst (('a,'b), ('a -> 'c)) -> ('c, 'b)
Tuple2::mapSecond (('a,'b), ('b -> 'c)) -> ('b, 'c)
Tuple2::mapBoth (('a,'b), ('a -> 'c), ('b -> 'd)) -> ('c, 'd)

Tuple2::swap (('a,'b)) -> ('b, 'a)
```

- [ ] Add the Tuple2 functions above
- [ ] add the equivalents for Tuple3
- [ ] Look at https://package.elm-lang.org/packages/TSFoster/elm-tuple-extra/latest/Tuple3 to see if there are useful functions there

**Comment by StachuDotNet** [comment]
I think that the fns listed in the OP, and their Tuple3 equivalents, are enough for now. I'm not seeing anything else that's necessary until someone reaches for them and asks about them.
