### ISSUE TITLE
Add tuple `let` destructuring

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#3402]
We want to support code like: `let (myString, myInt) = ("str", 6)`, where the user can destructure the tuple into values on the right-hand-side.

This is a prototype of an interaction model for this:

```
'let ' =>
  let |___ = ___
( =>
  let (|) = ___
myString =>
  let (myString|) = ___
, =>
  let (myString, |___) = ___
'myInt) = ' =>
  let (myString, myInt) = |___
( =>
  let (myString, myInt) = (|)
'"str", ' =>
  let (myString, myInt) = ("str", |___)
5) =>
  let (myString, myInt) = ("str", 5)|

```

**Comment by StachuDotNet** [comment]
I've been thinking through how this will look, and suspect @pbiggar you've had some ideas around this.

[here](https://github.com/darklang/dark/blob/ace459f87635cb0c769ac9a6a29f8a13efe9d233/fsharp-backend/src/LibExecution/ProgramTypes.fs#L72) is the current definition for how `let` works.

```fsharp
| ELet of id * string * Expr * Expr
```

The main question I'm thinking through is:
should `let (a, b) = (1, 2)` be powered by the existing `Pattern` structure, or with a new structure?

A 'new structure' could look like this:

```fsharp
type LetPattern =
  | Simple of string
  | Constructor of ...
  | Tuple of Expr * Expr * List<Expr>
  | ...

...
| ELet of id * LetPattern * Expr * Expr
...
```
with the current `Pattern` would be renamed to `MatchPattern`, and `LetPattern`.

Looking at prior art, [F#'s docs](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/functions/let-bindings) seem to imply that there's only one "Pattern" concept, and splitting "let patterns" from "match patterns" isn't done.

Using the existing `Pattern` structure as is could look just like:
```fsharp
| ELet of id * Pattern * Expr * Expr
```

, with existing Dark code migrated (?) to just use a `Variable` pattern.


Many of F#'s Patterns are non-exhaustive (e.g. `a :: b` on a list), and these result in compile-time errors there.
Ideally, I think, we avoid that, favoring the inability to represent illegal ASTs, but I'm a bit torn - introducing a new concept may be overkill here?

WDYT?

**Comment by pbiggar** [comment]
I would lean heavily towards the LetPattern idea. Agreed we want to avoid "compile-time" errors, and it seems error prone to have a sort of half pattern (we actually have the same issue with pipes, and it's caused nothing but problems)

**Comment by pbiggar** [comment]
Sounds good. I'm happy to keep the prefixes, agreed it's kinda useful.

**Comment by StachuDotNet** [comment]
A more detailed spec is being worked on here: https://docs.google.com/document/d/10mr811ONuUSm6Q1egfv9dGtpN7QdHwhM96uyW8w0140/edit#

**Comment by pbiggar** [comment]
Done
