### ISSUE TITLE
Create a way of adding types to the http framework

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#3407]
We want to have a fully typed system, where users make requests, the type checker validates it at input, and raises an error if it's the wrong shape.

The obvious solution to this is to add types to the framework. So for example, we would have a `parseJson<MyType>` function, and that would be used in a `HttpMiddleware<MyInputType, MyReturnType>` function.

## What if we don't know the type of the input value?

Today, we don't know the type and that makes us create an unholy Object with whatever fields are input, including null values if they're included. The field names can sometimes even be syntactically invalid in Dark.

When we don't know the type, we could instead infer the type and offer the user the option to create it. The runtime type when we don't know the value would then be based off that inference. For example, for the data:

```
{ 
  "int" = 6,
  "null" = null,
  "tuple" = [ 4, "5", 6, true ]
  "list" = [5,6,7,8]
  "error" = { error: "some error occured" }
}
```

we could infer the type:

```
TRecord [
  ("int", TInt);
  ("null", TOption<TUnknown>);
  ("tuple", TTuple[TInt, TString, TInt, TBool]);
  ("list", TList<TInt>)
  ("error", TResult<TUnknown, TString>)
]
```

Note that we haven't given the type a name yet, but the user could do that with one command.

If there are multiple options, the user could choose between them (eg, the tuple might be a list of `OneOf<TInt, TString, TBool>` instead). We could interactively ask the user for a type to fill in the `TUnknown`s.

If we have multiple traces available, we could look across different traces to pick the best type. For example, if we sometimes get ints and sometimes floats and sometimes ints-inside-strings, we could decide that's a `GenerouslyParsedFloat` (which is an alias of float except it's got a different `ofJson` trait).

## what if we don't know the type of the return value:

We can infer it with type inference or just with the type of the runtime value produced by the analysis engine.

**Comment by StachuDotNet** [comment]
This doesn't quite apply in `dark-next` -- incoming http handler bodies are just Bytes, which users have to then stringify, parse, etc -- it's in their hands.
At some point, we'll undoubtedly have middlewares for specific use cases like this, so after closing this now I'll refer to this issue in an issue on http handlers
