### ISSUE TITLE
Support Regex

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#3415]
Users often ask for regex.

Dark v1 does not have regex, due to the technical challenge that the OCaml native regex implementation we used (re2) does not compile to JS.

We want to use a regex implementation which can not be DOSed. Parse.com apparently had big problems with their regex.

Need a good API for this - regex libraries often have APIs that make them very hard to use

I've never seen a regex implementation that was as easy to use as Perl's, so that's what we're aiming for (in terms of simplicity, not necessarily syntax):

```
# does it match?
if ($str =~ /ul/) { ... }

# capturing
if($line =~ /name:\s+(\w+\s+\w+),\s+period:\s*(\d{4}\-\d{4})/)
  $composers{$1} = $2;
```

I'd love to have editor plugins showing users the state machine for their regex, or helping them write better ones.

**Comment by pbiggar** [comment]
Steps:
- design regex API
- add regex implementation
  - short timeout
  - perhaps no backtracking
  - ensure it works in Wasm
- add way of showing the state machine in the UI

**Comment by StachuDotNet** [comment]
This is great - currently folding into #5243, but will revisit when the time comes
