### ISSUE TITLE
v2 HTTP handlers

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#3423]
- [ ] #3424
- [ ] http handlers should have input and response types
- [ ] instantly create types from trace values

**Comment by pbiggar** [comment]
These aren't how we'll do things in darklang-next.

**Comment by StachuDotNet** [comment]
> These aren't how we'll do things in darklang-next.

I sort of like both of the unchecked boxes here still:

> * [x]  [We shouldn't expect bodies to be unicode strings #3424](https://github.com/darklang/dark/issues/3424)
> * [ ]  http handlers should have input and response types
> * [ ]  instantly create types from trace values

maybe they should be split into separate issues?
Http handlers having Dark types exposed for requests/responses still makes sense to me, and having something like 404s for _types_ of request values still makes sense (though the latter maybe would be better suited for a Discussion)

**Comment by pbiggar** [comment]
Yeah, they should definitely be separate issues.

But also, since we're going to design these in darklang-next, I'm not sure issues/checkboxes are the right tool for it?
