### ISSUE TITLE
Httpclient should have middleware

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#3426]
Similar to the http framework, there are a lit of problems in the HTTP clients that stem from them doing too much.

There's a lot of magic going on, and the magic prevents you from doing things like making http calls with plain bytes. The magic should be replaced with middleware that does stuff like json parsing, etc. There should be low-level http client functions that just take headers and verbs and bytes as bodies, and return the same.

**Comment by StachuDotNet** [comment]
folded into a larger issue
