### ISSUE TITLE
Ensure curl_logging is replicated

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#3461]

**Comment by StachuDotNet** [comment]
Could you please provide some thoughts here? @pbiggar

**Comment by pbiggar** [comment]
In the OCaml version, we logged some properties about httpclient:: calls. I think we do the same but we should check. We should also make sure the key properties are logged.

So to do this you would manually test http checks and read the console output of the server to see opentelemetry requests, and validate the data is present.

The logged attributes do not need to have the same names in both versions, but roughly the same info should be tracked in both.

**Comment by pbiggar** [comment]
I've got as much as is available
