### ISSUE TITLE
Annoyances while building a slack bot

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#3476]
I was building a simple slackbot, and these are some simple annoyances I felt.

- `extract variable` should select the variable so that we can edit its name
- huge text/value is annoying. Maybe support folding, or partial folding (just show as much interesting stuff as we can in 8 lines)
- lists of objects keep indenting, they should line up instead
- the slack notify package function doesn't support blocks
- i want to `wrap in match`, instead of `wrap in if`
- i want to convert an `if` to a `match`
- i was changing the function name, which kept the arguments. When I fully deleted it, with the intent to write a new function name, it converted to a blank and I fully lost the arguments. Perhaps it could wait one more backspace before it fully deletes it
- there's no parens around constructors when they're arguments (no parens anyway, but there were really needed here)
- when filling in arguments, if I add an option the placeholder goes away
- options don't have subtypes (I have `Option`, I want `Option<List<string>>`)

**Comment by StachuDotNet** [comment]
extracted remaining relevant issues out to other Issues
