### ISSUE TITLE
traces don't work well with loops

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#3480]
When iterating through a loop (eg `List::map`), only the trace results for the last iteration of the loop is stored. That is super confusing, and makes it hard to debug lots of things.

To solve this:
- [ ] store every result of every loop iteration
  - we initially did this and had to disable it due to trace size, so we may need to find a way to load traces more efficiently (perhaps partial loading, resumable downloads, etc, which may become easier when we switch traces to cloud storage)
- [ ] add ui to let users see trace results for different iterations

**Comment by StachuDotNet** [comment]
folded into #5238
