### ISSUE TITLE
traces permanently store all functions called while they're active

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#3482]
When you press a `play` button in the editor, the function is executed and its result is stored in the trace. As you edit a canvas, you might press the play button many many times, and each time the result of the function is stored in the trace, and is never cleaned up. This has caused users to have a very slow experience, as the trace grows without bounds, which slows down:

- trace loading from the DB when clicking on the handler
- analysis execution, as the entire trace is serialized and sent to the web worker

The function result is stored using a hash of the arguments. This hash was designed to so that if you changed back to old argument values, the previously calculated value would be available instantly. This is kinda nice but it feels a bit like an optimization, not a core design principle. It also allowed us to ensure that the value was associated with the arguments (and not accidentally report the wrong value). This property is valuable and should be maintained.

**Comment by StachuDotNet** [comment]
folded into a larger issue
