### ISSUE TITLE
Avail deprecated functions in local (dev.) environment

### ISSUE THREAD

**Issue by StachuDotNet** [darklang/dark#3483]
When working on #3256, I wanted to test deprecated lib functions via the client.
Currently this filtering seems to all be done in the front end, so I handled this locally by adjusting client-side logic to not filter those out.
I believe my solution was commenting out this line: https://github.com/darklang/dark/blob/main/client/src/analysis/Functions.res#L133

As I imagine this need arising again, we could add a query param to `include-deprecated-fns=true`, for general use

**Comment by pbiggar** [comment]
We really, really, don't want users adding deprecated functions. I'd suggest that include-deprecated-fns=true only work locally perhaps.

**Comment by StachuDotNet** [comment]
Understood and agreed!

**Comment by pbiggar** [comment]
Closing as it doesn't apply to darklang-next
