### ISSUE TITLE
traces don't work well in functions

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#3484]
When you create code in a function for the first time, the function does not have a trace, and the arguments are Incomplete. This means everything is red and when you try to call other functions, nothing works.

Why? The system is built around trace-driven development, but if you don't have a trace, nothing works.

Some possible solutions:
- Add a warning that you're using the default trace and it doesn't have values for the arguments. Fade the Play button and show a warning about this. Or at least give an error when you try to run something with an incomplete in it.
- Perhaps default traces should use default values for known types. However, that will result in real values being put in the DB, which the user will then have to dig out.
- perhaps a dry-run of some sort might be an idea in this situation?

**Comment by StachuDotNet** [comment]
merged into #5238
