### ISSUE TITLE
"clear db" script breaks when many integration test canvases are in DB

### ISSUE THREAD

**Issue by StachuDotNet** [darklang/dark#3504]
Someone my system got to a state where I had many canvases in my DB that fell under this criteria:
https://github.com/darklang/dark/blob/main/integration-tests/clear-db.sh#L16

`SELECT id FROM canvases WHERE substring(name, 0, 6) = 'test-';`

Because of this, the `run_sql "$SCRIPT";` command of `clear-db.sh` script failed for me, yielding a `Argument list too long` error, preventing integration tests to run.

I resolved this problem locally by updating the SELECT query to include a `limit 100` filter, followed by running clear-db.sh many times over manually. After that, I could run tests again.

While I was able to resolve this locally without too much hassle, it'd be good to prevent such an error again, perhaps either by:
- investigating why I had so many test- canvases (as of right now, I'm unsure), to prevent the problem
- update the clear-db script to LIMIT by default, retrying until no test canvases are left

**Comment by StachuDotNet** [comment]
https://github.com/darklang/dark/pull/3707#issue-1205916392 some related discussion (and a hacky solution) here.

**Comment by pbiggar** [comment]
Closing as it doesn't apply to darklang-next
