### ISSUE TITLE
Deprecated fns missing from ui.html ALLFUNCTIONS variable when injected by F# server

### ISSUE THREAD

**Issue by StachuDotNet** [darklang/dark#3505]
The `{{ALLFUNCTIONS}}` value injected into the ui.html templates includes deprecated functions when fetched by our OCaml server, but not our F# server.

I noticed this because [one of the integration tests](https://github.com/darklang/dark/blob/main/backend/test_appdata/test-fluid_test_copy_request_as_curl.json#L12) includes a deprecated function: `HttpClient::post_v4`.
I'm planning to handle this by using a non-deprecated function, so am not blocked there. (that seems appropriate to me - let me know in #3485 if otherwise)

Is this OK?

**Comment by pbiggar** [comment]
ALLFUNCTIONS should include deprecated functions, since existing canvases might use them (as in this example). So I think the fix is to ensure ALLFUNCTIONS has deprecated functions too.

There is an ApiServer test that checks this - I'm surprised it didn't catch it.

**Comment by StachuDotNet** [comment]
:facepalm: this was probably because I didn't have the legacy HttpClients port branch merged into my working branch...
