### ISSUE TITLE
Ensure all shell scripts have .sh extension

### ISSUE THREAD

**Issue by StachuDotNet** [darklang/dark#3506]
Otherwise, VS Code can get confused about what type of file it is.

**Comment by StachuDotNet** [comment]
Should our python scripts all have .py extensions, @pbiggar?

**Comment by nkilm** [comment]
@StachuDotNet Should I write another shell script which `ensures .sh extension` or just renaming all the files will do the job?

**Comment by pbiggar** [comment]
I'd personally prefer to remove the .sh ending from scripts. However, I do agree it is important for VSCode to accurately recognize file types.

I've never had this issue though - I assumed VSCode looks at the `#!/usr/bin/env bash` opening line, which we are consistent about (same with python scripts).

What am I missing?

**Comment by nkilm** [comment]
@pbiggar Occasionally, in my system VSCode fails to recognise the shell script files. But it works fine. 

So `.sh` extension should be removed from all script files?

**Comment by StachuDotNet** [comment]
I have the same issue as @nkilm. I also find it useful to have the extensions (.py, .sh) with the files for when I'm _outside_ of VS Code - i.e. when I'm `cd`ing and `ls`ing my way through files in terminal.
