### ISSUE TITLE
Allow deleting unlocked datastores

### ISSUE THREAD

**Issue by StachuDotNet** [darklang/dark#3545]
I have a datastore https://darklang.com/a/stachudotnet#db=112355512 which I've cleared with `DB::deleteAll [dbname]`. Since purging the records, I see that the DB appears as unlocked, yet the Delete button is disabled - this is surprising.

**Comment by pbiggar** [comment]
I speculate that the DB name is used in some code? I think that might prevent it from being deleted.

I think that's the right behaviour, but also that we could do a much better job explaining that. An error message or explanation should be added.

**Comment by StachuDotNet** [comment]
Ah, that was it (name being 'used' elsewhere). Was able to delete the DB now.
