### ISSUE TITLE
Client fails to deserialize static asset deploy event

### ISSUE THREAD

**Issue by StachuDotNet** [darklang/dark#3546]
When I deploy static assets as the client is open, the client seems to fail to deserialize and handle the corresponding Pusher.com event:
![image](https://user-images.githubusercontent.com/906686/157295733-37166245-91d1-4a92-a000-73bea33b3d39.png)

After a refresh, I can see my newly-deployed assets

**Comment by pbiggar** [comment]
Not applicable in darklang-next.
