### ISSUE TITLE
Graceful shutdown functions dont seem to be called.

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#3553]

**Comment by StachuDotNet** [comment]
Is this related to the `shutdownCallback` fns of `runKubernetesServer` (within CronChecker and QueueWorker), or something else?

**Comment by pbiggar** [comment]
Yes, exactly.

**Comment by pbiggar** [comment]
Looking through the history, it seems this was never hooked up in the first place.

**Comment by pbiggar** [comment]
Solvd in #3604
