### ISSUE TITLE
Port remains of webserver_apiserver.ml.unported

### ISSUE THREAD

**Issue by StachuDotNet** [darklang/dark#3561]
`webserver_apiserver.ml.unported` [still remains](https://github.com/darklang/dark/blob/main/fsharp-backend/src/LibBackend/webserver_apiserver.ml.unported) in the F# codebase at time of writing.

At some point, we need to finish the port or decide its functionality is no longer needed.

It has these functions:
- [ ] `upload_function`
- [ ] `save_test_handler`
- [ ] `admin_api_handler`

Extracting this from #3552

**Comment by pbiggar** [comment]
> * [ ]  `request_to_rollbar`
> * [ ]  `static_etag_for`
> * [ ]  `static_handler`

These have been functionally ported.

**Comment by pbiggar** [comment]
The others we can leave but we can move this task to much later since it's not holding anything up.

**Comment by StachuDotNet** [comment]
Great, edited OP

**Comment by pbiggar** [comment]
Closing as it doesn't apply to darklang-next
