### ISSUE TITLE
Consider banning `string` function

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#3567]
It's impossible to tell statically if the ToString function we are calling is one that we intend to call or merely the built-in `Object.ToString()`. This particularly came up for FQFnName.toString.

**Comment by pbiggar** [comment]
That wouldn't prevent string interpolation.

Look at https://www.nuget.org/packages/ToStringWithoutOverrideAnalyzer/

**Comment by StachuDotNet** [comment]
Folded into #5246
