### ISSUE TITLE
Attempting to re-bind value results in ambiguous UI

### ISSUE THREAD

**Issue by StachuDotNet** [darklang/dark#3570]
![image](https://user-images.githubusercontent.com/906686/158172534-4ac42163-48d7-4964-8eb3-2584cf6ea83c.png)
This user function has a `to` parameter. Within code, I attempt to create a map of the input, and bind to the same name.

Later when trying to use the binding, I'm presented with both options.

We should either:
- disallow the attempt of re-binding values (i.e. complain in my first line of code)
- only show the latest binding in the UI

**Comment by pbiggar** [comment]
Closing as it doesn't apply to darklang-next
