### ISSUE TITLE
Date module should document timezone info / UTC

### ISSUE THREAD

**Issue by StachuDotNet** [darklang/dark#3574]
![image](https://user-images.githubusercontent.com/906686/158431062-77710d59-c492-4f6d-a87e-472cf63da3f0.png)
(executed at 12:5x pm EST)

`Date::now |> Date::hour` can be surprising to users outside of GMT. This confusion could be avoided by updating documentation of `Date::now` (and maybe others)

**Comment by pbiggar** [comment]
I'm hoping to add more info to values, to give extra perspective (for example, with an int we could show it in hex, binary, etc). So for a date we could explain that the date is UTC, then show it in localtime (based on browser) or even allow the users to add some timezones they like in settings.

**Comment by StachuDotNet** [comment]
> with an int we could show it in hex, binary, etc

Once we have proper user types, we could allow users to customize the corresponding 'render' in some way.
I imagine similar customization for data-entry of user types, but both are certainly outside the scope of this issue

**Comment by StachuDotNet** [comment]
folded into #5239
