### ISSUE TITLE
Investigate and resolve blazor load error

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#3589]
When loading blazor, many of the files it needs will not load in the browser. The browser stops being able to make a connection to the server. This only happens in production. It is most commonly reproduced by loading and then doing another load from a clean cache.

I managed to reproduce the error:

```
Uncaught exception Blazor worker failure TypeError: Failed to fetch
    at loadResource (blob:https://darklang.com/dacea6f8-981c-4a6a-9522-f78faeed6aeb:738:24)
    at blob:https://darklang.com/dacea6f8-981c-4a6a-9522-f78faeed6aeb:732:11
    at Array.map (<anonymous>)
    at Object.loadResources (blob:https://darklang.com/dacea6f8-981c-4a6a-9522-f78faeed6aeb:731:39)
    at createEmscriptenModuleInstance (blob:https://darklang.com/dacea6f8-981c-4a6a-9522-f78faeed6aeb:220:52)
    at blob:https://darklang.com/dacea6f8-981c-4a6a-9522-f78faeed6aeb:772:25 undefined undefined undefined
e.<computed> @ appsupport-0aab008024f907c251bfe9927856eeebed075655f5139be469f7af1ceaf66459.js:179373
```

![image](https://user-images.githubusercontent.com/181762/158612539-68bd0423-d2e5-4a95-b32f-362e4d7dddaa.png)

And it seems to happen when part of the load time's out:

![image](https://user-images.githubusercontent.com/181762/158618815-e711f9e7-6526-4225-a697-f6b0f6646726.png)

Unclear why these loads time out, but this happens in about 1/4 of the times I refresh.

_Originally posted by @pbiggar in https://github.com/darklang/dark/issues/3254#issuecomment-1069216438_

**Comment by pbiggar** [comment]
Some investigation:
- the items being requested are uploaded to the bucket and configured properly
- no observable differences between things that succeed and things that fail, at the bucket level
- taking the failing url and fetching it via curl succeeds
- the load balancer does not have any logs for these requests
- the error in Chrome is ERR_CONNECTION_CLOSED
- all requests (success and failure) to the static assets load balancer are "h3" (http3)

ERR_CONNECTION_CLOSED means it wasn't able to make a connection:
- chrome has a connection limit?
- ddos protection at google?
- my os/router/isp/other doesn't like that many connections of that size/content-type/etc?

**Comment by pbiggar** [comment]
I don't have any clues here so I'll see who I can ask.

**Comment by pbiggar** [comment]
Using correct content-types didn't change anything.

**Comment by pbiggar** [comment]
- [ ] ask blazor people about it
- [ ] ask google support about it
- [ ] try a different browser

**Comment by pbiggar** [comment]
Google says it's not them.

**Comment by StachuDotNet** [comment]
Given I could eventually replicate this on my laptop, maybe we should figure out what's consistent between my laptop and your computer, and not consistent with my desktop where I can't replicate. 

Both my desktop and laptop are Ubuntu with Chrome on WiFi. The initial differences that come to mind would be drivers, chrome versions, extensions loaded, internet config settings, Ubuntu versions (desktop is 21.10 - maybe laptop is 21.04?) or underlying linux versions.

What variables would be worth looking at, if that seems a useful path?

**Comment by pbiggar** [comment]
You're not going to believe this but I just upgraded to Chrome 99 and I can't replicate this anymore!

**Comment by pbiggar** [comment]
This feels like it: https://bugs.chromium.org/p/chromium/issues/detail?id=1286445
