### ISSUE TITLE
Handle issues found by load testing

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#3626]
- [x] 500s reported in nginx (not reported in bwdserver)
  - [ ] report in bwdserver telemetrty
- [x] 502s in nginx (worker_connections)
- [ ] nginx alerts are not shown in honeycomb / elsewhere
- [x] use correct base-nginx file
- [x] update to latest nginx

**Comment by pbiggar** [comment]
- [ ] When load testing, I see errors in traces. Investigate

**Comment by pbiggar** [comment]
I just did a load test, the outcome:

```
 $ wrk -t 50 -c 2000 -d 20s https://trydarkfsharp.builtwithdark.com/fizzbuzz --timeout 4s
Running 20s test @ https://trydarkfsharp.builtwithdark.com/fizzbuzz
  50 threads and 2000 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     2.76s   776.48ms   4.00s    66.50%
    Req/Sec     9.07      7.54    60.00     77.36%
  5701 requests in 20.10s, 7.27MB read
  Socket errors: connect 0, read 0, write 0, timeout 4471
Requests/sec:    283.59
Transfer/sec:    370.55KB
```

Meanwhile, the google load balancer saw 7720 requests, all of which responded with status code 200 (though most took 3-5 seconds).

Nginx saw 7700 of them, all 200.

BwdServer saw 7222 of them, all 200.

And it seems wrk only successfully completed 5701 of them.

**Comment by StachuDotNet** [comment]
> wrk
https://github.com/wg/wrk FYI, anyone else reading.

**Comment by pbiggar** [comment]
Overall, 300 r/s isn't great, especially since it doesn't tax the servers even one little bit, but on the other hand we're currently typically doing 1 r/s on average, so we're well over provisioned for this.

Going to close this and leave optimization to another day.

**Comment by StachuDotNet** [comment]
> I just did a load test, the outcome:

Could you help me interpret these results?

I believe `wrk` is:
- running as many `GET https://trydarkfsharp.builtwithdark.com/fizzbuzz` requests as possible within 20s of testing
- with the constraints: up to 2000 total connections at a time, split across up to 50 threads, with a timeout per-request of 4s

> `5701 requests in 20.10s`

So, within the 20s it was able to make 5701 total requests (incl. getting a response)

> the google load balancer saw 7720 requests

The difference between 7720 and 5701 is assumedly the requests that were fired, but which we didn't get a response back yet within the 20s?

> Nginx saw 7700 of them
> BwdServer saw 7222

Why wouldn't they see all 7720?

**Comment by pbiggar** [comment]
> > I just did a load test, the outcome:
> 
> Could you help me interpret these results?
> 
> I believe `wrk` is:
> 
> * running as many `GET https://trydarkfsharp.builtwithdark.com/fizzbuzz` requests as possible within 20s of testing
> * with the constraints: up to 2000 total connections at a time, split across up to 50 threads, with a timeout per-request of 4s
> 
> > `5701 requests in 20.10s`
> 
> So, within the 20s it was able to make 5701 total requests (incl. getting a response)

Yes, and also 4471 where it did not get a response within the 4s timeout.

> > the google load balancer saw 7720 requests
> 
> The difference between 7720 and 5701 is assumedly the requests that were fired, but which we didn't get a response back yet within the 20s?

Yes.

 
> > Nginx saw 7700 of them
> > BwdServer saw 7222
> 
> Why wouldn't they see all 7720?

I don't know.

**Comment by pbiggar** [comment]
I added a task for the trace errors.

I'm going to declare this closed as the remaining errors are in nginx and I'm removing nginx from the bwdserver
