### ISSUE TITLE
Use dotnet-wasi-sdk once it supports AOT compilation

### ISSUE THREAD

**Issue by StachuDotNet** [darklang/dark#3642]
It'd be great to ship one big .wasm file rather than many .dlls and other files.

[dotnet-wasi-sdk](https://github.com/stevesandersonms/dotnet-wasi-sdk) allows us to do this.

We've tested (after upgrading to .net 7 in another branch) that Dark works with `dotnet-wasi-sdk`, but the project does not currently support AOT builds. Once it does, or once this project is assumedly merged into an official feature of .NET, we should reconsider this.

**Comment by pbiggar** [comment]
Closing as it doesn't apply to darklang-next
