### ISSUE TITLE
FuzzTests Failing on Bad Unicode Strings

### ISSUE THREAD

**Issue by StachuDotNet** [darklang/dark#3649]
Several fuzztests are failing on some odd strings. I'm not sure the title here is correct, but it's my best understanding.

Repro: `./scripts/run-fsharp-fuzzer --filter-test-case 'comparing jwt json' --fscheck-max-tests 100000`

This eventually yields a variant of these results, formatted slightly:
```
Failed after 61715 tests. Parameters:
...redacted...
Shrunk 17 times to:
        DObj (map [("򂭣ခ륣鸫", DNull); ("ﲒ", DNull)])
Result: Exception Expecto.AssertException: .
expected:
("{ 
  ﲒ: null,
  򂭣ခ륣鸫: null
}",
 [|123uy; 32uy; 10uy; 32uy; 32uy; 239uy; 178uy; 146uy; 58uy; 32uy; 110uy; 117uy;
   108uy; 108uy; 44uy; 10uy; 32uy; 32uy; 242uy; 130uy; 173uy; 163uy; 225uy;
   128uy; 129uy; 235uy; 165uy; 163uy; 233uy; 184uy; 171uy; 58uy; 32uy; 110uy;
   117uy; 108uy; 108uy; 10uy; 125uy|])

actual:
("{ 
  򂭣ခ륣鸫: null,
  ﲒ: null
}",
 [|123uy; 32uy; 10uy; 32uy; 32uy; 242uy; 130uy; 173uy; 163uy; 225uy; 128uy;
   129uy; 235uy; 165uy; 163uy; 233uy; 184uy; 171uy; 58uy; 32uy; 110uy; 117uy;
   108uy; 108uy; 44uy; 10uy; 32uy; 32uy; 239uy; 178uy; 146uy; 58uy; 32uy; 110uy;
   117uy; 108uy; 108uy; 10uy; 125uy|])
```

I've spent a while debugging this, and I'm not sure what to do.

<details>
  <summary>Another sample that result in errors, fwiw</summary>

```
DObj (map [("𢡄먞", DNull); ("", DNull)])
Result:
        Exception
  Expecto.AssertException: .
expected:
("{"":null,"𢡄먞":null}",
 [|123uy; 34uy; 239uy; 155uy; 180uy; 34uy; 58uy; 110uy; 117uy; 108uy; 108uy;
   44uy; 34uy; 240uy; 162uy; 161uy; 132uy; 235uy; 168uy; 158uy; 34uy; 58uy;
   110uy; 117uy; 108uy; 108uy; 125uy|])
  actual:
("{"𢡄먞":null,"":null}",
 [|123uy; 34uy; 240uy; 162uy; 161uy; 132uy; 235uy; 168uy; 158uy; 34uy; 58uy;
   110uy; 117uy; 108uy; 108uy; 44uy; 34uy; 239uy; 155uy; 180uy; 34uy; 58uy;
   110uy; 117uy; 108uy; 108uy; 125uy|])
```
</details>

Seemingly, these errors are mostly occurring on DObjs with rare/invalid strings as the keys.
Locally I've gotten around this by changing code to generate a much smaller pool of characters, but that's not ideal.

**Comment by pbiggar** [comment]
I've looked at these and the root cause is that OCaml sorts these objects differently to F#. So they stringify the contents in a slightly different order in some obscure cases.

See https://docs.darklang.com/reference/changelog#discovered-before-july-16-2021:

> Functions whose output relies on the internal ordering of a Dict may have different outputs, specifically, the output Lists may be in a different order. Examples include Dict::keys, Dict::values, and Dict::toList which return Lists of values which are ordered based on the internal ordering in the original Dict.

That's obviously more problematic for Jwt functions that for like `Dict::toList` - is there anything we can do about it (and should we bother)?

**Comment by pbiggar** [comment]
I think we can close this, let me know if I'm mistaken.
