### ISSUE TITLE
Scrolling in Secret input box also unexpectedly scrolls Canvas

### ISSUE THREAD

**Issue by StachuDotNet** [darklang/dark#3661]
https://user-images.githubusercontent.com/906686/162221391-cf3f9c1c-d2cc-430d-a26c-3beab33a8f21.mp4

**Comment by pbiggar** [comment]
Nice! Ive seen this myself. This happens in all UI we add and there's a flag to avoid it somewhere that I guess we didn't set for secret boxes.

**Comment by pbiggar** [comment]
Closing as it doesn't apply to darklang-next
