### ISSUE TITLE
Consider built-in type formatting guideline

### ISSUE THREAD

**Issue by StachuDotNet** [darklang/dark#3666]
See note [here](https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting#for-types-prefer-prefix-syntax-for-generics-foot-with-some-specific-exceptions) about built-in types.
In short, for built-in types, favor `x list` over `List<x>` where possible. (same for `option`, `array`, etc.)

Particular to lists, There's a "C# `List`" / "F# `ResizeArray`" type that also exists in .NET; I think many developers' brains would think of _that_ first upon seeing `List<x>`, esp. if they've worked in C# codebases before.

I'm totally fine getting away from that, but we should mark that in the coding guide, standardize to that, and (as we see it) adjust to use that generally, if so. Right now we use a bit of each option.

Do you have a strong preference one way or the other? I'll be happy to make a coding guide PR

**Comment by pbiggar** [comment]
Well this is some bullshit. F# has irregular verbs? 😂

Why do they do this?

I generally like to stick to their guide but I don't understand why there are five exceptions to memorize (and I think fantomas doesn't do it for us).

**Comment by StachuDotNet** [comment]
I kept coming back to this issue and writing drafts of responses; not worth it!

Every guide out there seems to say "use prefix, except _sometimes_ in these cases! use discretion." We're using plenty of both styles throughout the code (all of the stuff ported directly from OCaml is using the postfix style fwiw (e.g. `string list`). Considering we're already following that "use discretion," not worth a Dark-only standardization I think.

I think this is OK to close without action; it just threw me for a loop the other day.

**Comment by pbiggar** [comment]
I was in the process of converting them all to this format `List<string>`. I wasn't doing it for `byte array` because `Array<byte>` didn't work, but I think `array<byte>` does.

**Comment by StachuDotNet** [comment]
Cool, sounds good!
