### ISSUE TITLE
Prevent deploy from killing old CronChecker deployment until the new one is in place

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#3671]
A deploy failed earlier today.

The major issue that happened is that CronChecker went down and crons had a minor outage for about 15 minutes. This is because CronChecker's deployment policy is ReCreate, because we can't have two things running the cronchecker at once. To solve this, we should allow the old and the new cronchecker to run at once, with some sort of lock/semaphore in the DB, pub sub, cloud storage, etc.

**Comment by StachuDotNet** [comment]
Is still of a concern? if so, can we please re-title this?

**Comment by pbiggar** [comment]
This will be solved when CronChecker is removed. (if somehow we decide not to remove CronChecker, this issue is still important)

**Comment by StachuDotNet** [comment]
merged into #5261
