### ISSUE TITLE
`serve-latest.test` intermittently failing

### ISSUE THREAD

**Issue by StachuDotNet** [darklang/dark#3674]
https://app.circleci.com/pipelines/github/darklang/dark/2664/workflows/f84b0893-428e-41c0-bd1d-1058d252f5ab/jobs/28300

from @pbiggar:
> my guess is that the staticassets tests are all run in serial and take a long time, so it’s highly likely that at the point the serve-latest test runs, something is clearing the DB in parallel

**Comment by StachuDotNet** [comment]
This issue stems from both `testfiles/staticassets.tests` and `httptestfiles/serve-latest.test` using a canvas of name `test-static-assets-deploy`. The canvas name is consistent intentionally, to match the static assets that have been uploaded to our CDN.

Both relevant test-runners (`LibExecution.Tests.fs` and `HttpClient.Tests.fs`, respectively) clear the DB by owner+canvas name, and the issue occurs when one of the runners clears the DB before the other runner has had a chance to run its relevant test(s).

So far I've only a few ideas of how to tackle this:
1. adjust `Tests.fs` to run `Tests.HttpClient.tests` and `Tests.LibExecution.tests` in sequence
2. upload the static assets twice, so we don't have to rely on using the same canvas name across tests
3. add some kind of 'locking' mechanism (shared state) between the two test runners, that will "only close if the other test has already run." I'm not a big fan of this.

Option 2 requires some manual work around uploading the assets, but may be worthwhile. Thoughts, @pbiggar?

Otherwise, I believe option 1 could be satisfied by editing `Tests.fs` to:
```
let tests =
  [ Tests.Account.tests
    ...
    testSequenced (
      testList
        "SharedStaticGroup"
        [ Tests.HttpClient.tests; Tests.LibExecution.tests.Force() ]
    )
    ...
    Tests.UserDB.tests ]
```

If we were to pursue that option, we need to ensure the name of that test list (here, `SharedStaticGroup`) is clear, but without being caught by `--filter-test-case` and `--filter-test-list` usages. (i.e. we shouldn't accidentally run both lists when we intend to only run one, as would be the case if we named it `HttpClient and LibExecution` and then ran with `--filter-test-list 'httpclient'`, as that'd be annoying)

**Comment by pbiggar** [comment]
I can do 2, for sure. If you give me the name of the bucket to canvas and the hash that is created by baseUrl to that bucket, I'll upload them ASAP.

3 would help you test out whether this will work, but it's so easy to do that doing 2 quickly is probably better.

**Comment by StachuDotNet** [comment]
`test-static-assets-deploy` => `gd57quywk2db6zncs3h2hxgfdtc` I believe

https://github.com/darklang/dark/blob/c8a0905b9656492b81089cc1a35d39ac6321e5aa/fsharp-backend/tests/testfiles/staticassets.tests#L59

**Comment by StachuDotNet** [comment]
https://github.com/darklang/dark/blob/c8a0905b9656492b81089cc1a35d39ac6321e5aa/fsharp-backend/tests/testfiles/staticassets.tests#L101-L102

`test-static-assets-deploy` -> `u0n38z-mv-t0tkvnwiqyvankw6w`, I believe.

**Comment by StachuDotNet** [comment]
`test-httpclient-static-assets-deploy` -> `q80gm_txk39kbiy4l35hejeekxc`, if that name is fine by you.

**Comment by pbiggar** [comment]
Uploaded. I observed when building the tests the first time that fetching just one of them was flaky. It went away and I concluded it was due to eventual consistency. FYI in case you experience the same.

**Comment by pbiggar** [comment]
<img width="551" alt="image" src="https://user-images.githubusercontent.com/181762/163013489-689b8c7a-e9c2-4544-b35c-bf9b80d9fcdc.png">

**Comment by StachuDotNet** [comment]
Sounds good, thanks.

My expectation is that `./scripts/run-fsharp-tests --filter-test-case 'serve-latest'` should eventually pass locally, after having changed the canvas name to `test-httpclient-static-assets-deploy`, given that deployment. Is that true? See #3681. If so, I'll check back in an hour and run the test again.

When uploading, did you need to mind the deploy hash of `abcdef1234` at all?

**Comment by pbiggar** [comment]
Sorry, that's my mistake. Here's what I should be copying

<img width="591" alt="image" src="https://user-images.githubusercontent.com/181762/163015999-46e45eec-4d08-42fb-a917-002e88d2808d.png">

I'll fix now.

**Comment by pbiggar** [comment]
<img width="567" alt="image" src="https://user-images.githubusercontent.com/181762/163016182-50720e10-dad8-47ee-bf2c-df75c708bc71.png">

**Comment by StachuDotNet** [comment]
Aha, cool! np. test still failing locally, but will check again in a bit, hoping for eventual consistency.

**Comment by pbiggar** [comment]
fwiw, even with the eventual consistency issue, it only failed occasionally, and even then only on one of them. If you're seeing it fail every time, there's likely a real issue.

**Comment by StachuDotNet** [comment]
#3681 is failing consistently for me locally. Curiously, it [passed](https://app.circleci.com/pipelines/github/darklang/dark/2677/workflows/f9845f1e-4732-407a-85dd-14181e69e081/jobs/28475) in CI.

Not sure why.

**Comment by pbiggar** [comment]
In CI, it seems like it works but just the expected last-modified date is wrong.

**Comment by StachuDotNet** [comment]
Odd that it works as-is in CI. Locally the // comments were being interpreted as part of the handler, and thus failing the test. When I removed that (just a bit ago), I found the last-modified date difference and that resolves it.

**Comment by StachuDotNet** [comment]
This is an issue still

**Comment by pbiggar** [comment]
> This is an issue still https://app.circleci.com/pipelines/github/darklang/dark/2709/workflows/bdced322-d64f-484b-9172-7bc7762f95a1/jobs/28855

It looks like this canvas is being cleared. I'm not sure how that could happen?

**Comment by StachuDotNet** [comment]
I forget if we intentionally fixed this, but I haven't seen this in ages; closing.
