### ISSUE TITLE
Improve error messaging when creating invalid canvas name

### ISSUE THREAD

**Issue by StachuDotNet** [darklang/dark#3698]
I tried to create a canvas of name `stachudotnet-signAndVerify`, and it's 500-ing, assumedly on the capital letters.
![image](https://user-images.githubusercontent.com/906686/163480435-69059117-edc9-4966-81bf-c7256c384baf.png)

Improving the error messaging would be good

**Comment by pbiggar** [comment]
This now gives a simple "not found" which is good
