### ISSUE TITLE
getting 500 on big user, unclear why

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#3710]
Debugging this issue now.

**Comment by pbiggar** [comment]
So far I've found two issues:

## Issue 1:
calling a function like this:
```
value
|> myFunction dErrorValue dErrorValue
```

in OCaml returns `dErrorValue` but in F# returns a `DIncomplete`.

No obvious cause so far.

## Issue 2:

F# `DB::keys` is returning `[]` while OCaml `DB::keys` is returning `["some value"]` (OCaml seems to be correct here).

The DB contents are set in the background every minute, by getting the response, adding a new value, then deleting the old values one-by-one (note this is using OCaml code in the queueworker).

I don't have any obvious leads.

**Comment by pbiggar** [comment]
Not having any success reproducing this locally. My plan is to deploy an instrumented version of the runtime to make just this request and see what I can learn.

**Comment by pbiggar** [comment]
OK, found issue 1. The user named their function `myfunction_v1`, and we parsed that as a StdLib and not as a UserFunction.

1) needs tests
2) probably if they don't have a module we should check the stdlib before we decide it's a stdlib function
3) these are probably saved in the DB like this so some sort of migration or fix is required

**Comment by StachuDotNet** [comment]
relates to #3641, it seems

**Comment by pbiggar** [comment]
Fixed and followup done.
