### ISSUE TITLE
Handle FSLATER comments

### ISSUE THREAD

**Issue by StachuDotNet** [darklang/dark#3717]
Should [these](https://github.com/darklang/dark/blob/caa6dc18726590dda51c95ce751fb94806431514/fsharp-backend/src/ApiServer/ApiServer.fs#L111-L112) be turned into `CLEANUP`, or something else?
Maybe the comments can be removed in favor of Issues? (which may already exist)

**Comment by pbiggar** [comment]
Yeah, let's do that.
