### ISSUE TITLE
Incompletes in functions are confusing

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#3726]
In this function, it's not clear that `name` is `incomplete`, or why. What's happening here is that there is no default trace for the function, and so `name` gets an `incomplete` value.

![image](https://user-images.githubusercontent.com/181762/164539838-a56a56b9-87e5-4efa-883a-1b85bf82d79e.png)

Some options:
- allow people understand what's going on
  - better explanation of incomplete
  - docs, tooltips, etc
- allow people to solve the problem more easily 
  - a button to create a trace or edit a trace or something
  - a button to call the 
- prevent the problem from happening
  - change trace behaviour to have sample data by default
  - automatically call the function at it's call site (if it exists)

Would be worth going through the workflow of how users create functions (both from their callers aka bottomup, and from scratch aka top-down) and ensuring both cases are adequately handled.

**Comment by eldemcan** [comment]
just to leave more context here, I started my program with small function. Current design assumes users  design functions from  top-down.

**Comment by pbiggar** [comment]
Closing as it doesn't apply to darklang-next
