### ISSUE TITLE
Regression in error page for badly-formed ApiServer  URL

### ISSUE THREAD

**Issue by StachuDotNet** [darklang/dark#3728]
Here's a small difference between F# ApiServer and the OCaml server:

The OCaml server returns a friendly error page when directing to this bad URL:
http://darklang.localhost:8000/a/dark-brand-new&use-blazor=true (note the &, not an ? - I did this by accident locally)
![image](https://user-images.githubusercontent.com/906686/164575737-fd7f9424-2473-4c9a-867f-afa7e20e9333.png)

The F# ApiServer returns a simple 500 - less friendly.

(I couldn't think of a good appropriate title - please feel free to re-title and remove this comment line.)

This particular usage is probably rare/uninteresting, but it's worth some short consideration if there are similar URLs that would more often be attempted.

**Comment by pbiggar** [comment]
I actually keep doing this, wasted ten minutes yesterday figuring out the "bug"

**Comment by pbiggar** [comment]
Closing as it doesn't apply to darklang-next
