### ISSUE TITLE
User DBs can be in an invalid state

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#3762]
Users can make requests to DBs that don't exist, due to the ASTs being in an invalid state. This causes errors like "The given key was not present in the dictionary.", such as in https://rollbar.com/darkops/darklang/items/3196/.

To resolve this, we want to ensure that canvases cannot be in an invalid state:
- [ ] detect and resolve any to DB names in the AST that don't exist
- [ ] store DB names in the AST by ID, not by name (this ensures that we can rename them without changing all uses, which is more likely to partially fail)
- [ ] prevent deleting DBs server side if they have data in them (this might happen already)

**Comment by StachuDotNet** [comment]
seems largely irrelevant to dark-next
