### ISSUE TITLE
Tell users when errors happen

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#3773]
If a handler get a 400, or > 500, or DError, DIncomplete, DErrorRail, those are errors. Users should be told about errors, like an exception tracker.

- let the user see these errors in their canvas
- notify the user about the errors, perhaps daily, with links to the errors
- ensure we have a full trace
- ensure the trace stays "active" while the user moves between functions
- ensure the user can click on a link and see what happened

The goal here is to give a user (and to an extent us) confidence that their canvas is working.

**Comment by StachuDotNet** [comment]
folded into #5261
