### ISSUE TITLE
Document how to log/view Telemetry information locally

### ISSUE THREAD

**Issue by StachuDotNet** [darklang/dark#3778]
A while back I set myself up a personal Rollbar for some work, before getting access to the main Dark one.
A solution to work _without_ requiring someone to sign up for an account would be best.

I still haven't touched Honeycomb much, so not sure if that's relevant as well?

Are there other things like this to be split out?

**Comment by pbiggar** [comment]
Telemetry can be printed to console if we set `DARK_CONFIG_TELEMETRY_EXPORTER=console`, which is the default. So there should be telemetry info locally already in `rundir/logs/fsharp-bwdserver.log` (or the various other fsharp logs).

That said, it's not super usable - in fact, I tend to use honeycomb for my local telemetry as well, when I need it (usually to profile something).

**Comment by pbiggar** [comment]
A thing that occurred to me is that you (and anyone) could just set up a free honeycomb account and add the credentials to config/dev.

**Comment by StachuDotNet** [comment]
Yeah, that's an option. Maybe we go with that recommendation for now. Imo, ideally a dev doesn't have to create any accounts to work on the repo, but I can extract that to a separate ticket.

**Comment by pbiggar** [comment]
Well, I guess they don't actually have to, they can just ignore telemetry.
