### ISSUE TITLE
Add db tracing back to CronChecker and QueueWorker

### ISSUE THREAD

**Issue by StachuDotNet** [darklang/dark#3780]

**Comment by StachuDotNet** [comment]
@pbiggar can you please expand upon this?

**Comment by pbiggar** [comment]
See https://github.com/npgsql/npgsql/issues/4243.

We have an event budget in honeycomb, about 1.5B events per month. Every DB call is 2 events, and queueworkers and the CronChecker essentially poll the DB in a hot loop.

In the past, we handled this by only logging postgres events above 1ms. I couldn't figure out how to do this, so I disabled Npgsql tracing in the workers. However, some suggestions were made [starting here](https://github.com/npgsql/npgsql/issues/4243#issuecomment-1002073938) that might work.

**Comment by StachuDotNet** [comment]
Some context in Dark:
various `Telemetry` fns (e.g. `Console.loadTelemetry` and `AspNet.addTelemetryToServices`) include a `traceDBQueries` parameter.
In most cases (QueueWorker, ExecHost, Tests, ApiServer, BwdServer), we set this to `TraceDBQueries` but in the case of `CronChecker`, we pass `DontTraceDBQueries`.

Eventually these arguments are eventually used in `Telemetry.addTelemetry`, where we decide whether to call our `builder`'s (`TracerProviderBuilder`) `builder.AddNpgsql()`

- [ ] research the `AddNpgsql()` here - maybe we can fork it, or provide some configuration

**Comment by StachuDotNet** [comment]
FYI: The title of this issue mentions both QueueWorker and CronChecker, but QueueWorker seems to have this enabled.

**Comment by pbiggar** [comment]
> FYI: The title of this issue mentions both QueueWorker and CronChecker, but QueueWorker seems to have this enabled.

Oh yeah, I changed it cause it no longer polls the DB like it used to (and like cronchecker does)

**Comment by pbiggar** [comment]
> research the `AddNpgsql()` here - maybe we can fork it, or provide some configuration

Highlighting [this link](https://github.com/npgsql/npgsql/issues/4243#issuecomment-1002073938) as a starting point

**Comment by StachuDotNet** [comment]
folding into #5246 for now
