### ISSUE TITLE
Warm Up BwdServer when it starts

### ISSUE THREAD

**Issue by StachuDotNet** [darklang/dark#3782]

**Comment by StachuDotNet** [comment]
What are reasonable "warm-up" actions for each of ApiServer and BwdServer?

Is it at all relevant to "warm up" wasm build in some way? (e.g. executing 2+2) I don't think so, but the thought came up.

**Comment by pbiggar** [comment]
I think we'd have a canvas called like `ops-performance` and we'd do something on that canvas from each server when it starts up. Maybe 3-10 calls of a handler on BwdServer, and a similar number of API calls on ApiServer.

Warming up Wasm is interesting. We could have a simple program (maybe fizzbuzz) that runs if there isn't anything else running to warm it up. Though probably lower priority for now.

**Comment by StachuDotNet** [comment]
Folded into #5246
