### ISSUE TITLE
Remove ocamlCompatible json from the API

### ISSUE THREAD

**Issue by StachuDotNet** [darklang/dark#3783]

**Comment by pbiggar** [comment]
So for this, we'd need to add a client side JSON decoder for the new versions. Then we'd need to add a new API version (so `/api/v1/get_traces` or whatever), as old clients tend to live on for a while. So the new client would call the new version, and then in a few weeks we can remove the old version, when the old clients are gone.

**Comment by pbiggar** [comment]
🥳
