### ISSUE TITLE
Pasting "lines" fails

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#3785]
Users will try to highlight a line, and then paste it below. Typically this means they'll be trying to paste into something like

```
let x = y
let ___ = ___
x
```

There are various points where it should work to paste, such as:
- after `y`
- before `let`
- after `let`
- in the left `___`
- before the `x`

An example of something a user has had a problem pasting is: `let ONE_DAY = 60 * 60 * 24`

**Comment by xumx** [comment]
The most common expectation when pasting is to "insert in-between two lines". Which is also equivalent to paste before let AND add a new linebreak.

This is currently not possible. 


---

another more general solution is to allow empty lines in Dark's Editor. it has the additional readability benefits if the developer wishes to add spacing between code sections.

**Comment by pbiggar** [comment]
Not applicable to darklang-next.
