### ISSUE TITLE
Review remaining F# list-concatenations

### ISSUE THREAD

**Issue by StachuDotNet** [darklang/dark#3790]
We've seen 2 problems so far with `@` list concatonations being backwards in the new F# backend. We should review the remaining ones for any issues.

Here's a dump of all `@` within `fsharp-backend/src`, after removing irrelevant ones (e.g. RegEx and @columnName sql refs)

- [x] fsharp-backend/src/ApiServer/Login.fs:
  - [x] 116:      ` let qs = Http.queryString (redirect @ error)`

- [x] fsharp-backend/src/LibExecution/DvalReprInternal.fs:
  - [x] 554:        ` @ rows @ [ UTF8.toBytes nl; UTF8.toBytes "}" ]`
- [x] fsharp-backend/src/LibExecutionStdLib/LibList.fs:
  - [x] 235:        ` | _, [ DList l; i ] -> Ply(DList(l @ [ i ]))`
  - [x] 529:               ` | t -> [ h ] @ [ i ] @ join t)`
- [x] fsharp-backend/src/LibExecution/RuntimeTypes.fs:
  - [x]  952:    ` let metadata = metadata @ Exception.toMetadata exn`
  - [x] 1030:  ` existing @ newFns`
- [x] fsharp-backend/src/ApiServer/Api/APIOps.fs:
  - [x] 148:    ` let allTLIDs = opTLIDs @ dbTLIDs`
  - [x] 187:         `(oldOps @ newOps)`

- [x] fsharp-backend/src/LibExecution/Interpreter.fs:
  - [x] 688:                        ` let context = (context @ [ "dval", dv ])`
- [x] fsharp-backend/src/LibBackend/Cron.fs:
  - [x] 149:        ` @ ([ delayLog; intervalLog; delayRatioLog ] |> List.filterMap (fun a -> a))`
- [x] fsharp-backend/src/LibBackend/UserDB.fs:
  - [x] 303:        ` @ [ "tlid", Sql.tlid db.tlid`
  - [x] 507:        ` db.cols @ [ { name = None; typ = None; nameID = colid; typeID = typeid } ] }`
  - [x] 554:` //         {migration with cols = migration.cols @ [(Blank nameid, Blank typeid)]}`
  - [x] 604:` //         {db with old_migrations = db.old_migrations @ [mutated_migration]}`

- [x] fsharp-backend/src/LibExecution/OCamlTypes.fs:
  - [x]  621:      ` | ORT.Handler h -> (hs @ [ ocamlHandler2PT tl.pos h ], dbs)`
  - [x]  622:      ` | ORT.DB db -> (hs, dbs @ [ ocamlDB2PT tl.pos db ]))`
  - [x]  836:      ` ORT.EPipe(pipeID, pipeStart @ [ fnCall ])`
  - [x] 1018:        ` tls @ [ ocamlTL ], ufns, uts`
  - [x] 1027:        ` tls @ [ ocamlTL ], ufns, uts`
- [x] fsharp-backend/src/LibBackend/Undo.fs:
  - [x] 68:      ` newBefore @ newAfter`

- [x] fsharp-backend/src/ApiServer/Api/APITraces.fs:
  - [x] 130:      ` return { traces = hTraces @ ufTraces }`

- [x] fsharp-backend/src/HttpMiddleware/MiddlewareV0.fs:
  - [x] 75:        ` headers = response.headers @ [ "Access-Control-Allow-Origin", origin ] })`
- [ ] fsharp-backend/src/BackendOnlyStdLib/HttpClient.fs:
  - [ ] 258:            ` headers = [ statusHeader, "" ] @ headers`
  - [ ] 347:                    ` headers = result.headers @ redirectResult.headers })`

- [ ] fsharp-backend/src/BackendOnlyStdLib/HttpQueryEncoding.fs:
  - [ ] 127:   `(queryParams @ parseQueryString_ existingQuery) |> queryToEncodedString_`

- [ ] fsharp-backend/src/BackendOnlyStdLib/LegacyBaseHttpClient.fs:
  - [ ] 356:          ` convertHeaders response.Headers @ convertHeaders response.Content.Headers`
  - [ ] 368:          ` { body = respBody; code = code; headers = [ statusHeader, "" ] @ headers }`
  - [ ] 489:                    ` headers = result.headers @ redirectResult.headers })`

- [ ] fsharp-backend/src/HttpMiddleware/ResponseV0.fs:
  - [ ] 95:      ` headers = headers @ inferredContentTypeHeader`

- [ ] fsharp-backend/src/LibBackend/Analytics.fs:
  - [ ] 56:      ` let payload = Map(payload @ Map.toList heapioMetadata)`

- [ ] fsharp-backend/src/LibBackend/SqlCompiler.fs:
  - [ ] 214:        ` let argSql = fnArgs @ argSqls |> String.concat ", "`
  - [ ] 217:        ` let argSql = argSqls @ fnArgs |> String.concat ", "`

- [ ] fsharp-backend/src/LibBackend/Traces.fs:
  - [ ] 39:  ` | PT.Handler.UnknownHandler _ -> sampleRequestInputVars @ sampleEventInputVars`
  - [ ] 52:  ` sampleModuleInputVars h @ sampleRouteInputVars h`
  - [ ] 86:    ` withR @ bound`

- [ ] fsharp-backend/src/LibRealExecution/RealExecution.fs:
  - [ ] 103:      ` let metadata = extraMetadata state @ metadata`
  - [ ] 107:      ` let metadata = extraMetadata state @ metadata`

- [ ] fsharp-backend/src/LibService/Rollbar.fs:
  - [ ] 345:    ` let metadata = Exception.toMetadata e @ metadata`
  - [ ] 437:              ` let metadata = metadata @ Exception.toMetadata e`

- [ ] fsharp-backend/src/LibService/Telemetry.fs:
  - [ ] 157:    ` @ Exception.toMetadata e @ metadata`

- [ ] fsharp-backend/src/Prelude/Prelude.fs:
  - [ ]   97:      ` | :? PageableException as e -> [ "is_pageable", true :> obj ] @ e.metadata`
  - [ ]  103:    ` thisMetadata @ innerMetadata`
  - [x]  967:              ` read (index + 1) (acc @ [ value ])`
  - [x] 1034:              ` read (index + 1) (acc @ [ value ])`
  - [ ] 1841:    ` fromAspNetHeaders response.Headers @ fromAspNetHeaders response.Content.Headers`

**Comment by StachuDotNet** [comment]
My plan from here is to turn the above into a checkbox list to review, and consider each one by one in spurts.

**Comment by pbiggar** [comment]
Off the top of my head:
 
> ```
> 48 results - 23 files
> 
> fsharp-backend/src/ApiServer/Login.fs:
>   116:       let qs = Http.queryString (redirect @ error)

Don't know

> 
> fsharp-backend/src/ApiServer/Api/APIOps.fs:
>   148:     let allTLIDs = opTLIDs @ dbTLIDs
>   187:         (oldOps @ newOps)

Feels fine.

> fsharp-backend/src/ApiServer/Api/APITraces.fs:
>   130:       return { traces = hTraces @ ufTraces }

Fine

> fsharp-backend/src/BackendOnlyStdLib/HttpClient.fs:
>   258:             headers = [ statusHeader, "" ] @ headers
>   347:                     headers = result.headers @ redirectResult.headers })

Would look at

> fsharp-backend/src/BackendOnlyStdLib/HttpQueryEncoding.fs:
>   127:   (queryParams @ parseQueryString_ existingQuery) |> queryToEncodedString_

Would look at

> fsharp-backend/src/BackendOnlyStdLib/LegacyBaseHttpClient.fs:
>   356:           convertHeaders response.Headers @ convertHeaders response.Content.Headers
>   368:           { body = respBody; code = code; headers = [ statusHeader, "" ] @ headers }
>   489:                     headers = result.headers @ redirectResult.headers })

Would look at

> 
> fsharp-backend/src/HttpMiddleware/MiddlewareV0.fs:
>   75:         headers = response.headers @ [ "Access-Control-Allow-Origin", origin ] })
> 
Would look at

> fsharp-backend/src/HttpMiddleware/ResponseV0.fs:
>   95:       headers = headers @ inferredContentTypeHeader
Would look at

> 
> fsharp-backend/src/LibBackend/Analytics.fs:
>   56:       let payload = Map(payload @ Map.toList heapioMetadata)

Fine.
> 
> fsharp-backend/src/LibBackend/Cron.fs:
>   149:         @ ([ delayLog; intervalLog; delayRatioLog ] |> List.filterMap (fun a -> a))
> 
Fine


> fsharp-backend/src/LibBackend/SqlCompiler.fs:
>   214:         let argSql = fnArgs @ argSqls |> String.concat ", "
>   217:         let argSql = argSqls @ fnArgs |> String.concat ", "
> 
Would look at

> fsharp-backend/src/LibBackend/Traces.fs:
>   39:   | PT.Handler.UnknownHandler _ -> sampleRequestInputVars @ sampleEventInputVars
>   52:   sampleModuleInputVars h @ sampleRouteInputVars h
>   86:     withR @ bound
Would look at
 
> fsharp-backend/src/LibBackend/Undo.fs:
>   68:       newBefore @ newAfter
Would look at
 
> fsharp-backend/src/LibBackend/UserDB.fs:
>   303:         @ [ "tlid", Sql.tlid db.tlid
>   507:         db.cols @ [ { name = None; typ = None; nameID = colid; typeID = typeid } ] }
>   554: //         {migration with cols = migration.cols @ [(Blank nameid, Blank typeid)]}
>   604: //         {db with old_migrations = db.old_migrations @ [mutated_migration]}
Would look at
 
> fsharp-backend/src/LibExecution/DvalReprInternal.fs:
>   554:         @ rows @ [ UTF8.toBytes nl; UTF8.toBytes "}" ]
Fine 
> fsharp-backend/src/LibExecution/Interpreter.fs:
>   688:                         let context = (context @ [ "dval", dv ])
Find
> fsharp-backend/src/LibExecution/OCamlTypes.fs:
>    621:       | ORT.Handler h -> (hs @ [ ocamlHandler2PT tl.pos h ], dbs)
>    622:       | ORT.DB db -> (hs, dbs @ [ ocamlDB2PT tl.pos db ]))
>    836:       ORT.EPipe(pipeID, pipeStart @ [ fnCall ])
>   1018:         tls @ [ ocamlTL ], ufns, uts
>   1027:         tls @ [ ocamlTL ], ufns, uts

Feels ok.

> fsharp-backend/src/LibExecution/RuntimeTypes.fs:
>    952:     let metadata = metadata @ Exception.toMetadata exn
>   1030:   existing @ newFns

Don't know

> fsharp-backend/src/LibExecutionStdLib/LibList.fs:
>   235:         | _, [ DList l; i ] -> Ply(DList(l @ [ i ]))
>   529:                | t -> [ h ] @ [ i ] @ join t)

Dunno but there's probably tests
 
> fsharp-backend/src/LibRealExecution/RealExecution.fs:
>   103:       let metadata = extraMetadata state @ metadata
>   107:       let metadata = extraMetadata state @ metadata

Probably fine

> fsharp-backend/src/LibService/Rollbar.fs:
>   345:     let metadata = Exception.toMetadata e @ metadata
>   437:               let metadata = metadata @ Exception.toMetadata e
Probably fine
> 
> fsharp-backend/src/LibService/Telemetry.fs:
>   157:     @ Exception.toMetadata e @ metadata
Probably fine
> 
> fsharp-backend/src/Prelude/Prelude.fs:
>     97:       | :? PageableException as e -> [ "is_pageable", true :> obj ] @ e.metadata
>    103:     thisMetadata @ innerMetadata
>    967:               read (index + 1) (acc @ [ value ])
>   1034:               read (index + 1) (acc @ [ value ])
>   1841:     fromAspNetHeaders response.Headers @ fromAspNetHeaders response.Content.Headers
> ```
Probably fine

**Comment by StachuDotNet** [comment]
Edited the OP to be a bunch of checkboxes. Marking them off now, reviewing your quick-review and going through them myself otherwise.
