### ISSUE TITLE
Can't run integration tests outside of devcontainer

### ISSUE THREAD

**Issue by StachuDotNet** [darklang/dark#3810]
I've been recently unable to run integration tests outside of the devcontainer.
Usually this isn't an issue, but `--debug` doesn't work from within the devcontainer.

The error that I'm getting is `./integration-tests/run.sh: line 18: DARK_CONFIG_APISERVER_HOST: unbound variable`
Previously, I don't believe I've had to do anything special for this to be available outside of the container - any ideas of how to resolve?

**Comment by StachuDotNet** [comment]
`DARK_CONFIG_APISERVER_HOST=darklang.localhost:9000 DARK_CONFIG_BWDSERVER_HOST=builtwithdark.localhost:11001 ./integration-tests/run.sh`

yields this endlessly:
```
curl: (22) The requested URL returned error: 502 Bad Gateway
waiting for analysis.js at http://static.darklang.localhost:9000/analysis.js
```

**Comment by pbiggar** [comment]
I can't find where we set the DNS for darklang.localhost, but we should add static.darklang.localhost to it

**Comment by pbiggar** [comment]
> I can't find where we set the DNS for darklang.localhost, but we should add static.darklang.localhost to it

Actually, I don't think that's it. When I do: `ping x.x.localhost` it knows it's 127.0.0.1, and when I go `curl -v http://static.darklang.localhost` I get a 404 from the webserver.

I'm thinking perhaps analysis.js isn't available? That's the ocaml version of the analysis - perhaps it wasn't built properly? Can you reach it from inside the container? can you reach it in your browser?

**Comment by StachuDotNet** [comment]
I'm able to run tests outside of the container if I remove [this line](https://github.com/darklang/dark/blob/1308ceb566b36b92518b5422eded83ddb03bae73/integration-tests/run.sh#L90) from `integration-tests/run.sh`, which is `./scripts/run-fsharp-server "${PUBLISHED}"`.

I'm not yet sure why.

**Comment by pbiggar** [comment]
I think what might be happening is that the servers started up by `run-fsharp-server` die after the script ends if they're run outside the container. So the `run-fsharp-server` script would first kill the running servers, then start up its own servers, then those would die after that script ends.

So by making the change, run.sh no longer calls `run-fsharp-server` and so no longer kills the servers.

**Comment by pbiggar** [comment]
> How should we address those hacks, so someone can more easily run the tests outside of the container (as our docs suggest)?

One option here is to stop suggesting that. I'm fully using the devcontainer now, personally.

 
> 1. need to set `DARK_CONFIG_APISERVER_HOST` and `DARK_CONFIG_BWDSERVER_HOST`
>    Is there a way for the script to fetch the variables as they're set within the container? Maybe via `docker exec`? (see https://stackoverflow.com/a/71664791)

We could use the values from config/dev (maybe fetch them with grep or hard code them?)

> 2. need to comment out the `run-fsharp-server` line, otherwise the server won't be available
>    I'm curious how this was working before and isn't now. No ideas here yet. I don't fully understand why it's necesarry, actually - the [note](https://github.com/darklang/dark/blob/895399f19c1a5ecc71cd96086a6852572c6899c8/integration-tests/run.sh#L88-L90) says:
> 
> > We need to restart the server after adding new packages. Integration tests test against the dev environment, not the test one.
> 
> I believe this is referring to the npm packages (really, just the playwright package). Shouldn't it be safe to assume that's already been installed per the readme?

I'm not super sure what that means. Looks like I wrote it recently though 😬

We could run `./scripts/run-fsharp-server` only if `IN_DEV_CONTAINER` is set?

**Comment by StachuDotNet** [comment]
"I'm fully using the devcontainer now, personally."
are you able to `--debug` in-container? If so, that sounds great.

**Comment by pbiggar** [comment]
> "I'm fully using the devcontainer now, personally."
> are you able to `--debug` in-container? If so, that sounds great.

No. I run it in the container then watch the video. But I haven't actually done integration tests much recently.

**Comment by StachuDotNet** [comment]
```
BASE_URL="http://${cat config/dev | grep DARK_CONFIG_TEST_APISERVER_BACKEND_PORT= | cut -d '=' -f2}"
BWD_BASE_URL=".${cat config/dev | grep DARK_CONFIG_BWDSERVER_HOST= | cut -d '=' -f2}"
```

These get the job done, but need to fit into the full script

**Comment by pbiggar** [comment]
Shall we deprioritize this til next time?

**Comment by StachuDotNet** [comment]
Yeah, it's not pressing

**Comment by StachuDotNet** [comment]
I've been finding that the update to the run.sh [here](https://github.com/darklang/dark/pull/4167/files) is really sufficient
