### ISSUE TITLE
`use-blazor=true` flag currently broken in production

### ISSUE THREAD

**Issue by StachuDotNet** [darklang/dark#3811]
I just noticed that ?use-blazor=true in the Editor currently is broken - many console errors around invalid integrity attributes.

AFAIK this was working Friday afternoon - not yet sure what may be wrong here.

**Comment by StachuDotNet** [comment]
![image](https://user-images.githubusercontent.com/906686/168647234-e1dc8d30-c7cc-4cf9-8271-b61dbc22afe6.png)

**Comment by StachuDotNet** [comment]
I haven't encountered this error before @pbiggar if you have any advice, I can look into this.

**Comment by StachuDotNet** [comment]
It seems some of the blazor assets (dlls) are 200-ing OK when being loaded, but others are 404-ing.

**Comment by pbiggar** [comment]
Relevent, don't know if this is it https://stackoverflow.com/a/71171026/104021

**Comment by pbiggar** [comment]
So what I think this is all referring to is the hashes loaded via blazor.boot.json

<img width="1010" alt="image" src="https://user-images.githubusercontent.com/181762/168648158-6c0ca220-cab8-4931-86b6-46b49be3423d.png">

**Comment by pbiggar** [comment]
I don't know why some of them would be bad, but perhaps as the Stackoverflow link suggests, we are perhaps loading them from cache incorrectly?

**Comment by pbiggar** [comment]
> It seems some of the blazor assets (dlls) are 200-ing OK when being loaded, but others are 404-ing.

Hmm, I was thinking it wasn't really 404-ing, just that was how the SRI check failure appears in the chrome UI. But it could be the other way: they're 404-ing and we're getting an SRI *because* they're 404-ing.

**Comment by StachuDotNet** [comment]
What cache are you referring to?

**Comment by pbiggar** [comment]
Stackoverflow said "Manually deleted all bin and obj folders in the solution and then redeployed. After this everything worked."

**Comment by pbiggar** [comment]
Cleared the CI cache in this build: https://app.circleci.com/pipelines/github/darklang/dark/2949/workflows/fdf26f5c-e511-4c96-865f-1cd0f76fcdc1

**Comment by StachuDotNet** [comment]
Unfortunately that didn't seem to help

**Comment by StachuDotNet** [comment]
Resolved recently - this was due to bad CDN uploads in CI, because of the more+larger Blazor static assets resulting in more big concurrent calls to gsutil cp
