### ISSUE TITLE
Rollbar: Invalid canvas name '1a11', can only contain roman letters, digits, and '-' or '_'

### ISSUE THREAD

**Issue by StachuDotNet** [darklang/dark#3814]
(I changed the actual canvas name for privacy, but this matches the pattern)

https://rollbar.com/darkops/darklang/items/3233/

Theory: an existing canvas that was allowed in OCaml doesn't match the pattern that the F# backend demands.
If so, we should update the RegEx?
- [x] write a test against that theory (create it in OCaml, load via F#)

**Comment by pbiggar** [comment]
There's hundreds of these with different variations, I'm pretty sure its spam. I think the thing here is that there's always going to be people probing random subdomains, canvases, etc, so we don't want to have this be reported as an exception.

**Comment by StachuDotNet** [comment]
Relates to https://github.com/darklang/dark/issues/3698

**Comment by pbiggar** [comment]
Also similar in concept: https://github.com/darklang/dark/projects/1#card-80611141

**Comment by pbiggar** [comment]
Think this is done, we'll need to reopen if they happen again.

I unmuted https://rollbar.com/darkops/darklang/items/3244/ and resolved it, so we should be alerted quickly. None in the last 20 mins though.
