### ISSUE TITLE
Rollbar: "Deadline Exceeded"

### ISSUE THREAD

**Issue by StachuDotNet** [darklang/dark#3815]
https://rollbar.com/darkops/darklang/items/3236/

https://github.com/darklang/dark/blob/4a9fdbede527bc00d08b08f6ece456cf135d7733/fsharp-backend/src/LibBackend/EventQueueV2.fs#L275

LibBackend/EventQueueV2.fs line 275 col 5

**Comment by pbiggar** [comment]
Handling in #3817

**Comment by pbiggar** [comment]
I think we got a DeadlineExceeded exception a few days ago, so I might look at that before closing.

**Comment by StachuDotNet** [comment]
folded into #5261
