### ISSUE TITLE
Rollbar: "Deadline Exceeded" in EventQueueV2 `dequeue`

### ISSUE THREAD

**Issue by StachuDotNet** [darklang/dark#3816]
https://rollbar.com/darkops/darklang/items/3236/

https://github.com/darklang/dark/blob/4a9fdbede527bc00d08b08f6ece456cf135d7733/fsharp-backend/src/LibBackend/EventQueueV2.fs#L275

**Comment by pbiggar** [comment]
Duplicate of #3815
