### ISSUE TITLE
UI Customizability

### ISSUE THREAD

**Issue by StachuDotNet** [darklang/dark#3825]
Not a current priority, but something to think about over time:
- color themes (e.g. "light mode," or more fine-grained customization)
- font choice
- layout

**Comment by pbiggar** [comment]
Light mode theme and tab size options in this branch: https://github.com/darklang/dark/compare/main...syd/user-settings

Easy to add font-choice to it. Also allow the user to choose if they like ligatures (our default is Fira-code which uses ligatures, but they could opt out by using fira-mono).

All this should be per-user, not per canvas.

**Comment by pbiggar** [comment]
Closing as it doesn't apply to darklang-next
