### ISSUE TITLE
copy and paste is pretty broken

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#3838]
Copy and paste is pretty broken, it's not hard to find examples by trying for a few minutes.

**Comment by pbiggar** [comment]
From https://github.com/darklang/dark/discussions/3834

> Copying and pasting code always feels like a gamble. Sometimes you have to rewrite the code because the pasted code get so mangled in the process.

**Comment by pbiggar** [comment]
From https://github.com/darklang/dark/issues/2806

> Oftentimes you want to move code between HTTP handlers, REPLs, and/or functions. However, due to the enforced structural editing, copy and pasting usually leads to a broken state and I have to manually type/edit parts of it out again to make the editor happy.

> extract-function in theory should fill this role, but in practice it does not. What if you're wanting to copy functionality between an HTTP handler and a REPL, between REPLs, or between functions?

> This isn't a core blocker (you can just retype the functionality you want in a new context), but is a bit frustrating.

**Comment by xumx** [comment]
From #3785 

Allow empty lines to be added in code might be a quick and dirty solution.

**Comment by Thyrst** [comment]
Here goes an example:

https://user-images.githubusercontent.com/2419285/211102876-7e9441c9-bab0-4828-b94e-02d49de9fb24.mov

**Comment by pbiggar** [comment]
Closing as it doesn't apply to darklang-next
