### ISSUE TITLE
add new version of existing httpclient without the eggregious problems

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#3839]
The new F# httpclients v0-v5 copy the old OCaml ones pretty exactly. As we did the transition, we noticed lots of problems. We replicated them, but it would be better to add a v6 version that doesn't have these weird problems.

These include:
- keeping the headers for redirects
- adding a header with the status code
- only doing latin1 decoding
- manually handling compression (implementation detail to allow the content-encoding headers to appear)
- disabling http3
- using different casing in http headers depending on whether the request was http1 or http2
- manually handing redirects (may still be necessary to avoid dropping the auth header, or maybe we should drop the auth header)
- not sending headers with empty values
- incorrectly check the headers for json/forms
- have confusing logic for when to parse json

I notice something in the code saying we shouldn't redirect POSTs to GET - I think that's an incorrect comemnt and that we should in fact do that.

This does not need to be perfect: just get rid of the dumb behaviour.

**Comment by StachuDotNet** [comment]
we've done a pretty good job of these. Referenced in a larger issue for futher review, but otherwise closing this for now.
