### ISSUE TITLE
add BaseHttp client with sends bytes and headers and received bytes and headers

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#3840]
Add a version of Httpclient that does almost nothing, so that httpclients with different behaviour can be built on top of it. There should be options for things that cant' be controlled in other ways:

- which http version to use (default 3)
- whether to decode charsets automatically (default yes)
- whether to decode compression automatically (default yes)

It should accept bytes and return bytes

**Comment by pbiggar** [comment]
@StachuDotNet Is this ready to be called done?

**Comment by StachuDotNet** [comment]
yeah
