### ISSUE TITLE
we should have more control over cron timing

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#3842]
Developers want more control over the timing of crons:

- what time of *interval* crons go out (eg Fridays at 2pm)
- frequency per interval and better intervals (eg once every 3 days)

**Comment by pbiggar** [comment]
From https://github.com/darklang/dark/issues/2806

> For [cron](https://docs.darklang.com/component-cron) components, you can specify certain intervals, but you can't say when you want it to start, it appears to start when you first create the component.

> For example, let's say I want to calculate some stats at 10pm every night. Currently I'd have to wait until 10pm to create this cron.

> Perhaps even more than not being able to set the time at which a cron runs, it would be nice to have visibility into when it's running (e.g. "Daily at 5pm", "Weekly on Sundays at 7pm", ...) Currently you can infer this by looking at previous times it ran + the run frequency, but that seems unnecessarily opaque.

> A more usable UI would be to add to the title of the cron component more info like:

> `CRON Daily 10pm             update_my_stats    `
>
> `CRON Weekly Sundays 5pm     check_rss_feeds    `
> 
> `# And maybe include next time it'll trigger`
> `CRON Weekly Sundays 5pm     check_rss_feeds    Next: 2020/09/27 @ 5pm`

**Comment by StachuDotNet** [comment]
folded into #5261
