### ISSUE TITLE
Make it easy to contribute

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#3851]
Right now, contributing means learning F# or Rescript, which takes an experienced developer weeks in many cases.

The best way to make it easier to contribute is to build as much of Dark as we can in Dark, and create a permissioning system so that people can contribute to it.

That includes:
- packages
- canvases
- in-editor tooling
- documentation
 
This should all be contributatable via the Dark editor

**Comment by StachuDotNet** [comment]
Closing this -- #5311 probably covers this well enough, for now, and these individual items will resurface as they become relevant again.
