### ISSUE TITLE
Improve the feeling of safety while using dark

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#3852]
It can feel quite unsafe to use Dark:

- version control is poor (undo-based only) and the undos are slow
- not all ops make it to the server
- you can't see who made a change.
- copy-and-pasting and refactoring commands can both mess up your code
- even pasting in a big string does not work lend itself to feelings of success
- the features that we intend to have around migrations, locking and feature flagging, are not present yet
- users are not notified of errors, and it's somewhere between challenging and impossible to find them when they occur. 

Ultimately, this will best be solved by building more of Dark in Dark and resolving issues as they come up.

**Comment by StachuDotNet** [comment]
let's see how this comes up in dark-next with the new editor; a lot of the issues here were related tot he old flow, I think
