### ISSUE TITLE
Prepare Stachu for ops management while Paul out

### ISSUE THREAD

**Issue by StachuDotNet** [darklang/dark#3853]
June 10-22

Pairing Tasks:
- [x] go over honeycomb and our usage
- [x] practice: get into prod devcontainer
- [x] practice: get kubernetes logs
- [x] review incidents over past year
- [x] review recent rollbars
- [x] reduce the incoming rollbars

Tasks for Stachu:
- [x] install pagerduty on phone
- [x] study "what to do if something goes wrong"
- [x] bypass DND for pagerduty on phone
- [x] add Kate as contact on phone
  - [x] bypass DND
- [x] study pagerduty
- [x] review GCP dashboards
- [x] review a few Dark `ops-` canvases
  - [x] ops-corpsite is darklang.com
  - [x] ops-login
  - [x] ops-adduser
  - [x] ops-presence
- [ ] review [production accounts](https://github.com/darklang/dark/blob/main/docs/production/accounts.md)
  add some links
- [x] study Rollbar. ([this](https://www.youtube.com/watch?v=Pc7HgWZ8mxQ) video is probably enough)
- [x] study [kubectl](https://kubernetes.io/docs/tasks/tools/) basics
- [ ] keep review [if things to wrong](https://github.com/darklang/dark/blob/main/docs/production/what-to-do-if-something-goes-wrong.md) doc.
  Add some links where relevant
  - [ ] "apparmor" -> "google cloud armor"
- [x] study betteruptime
- [x] learn how to contact GCP support
- [x] practice accessing users' canvases for emergencies
  by way of `add-user` canvas.
  (get into your other account)
- [x] review shipit code
- [x] review auth0 usage
- [ ] figure out what we use name.com for
- [x] subscribe to alerts [here](https://console.cloud.google.com/monitoring/alerting/policies/6080750562617246495?project=balmy-ground-195100)

Tasks for Paul:
- [x] get Stachu all relevant credentials
- [ ] grant Stachu access to more Auth0 tenants. (right now, only Development is seen - I reckon we have others)
- [ ] gather contractors for reference

**Comment by StachuDotNet** [comment]
@pbiggar For this topic/Issue, would it be best to 1:1 for a bit on this, or track via Slack/GitHub/other?

**Comment by StachuDotNet** [comment]
- [ ] Stachu to review https://github.com/darklang/dark/blob/main/docs/production/accounts.md
- [ ] Stachu to review https://github.com/darklang/dark/blob/main/docs/production/what-to-do-if-something-goes-wrong.md

**Comment by pbiggar** [comment]
Also get set up with betteruptime (pagerduty replacement)

**Comment by StachuDotNet** [comment]
> WDYT?

Sounds good. Currently processing and will follow up this week.

Question: what should I do if I find myself wholly ignorant of how to resolve some problem? Can I seek external consultancy for help? Legally? Anyone you'd recommend? There's a lot of stuff in dark that's out of reach for me currently: rust, kubernetes, etc. In the unlikely event something breaks somewhere I'm totally ignorant, what should I do? (Besides contact you, in a rare case)

**Comment by pbiggar** [comment]
I can think up a couple of consultants I've worked with before for kubernetes and postgres issues.

Rust issues won't happen I'm pretty sure. Just don't touch anything in the queue scheduler :)

I can also add you to google cloud support.

**Comment by StachuDotNet** [comment]
Something to consider: a code cutoff prior to Paul's departure, to ensure some stability of released code (preventing too many rollbars around recent code).

**Comment by StachuDotNet** [comment]
@pbiggar Could you send me the contacts of a small # of consultants to reach out in case of emergency? Hopefully I can get through anything myself, but would be good to have stand-bys with more experience in GCP and kubernetes stuff in particular.

**Comment by StachuDotNet** [comment]
I'm feeling pretty good at this point. Studying a bit more `kubectl` and exploring `production/scripts` but good enough.
Extracting some TODOs from this doc (e.g. improving some of the docs/production updates on this list) then will close

**Comment by pbiggar** [comment]
Sent some contacts by email.

**Comment by StachuDotNet** [comment]
I saw - thanks!
