### ISSUE TITLE
Don't allow pushes directly to `main` for Dark admins

### ISSUE THREAD

**Issue by StachuDotNet** [darklang/dark#3874]
Sometimes I make small changes via the GitHub UI itself, rather than doing a `git` dance locally.

As-is, it'd be too easy to accidentally push to `main`. This is a setting @pbiggar can adjust very easily somewhere in https://github.com/darklang/dark/settings (I've used it before on other repos)

![image](https://user-images.githubusercontent.com/906686/169867512-440c2f2d-7548-41c7-9e57-435b10bc983d.png)

**Comment by pbiggar** [comment]
I think I chose to leave that in so that we could push to main in case of emergency. Or maybe it was that i coudn't find the button (also, i can't find the button now)

**Comment by StachuDotNet** [comment]
Here's the button

https://user-images.githubusercontent.com/906686/169869942-210c7513-50ec-410c-9292-9abd2a3ad8b0.mp4

**Comment by StachuDotNet** [comment]
Up to you, end of day - just raising the awareness of the risk.

**Comment by StachuDotNet** [comment]
For emergencies, the extra overhead of creating a PR and then clicking the "yeah I'm ignoring the fact that CI isn't done" dialog in the PR seems slight enough to me. That said, I haven't faced many damning prod issues with Dark yet.
