### ISSUE TITLE
Create Http middleware functions in stdlib package

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#3892]
We should allow multiple http frameworks, based on a middleware approach.

We should create a bare-bone http framework option for handlers. Instead of doing everything that the current one does, it would only read the headers, url, body (as bytes) from ASP.net.

The option for which middleware to choose would be made in the HTTP handler spec.

From there, we could provide many middleware functions that parse json, dynamically parse the body based on content-type, support CORS, handle compression, and everything else that our middleware does.

**Comment by StachuDotNet** [comment]
folded this into #5261
