### ISSUE TITLE
Lock dotnet tool versions in Dockerfile

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#3896]
https://github.com/darklang/dark/blob/bd1bd7408be9b34099bbf79273f3d716c8ebd57b/Dockerfile#L362-L363

**Comment by pbiggar** [comment]
I looked into this and I can't see how to do add versions

https://github.com/dotnet/docs/blob/main/docs/core/tools/dotnet-workload-install.md

**Comment by StachuDotNet** [comment]
I see `--version` noted on this page https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-tool-install

**Comment by pbiggar** [comment]
Oh yeah. Do you see where to get the version number?

**Comment by StachuDotNet** [comment]
Actually, I think my link was irrelevant.

I'm not seeing a way, and I'm not finding a version for `wasm-tools` locally at all (searching within /usr/share/dotnet)

**Comment by pbiggar** [comment]
Yeah, I guess that was for tools.

I removed the sos tool in #4017, as it was for debugging native code and we don't have any anymore.

**Comment by StachuDotNet** [comment]
Maybe we can make an Issue to ask about this in some `dotnet` repo - `runtime` maybe?

**Comment by pbiggar** [comment]
Go for it!

**Comment by StachuDotNet** [comment]
https://github.com/dotnet/runtime/issues/69951

**Comment by StachuDotNet** [comment]
https://gist.github.com/filipnavara/4611f15c9a3045108eeae5a98750f64f

**Comment by StachuDotNet** [comment]
Folded into #5246
