### ISSUE TITLE
Add people to queueworker rollbar

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#3905]

**Comment by StachuDotNet** [comment]
Is the goal here to include the identifier of a Dark user in data sent to Rollbars that happen within QueueWorker?

**Comment by pbiggar** [comment]
Yes. I took a look and it wasn't very easy, so I moved on. I don't mind deprioritizing if this continues to be hard.

**Comment by StachuDotNet** [comment]
Folded into #5246
