### ISSUE TITLE
Change ApiServer tests (instead of testing against the old OCaml server)

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#3909]

**Comment by StachuDotNet** [comment]
Is this still relevant? If so, could you please clarify here?

**Comment by pbiggar** [comment]
Yes, still relevant. There's a ton of commented up tests in ApiServer.Tests.fs, which test that the output is the same in the ocaml and F# versions. They should be turned into unit/functional/controller tests.

However, since we're now replacing ApiServer with editor.darklang.com, they should really be replaced with tests in that canvas (however that is to be achieved).

**Comment by pbiggar** [comment]
Might still be relevant, but a kinda useless issue, so closing.
