### ISSUE TITLE
Investigate "killed" in asset upload: https://app.circleci.com/pipelines/github/darklang/dark/2912/workflows/242c6cc9-161b-44ac-9069-a9ee77eac64c/jobs/31251

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#3913]

**Comment by StachuDotNet** [comment]
Resolved recently.

We had started uploading many more files during CDN upload during CI, once we started to ship AOT Blazor assets.
This resulted in many many concurrent gsutil calls, resulting in out-of-memory issues that led to a SIGKILL, iirc.
