### ISSUE TITLE
static assets tests are disabled

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#3919]
Looks like the deploy hashes aren't always being ordered right when fetched

**Comment by StachuDotNet** [comment]
These tests were since [disabled](https://github.com/darklang/dark/blob/6af54726fcf429768f0e05f656684b868d42cf46/fsharp-backend/tests/testfiles/staticassets.tests#L88) and a new goal should be to bring them back safely.

**Comment by pbiggar** [comment]
Not applicable in darklang-next.
