### ISSUE TITLE
Rewrite static assets feature in Dark

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#3932]
- remove remaining OCaml editor-servers

**Comment by StachuDotNet** [comment]
(WIP research brain-dump)

# Porting Static Assets to Dark

## Relevant files in code (all in `fsharp-backend`):
- `src/ApiServer/Api/APIInitialLoad.fs`
- `src/BackendOnlyStdLib/LibStaticAssets.fs`
- `src/LibBackend/Config.fs`
- `src/LibBackend/Pusher.fs`
- `src/LibBackend/StaticAssets.fs`
- `src/LibBackend/webserver_apiserver.ml.unported`
- `tests/httptestfiles/serve-latest.test`
- `tests/staticassets-tests/README.md`
- `tests/testfiles/staticassets.tests`
- `tests/Tests/ApiServer.Tests.fs`
- `tests/Tests/LibExecution.Tests.fs`
- `tests/TestUtils/TestUtils.fs`

## Existing Functionality
- upload static assets
  - external upload script
  - backend stuff that handles the uploads by the script
- access via StdLib fns in BwdServer
  (list them out here)
- display the static asset deploys within the Editor
  - ApiServer gathers this during `initial_load`
  - ui.html and the `client` code coordinate to display such
- upload static assets (currently only in OCaml)
  - call Pusher when performed so client gets notification of new assets

## Open Questions:
- Should `StaticAssets` should be a Package wholly outside of the Dark repo?
  - verify: are staticassets a stdlib thing right now? (I think so)
  - we would need at least a thin proxy for existing code that uses the stdlib fns
  - can we ReplacedBy from a StdLib module to a Package? not sure how that would work.
  - it's probably best to just leave it in StdLib right now, with no changes to versions or anything, and consider after the majority of the work

## TODOs
- [ ] list out the stdlib fns here
- [ ] read through those code files and expand upon this document

**Comment by pbiggar** [comment]
> Should StaticAssets should be a Package wholly outside of the Dark repo?

No. Packages don't have the ability to dip into the runtime like StdLib functions do (and they're not intended to).

**Comment by pbiggar** [comment]
> external upload script

This is https://github.com/darklang/dark-cli

**Comment by StachuDotNet** [comment]
What do you mean by "dip into the runtime"?

**Comment by pbiggar** [comment]
A stdlib function is written in F#, so it can call functions and use types from LibBackend. But a package can only call things already exposed as Stdlib functions.

**Comment by StachuDotNet** [comment]
I'll be continuing this work in #4259 for a while, focusing specifically on the _upload_ of static assets. Eventually we may circle back to rewriting the whole thing in Dark.

Note that while there's some discussion about _needing_ to dip into the runtime, we likely don't need to - we can simply replace our "internal" Postgres table with a Dark datastore in a canvas.

**Comment by StachuDotNet** [comment]
There's some related discussion in #4278 worth reading. (all future-thinking, not planning)

**Comment by pbiggar** [comment]
Not applicable in darklang-next.
