### ISSUE TITLE
Convert all http framework headers to lowercase

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#3946]
As far as I can tell, every http request received by dark has its headers names in lowercase. I think this is done at the google load balancer.

We should add this guarantee to the http framework as well. This will avoid things changing without us noticing.

~Note: that might be true for http2/3 only perhaps! Nope, this is true for http1.1 as well~

We should do this for HttpClient as well

**Comment by pbiggar** [comment]
Is this done? @StachuDotNet

**Comment by StachuDotNet** [comment]
Yes - we toLowercase on the way in (for request headers) and on the way out (for response headers).
