### ISSUE TITLE
Reference DBs, UserTypes, and UserFunctions in ASTs by ID rather than Name

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#3964]
Functions, DBs and types are all referenced in the AST by name. Instead, we should refer to them by TLID. This means they won't go out of sync, they're faster to look up, and they're less likely or impossible to accidentally refer to a non-existing one. This will also mean that renaming them won't require changes to other toplevels (a key way these go out of sync)

**Comment by StachuDotNet** [comment]
folded into #5259
