### ISSUE TITLE
Send users alerts and notifications

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#3991]
Use cases of notifications:

- analytics, generally being aware
  - send daily or weekly or at user-defined cadence with how much traffic they have
  - partially for funsies and partially to make people aware that they have a lot of traffic
  - by default, don't send if there's no traffic

- error reporting
  - if something came back was on the errorrail
    - note: people might not be aware of the errorrail or that they're using it
  - if you returned an DError, DIncomplete
  - if you returned Error
  - if there's an error in the queue, such as you don't have a handler for this
  - some people are generating thousands of these. We should do backoff or consolidate

- operational: we want people to turn off useless computation
  - some people are not aware how much computation they're running, especially on CRONs every minute
  - we should first have the ability to delete canvases, delete handlers, or disable handlers, especially CRONs

Plan:
- design for who gets what notification when (especially back-offs)
- design user controls for notification, especially opt-out
- design emails
- add ability to delete and disable so that users aren't notified
- tell users in advance that notifications are coming in

**Comment by StachuDotNet** [comment]
folding this into a larger issue shortly
