### ISSUE TITLE
Keep trace active when moving around

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#3992]
When I'm on a handler and I click on a function, I want to stay on the same trace

**Comment by pbiggar** [comment]
This is really really annoying when debugging anything. I find I have to manually add the trace myself to the url and then reload the page.

**Comment by pbiggar** [comment]
Issue gone with the old client, but worth keeping this as a suggestion when we build the new client.

**Comment by StachuDotNet** [comment]
Closing - this will come up naturally eventually when working with the new editor
