### ISSUE TITLE
Manually purge some accidental static assets in prod

### ISSUE THREAD

**Issue by StachuDotNet** [darklang/dark#3997]
#3984 accidentally uploaded some files to the root of the bucket, where they're not relevant.

Namely, I'm thinking about .dll files that shouldn't be there.

We can/should tidy these up manually. If that makes sense to you, @pbiggar, I'm happy to carefully do such.

**Comment by pbiggar** [comment]
Yeah we can do it together if you want

**Comment by StachuDotNet** [comment]
I felt comfortable doing this myself - done now, and happy with results.
