### ISSUE TITLE
Port a new version of blazor.webassembly.js / BlazorWorker

### ISSUE THREAD

**Issue by StachuDotNet** [darklang/dark#4001]
Or contribute to .net such that the official one works

**Comment by StachuDotNet** [comment]
Maybe it'll load faster

**Comment by StachuDotNet** [comment]
What do you think, Paul - is it worth investing a # of hours to contributing to aspnet such that an npm package with a webworker-friendly blazor.webassembly.js can be publishable? I think it'd be fun, anyway. I'll have to revisit our old issues to see if a good Issue already exists

**Comment by StachuDotNet** [comment]
Note: I'd like to break from Blazor before too long, so this isn't volunteering myself to do this soon :)

**Comment by pbiggar** [comment]
> What do you think, Paul - is it worth investing a # of hours to contributing to aspnet such that an npm package with a webworker-friendly blazor.webassembly.js can be publishable? I think it'd be fun, anyway. I'll have to revisit our old issues to see if a good Issue already exists

I wouldn't go so far as this, but I think a few hours of trying to port the official script to support webworkers and upstreaming it would be worth it.

**Comment by pbiggar** [comment]
Closing as it doesn't apply to darklang-next
