### ISSUE TITLE
Improve load-time of F# wasm

### ISSUE THREAD

**Issue by StachuDotNet** [darklang/dark#4003]
I'm sure this is a dupe, but wanted to jot a few notes down quickly:

- `<BlazorWebAssemblyLazyLoad Include="Something.dll" />`
- https://docs.microsoft.com/en-us/aspnet/core/blazor/performance?view=aspnetcore-5.0
- https://docs.microsoft.com/en-us/aspnet/core/blazor/webassembly-lazy-load-assemblies?view=aspnetcore-5.0
- copy some notes from #4002

**Comment by StachuDotNet** [comment]
load Blazor
	114 requests
	30.3MB transferred
	139MB resources
	finish 2.88s

load OCaml
	38 requests
	2.9 MB transferred
	38.9MB resources
	finish 1.78s


why do we call get_unlocked_dbs after loading with OCaml, but not Blazor?

**Comment by StachuDotNet** [comment]
brotli

**Comment by pbiggar** [comment]
How are we doing on this? Feels pretty quick these days, at least relative to the old days.

**Comment by StachuDotNet** [comment]
Personally, it'd been loading certainly "fast enough," and I haven't heard any complaints. Maybe we close this issue until it comes up? With an eventual .NET 7 upgrade, we may gain free wins here anyway.
