### ISSUE TITLE
Program doesn't load with blazor

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#4004]
I suspect it's to do with serialization of NaN and Infinity (they're probably serialized at `"NaN"` vs `NaN` in the old one).

```
{
  a : 0.0 / 0.0
  b : 1.0 / 0.0
  c : 5.6
}
```

**Comment by pbiggar** [comment]
Solution is probably to modify Decoders.res.

**Comment by StachuDotNet** [comment]
Having replicated locally, this seems to actually fail during serialization (within our F# code), not yet getting to Decoders.res.

I believe we'll need to adjust the `Vanilla` serialization to account for these special NaN/Infinity cases.
Seems we did such in the non-Vanilla case, but not in Vanilla?

[here](https://github.com/dotnet/runtime/issues/40140#issuecomment-666518168)'s a point I'll start with.

**Comment by pbiggar** [comment]
I think the STJ formatters have an option for this.

**Comment by pbiggar** [comment]
https://docs.microsoft.com/en-us/dotnet/api/system.text.json.serialization.jsonnumberhandling?view=net-6.0#fields

**Comment by StachuDotNet** [comment]
Thanks
