### ISSUE TITLE
Get F# Analyzers working in VS Code

### ISSUE THREAD

**Issue by StachuDotNet** [darklang/dark#4029]
https://medium.com/lambda-factory/introducing-f-analyzers-772487889429

**Comment by StachuDotNet** [comment]
@pbiggar any initial ideas for analyzers?

**Comment by pbiggar** [comment]
They always seem less pressing after the fact. I think let's just add them and see what they say, and then we can add more later once it becomes obvious.

Just remembered one, banning this:

```
  try
    task {
      // stuff with exception
    }
```

**Comment by StachuDotNet** [comment]
F# analyzer to add: 2 newlines after a stdlib fn definition.
