### ISSUE TITLE
Make canvas work well for 10MB of data

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#4035]
The canvas can be quite slow for "large" amounts of data. While in the future we would like to handle many gigs of data through some clever cloud/editor hybrid solution, for now we should make sure that the canvas works well for reasonably large amounts of data that a user would like to have. This includes:

- loading 10MB of values from the DB
- returning 10MB of json from HTTP client
- http requests with 10MB of json

Specifically:
- the editor should be responsive and not at all sluggish when the trace is selected
- execute_function and execution_handler should work fine
- the trace should load
- nothing should error
- analysis should be available

**Comment by pbiggar** [comment]
A first step would be to list out the errors that users experience when trying to use it.

Here's the ones I'm aware of:

- requests with more than 10k of data won't have a trace sent to the canvas
- the rendering starts to get sluggish at around 1MB of data
- we get the big red error bad when calling execution_function or execute_handler with large data
- if we can't complete analysis, we get no live values at all
- large traces won't load (typically the result of too many function_results) - this will be solved by moving traces to S3, which is planned soon anyway.

**Comment by StachuDotNet** [comment]
not really relevant to dark-next
