### ISSUE TITLE
Canvas entirely frozen when I try to paste in absurdly large text

### ISSUE THREAD

**Issue by StachuDotNet** [darklang/dark#4060]
Warning, large file:
https://gist.githubusercontent.com/marcusturewicz/63985290c03386903ce2bdcad8b0bcbe/raw/e26412de8e062db6c74f1a71ff567d0afac9cffd/10000.json

If I create a REPL and attempt to paste the contents of that .json into a pair of quotes "", the screen freezes 

![image](https://user-images.githubusercontent.com/906686/171304294-56e092f3-654a-4c41-be15-ae529f5516d1.png)

I don't think we need to allow someone to do this, but we should handle failure better

**Comment by pbiggar** [comment]
Closing as it doesn't apply to darklang-next
