### ISSUE TITLE
Ocaml? Is this an obsolete error message?

### ISSUE THREAD

**Issue by gunnarahlberg** [darklang/dark#4107]
https://github.com/darklang/dark/blob/dc20a7a16e9fcd37648ab4a3899b1c1b1241102b/scripts/run-backend-server#L36

is this true? Thought ocaml is gone 😉
but I am just surfing the code

**Comment by pbiggar** [comment]
Not gone yet, we still run two ocaml services, they're just not going to be replaced with F# services (instead, one will be rewritten in Dark, and one won't be required after #3954).

References to "backend" still refer to ocaml, and all F# references use fsharp in the name. So for example the important script here is `./scripts/run-fsharp-server`

**Comment by pbiggar** [comment]
Thanks for looking - please feel free to ask any questions as you look around!
