### ISSUE TITLE
Dates get modified when passed in a function call

### ISSUE THREAD

**Issue by edman** [darklang/dark#4114]
It seems dates get added 2h when passed by parameter to functions.

As a minimal example consider a function that takes a time and returns it:
![Screenshot 2022-06-08 at 14 33 32](https://user-images.githubusercontent.com/1776440/172619559-f00c432d-4869-4848-9d31-9ef75d7f032c.png)

Then here's a REPL that creates a time, passes it to the function above, and compares them for equality:
![Screenshot 2022-06-08 at 14 33 21](https://user-images.githubusercontent.com/1776440/172619651-bdc83cac-621c-485b-b62d-79583d3af2e3.png)

Notice the trace output shows the time is `"02:00:00"` instead of the expected `"00:00:00"`.

Somehow the bug does not manifest if I "live modify" the timestamp parsed in line 1 of the REPL and the output is correct. But if I click either the "reload" icon on the top right, or the green reload icon for the `sameTime` invocation, the result updates to the wrong one as shown in the screenshots.

**Comment by StachuDotNet** [comment]
Thanks for reporting.

So far, I think that this is an in-Editor-only problem.
If I create a simple HTTP handler of `Date::now`, and preview the fn in the Editor, I see this:
![image](https://user-images.githubusercontent.com/906686/172653834-5c55a2c5-860e-42dd-be9f-f3a454959ed4.png)

`2022-06-08T11:15:27Z`

But if I go to the corresponding route in my browser, `http://dark-brand-new.builtwithdark.localhost:11001/now`, I get:
`2022-06-08T15:15:29Z`

Relevantly, if I watch network traffic when playing the function within the editor, the `execute_function`, I see that `2022-06-08T15:19:24` is the result. (ran this a few mins later)

---

Something in the Wasm code likely needs to change here

**Comment by StachuDotNet** [comment]
This is resolved with #4260.
