### ISSUE TITLE
Refresh editor upon deploy if not in use

### ISSUE THREAD

**Issue by StachuDotNet** [darklang/dark#4119]
We'd like to have users on the most recent version of the client if possible, for a variety of reasons.

e.g. if you bug-fix an issue with the Editor, this would prevent rollbars coming in for the bugs after they've been fixed due to users on an older client.

**Comment by StachuDotNet** [comment]
"upon deploy" may not be ideal timing, but it's a decent option. we could probably Pusher that to happen, maybe staggered?

**Comment by pbiggar** [comment]
Pusher isn't super reliable for tabs that aren't active (off the internet right now, etc). Easy to miss the message.

What about ping once an hour?

**Comment by pbiggar** [comment]
Closing as it doesn't apply to darklang-next
