### ISSUE TITLE
Switch back to Ply in Analysis/Wasm project

### ISSUE THREAD

**Issue by StachuDotNet** [darklang/dark#4122]

**Comment by StachuDotNet** [comment]
We're using Ply in most layers of Analysis/Wasm already, just not within Wasm.fs/Analysis.fs itself.

The real output of this issue should be removing the `.Result` some day, or at least adding a note that it's blocked by .NET 7 upgrade. (to be confirmed)

**Comment by pbiggar** [comment]
Closing as it doesn't apply to darklang-next
