### ISSUE TITLE
Don't fail when an unexpected Pusher.com push is received by client

### ISSUE THREAD

**Issue by StachuDotNet** [darklang/dark#4131]
Rather, we should simply log this away.

**Comment by pbiggar** [comment]
What do we want to do with this?

**Comment by StachuDotNet** [comment]
> What do we want to do with this?

I think there are a few Pusher.com efforts to take care of:
- (client) when an unexpected Pusher.com event comes in, create a rollbar that doesn't result in any UI "error bar"
- (client) handle the "AddOpV1 payload too big" pusher.com event that is currently sketched out
- (server) push that ^ event when appropriate (right now, code is just commented out)

(# 2 and 3 could safely be done at the same time, if the first is out the door for a bit)

Intuitively this doesn't seem like a ton of effort.

**Comment by StachuDotNet** [comment]
Killing this issue for now - let's see if/how pusher.com relates to dark-next and revisit then.
