### ISSUE TITLE
Provide notes on loading fsharp-backend outside of devcontainer

### ISSUE THREAD

**Issue by StachuDotNet** [darklang/dark#4139]
I just tried to load fsharp-backend in JetBrains Rider, and found that I had to delete https://github.com/darklang/dark/blob/main/fsharp-backend/Directory.Build.props - otherwise, it fails to compile, looking for a directory that isn't there (`/home/dark/app...`)

I'm not sure the best place to put such a note - maybe the root readme, or a readme within fsharp-backend?

**Comment by pbiggar** [comment]
Might fit nicely in this category: https://github.com/darklang/dark/blob/main/README.md#less-important-docs

**Comment by pbiggar** [comment]
Close this?
