### ISSUE TITLE
Upgrade to .NET 7

### ISSUE THREAD

**Issue by StachuDotNet** [darklang/dark#4161]
Do we wait for full release (~November) or jump earlier?
FWIW, per https://github.com/dotnet/runtime/issues/70286#issuecomment-1156652738 the `.Result` that we're currently doing in Analysis.fs/Wasm.fs should be removable with .NET 7 upgrade.

(I'm not pushing to go upgrade early - just raising the question)

- [ ] Review all `DOTNET7TODO`

**Comment by pbiggar** [comment]
Personally I don't like to upgrade before a "release candidate" version, if we can help it. I'm not strongly opposed to doing an upgrade if it's required before then, though involves doubling the upgrade work.

**Comment by pbiggar** [comment]
We removed the .Result issue, however the following issue remains:


<img width="1083" alt="Screen Shot 2022-09-05 at 5 01 43 PM" src="https://user-images.githubusercontent.com/181762/188512172-bf0333be-521c-4c82-8f77-3ffecd4d1197.png">

Do you think that this issue will also be solved by moving to .Net 7?

**Comment by StachuDotNet** [comment]
I'm unsure, but suspect it would be - the .net team has note general improvements to this wort of functionality [here](https://github.com/dotnet/runtime/issues/70286#issuecomment-1152563856) and would imagine this would be part of that.

**Comment by pbiggar** [comment]
OK, I'm just going to hide the error for now then

**Comment by StachuDotNet** [comment]
Right I certainly think it's worth waiting until the .NET 7 upgrade and circling back here only if that _doesn't_ resolve the issue.

**Comment by pbiggar** [comment]
Done today!
