### ISSUE TITLE
Untangle ImpurePreviewable

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#4162]
Dark has a concept of purity for built-in functions:

```
type Pure = 
  Pure
  | Impure
  | ImpurePreviewable
```

The intent of Pure functions is that we don't need to store their analysis results, as we can recalculate them on the fly. Impure functions we can't however, as we might get a different result.

ImpurePreviewable is a set of functions where they do not have side-effects, but they also don't return the same result every time. `Date::now` is a good example. This is a useful annotation as it could allow us to automatically execute the function when a function is added. This is all good, but the name `ImpurePreviewable` isn't the greatest name for this, perhaps we can come up with something better.

There is another related category which should be factored into this, which is functions which are pure or are impurePreviewable, but do not have a client side implementation available (due to something missing in blazor usually). We should probably mark them separately from Pure/Impure/ImpurePreviewable, either with another boolean flag (probably) or another category. Then we should think about how to use that info to give a better experience to users using these functions (perhaps they could execute automatically using the server if they're pure or previewable?)

**Comment by StachuDotNet** [comment]
folded into #4185
