### ISSUE TITLE
Make undo/redo multiplayer

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#4172]
This article is a good discussion, and lots of the things they mention are things  we do poorly or wrong. https://liveblocks.io/blog/how-to-build-undo-redo-in-a-multiplayer-environment

A good starting point would be a list of things we do wrong/badly.

Off the top of my head:
- we make a user undo through all canvas moves
- no animation on undo/redo
- users do not have separate undo/redo from other users
- there is no "debouncing" - eg if you type a string you have to undo through each step

**Comment by pbiggar** [comment]
- selection is not in the undo state
- neither is cursor position

**Comment by StachuDotNet** [comment]
Folding this into #5237 until it comes up again
