### ISSUE TITLE
Provide guidance on appropriate static asset usage

### ISSUE THREAD

**Issue by StachuDotNet** [darklang/dark#4173]
Does Dark have any issue in housing and serving large static assets, e.g. as a host for .mp3s of a podcast website?

Long-term I imagine users would be charged based on the storage+usage, but some brief guidance in docs or otherwise around what usage is "appropriate" would be useful.

**Comment by pbiggar** [comment]
Good idea. The intent of static assets it to be used for the build output of html/js/css stuff for SPAs (and the feature pretty much designed around that use case).

For storage of things like mp3s of podcasts, we do plan a feature but this isn't it.

**Comment by StachuDotNet** [comment]
> For storage of things like mp3s of podcasts, we do plan a feature but this isn't it.
What's a name for that feature? I'll create a separate issue to track conversation (understanding we might not get to it for quite some time).

**Comment by pbiggar** [comment]
"File storage"
