### ISSUE TITLE
Allow users to clone functions

### ISSUE THREAD

**Issue by StachuDotNet** [darklang/dark#4175]
e.g. in this case, I'd like to generate many `htmlTagX` functions
![image](https://user-images.githubusercontent.com/906686/174510282-194a689d-aede-4d2d-adfa-a951561eeb1e.png)

**Comment by StachuDotNet** [comment]
An adjacent idea: generate Dark code from within Dark (so I can quickly generate a bunch of functions - either as fns that exist normally after the generation, or functions that are dynamically generated in ways I can change all at once later on.

**Comment by pbiggar** [comment]
Another reason for this is that developers want versioned functions so that they don't break existing code. We planned to allow locking handlers that are in use, so that devs can be sure to not break anything that's running - which would require copying the whole stack of functions.

**Comment by pbiggar** [comment]
Also, allow cloning handlers

**Comment by StachuDotNet** [comment]
merged into #5237
