### ISSUE TITLE
Support Search across editor

### ISSUE THREAD

**Issue by StachuDotNet** [darklang/dark#4179]
When coding in Dark, I often reach for a (keyboard-centric) Search.

Namely, my hands reach for "Ctrl+Shift+F," and I expect some UI where I can search for Dark functions and toplevels I've defined quickly, ideally navigating to any datastore, user fn, etc. without leaving the keyboard.

At very minimum, this could be a simple overlay with search box and results below accessible via the arrow keys.

**Comment by StachuDotNet** [comment]
The Client may have everything it needs for an MVP already, without any backend work?

**Comment by pbiggar** [comment]
This is implemented already, just not particularly well. If you press Ctrl-k, then type a word, it will search all the code to find it and offer results. It was intended to be like spotlight, but it didn't really work out very well. Making it a separate thing would be a big improvement.

**Comment by pbiggar** [comment]
Closing as it doesn't apply to darklang-next
