### ISSUE TITLE
What happens if we have a massive response in blazor?

### ISSUE THREAD

**Issue by StachuDotNet** [darklang/dark#4189]
Let's test this and make sure our Editor handles it OK

_Originally posted by @pbiggar in https://github.com/darklang/dark/issues/2681#issuecomment-1163110934_

**Comment by StachuDotNet** [comment]
anecdotally, I tested some VERY payloads for both input and output of Blazor responses. Since migrating to `.Result` to resolve the GC-related Blazor issue, I hadn't seen problems with the large payloads.

**Comment by pbiggar** [comment]
Ah, finally triggered it

<img width="409" alt="image" src="https://user-images.githubusercontent.com/181762/175170405-88cba0e0-8402-4e18-8cd3-1971a1c66fc7.png">

**Comment by pbiggar** [comment]
This issue is specifically about "will it fail if we try to send a response that's too big", so I think we can safely say "no" and close this.
