### ISSUE TITLE
What do we call a space/module?

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#4210]
In the interest of consistency going forward, what should we call "type" of a handler. It is usually one of (though in the past we allowed an arbitrary "space" for workers, we don't allow that anymore):

- CRON
- WORKER
- HTTP
- REPL

We sometimes call it `module`, and sometimes `space`. Both of which aren't great names.

**Comment by StachuDotNet** [comment]
I like "handler category" or "handler class"

**Comment by StachuDotNet** [comment]
I think we sort of settled on `module`, with each of these (REPL, CRON, etc) being a different _kind_ of handler.
