### ISSUE TITLE
Consider accepting `any` instead of `string` in Result::fromOption

### ISSUE THREAD

**Issue by edman** [darklang/dark#4212]
`Result::fromOption` takes an `(option, string)`, forcing callers to use `string` to represent errors.

Accepting `any` allows more flexibility.

**Comment by pbiggar** [comment]
Yeah, I agree with this. We should deprecate the existing version and have a new version which takes `any`.

**Comment by StachuDotNet** [comment]
:+1: @edman do you have any interest in contributing this change?

I believe the changes would be confined to just 2 F# files:
- source: https://github.com/darklang/dark/blob/7f7a4088854f448074d1b93f9246e0c5e43316d4/fsharp-backend/src/LibExecutionStdLib/LibResult.fs#L164
- tests: https://github.com/darklang/dark/blob/main/fsharp-backend/tests/testfiles/result.tests

**Comment by StachuDotNet** [comment]
Thanks for the Issue, @edman  - resolved now.
