### ISSUE TITLE
Replace ApiServer with `dark-editor` canvas

### ISSUE THREAD

**Issue by StachuDotNet** [darklang/dark#4230]
In other words: rewrite ApiServer in Dark

Useful links:
- https://github.com/darklang/dark/blob/main/fsharp-backend/src/ApiServer
- https://darklang.com/a/dark-editor

**Comment by StachuDotNet** [comment]
Thinking out loud, some TODOs:
- [ ] review existing functionality within `ApiServer`
- [ ] review existing testing of `ApiServer`
- [ ] review internal functions (esp. the recently-exposed ones)
- [ ] write out the existing endpoints
- [ ] spend a few minutes sketching out what's needed for each of them
- [ ] spend some time thinking through how the ApiServer testing can be replaced/improved in Dark
- [ ] outline some rough ordering
- [ ] review current state of `dark-editor`
- [ ] review current state of other `dark-` canvases and `ops-`
  - [ ] note which are appropriate to eventually be merged to dark-editor
- [ ] decide how to host ui.html and login.html
  - [ ] ? strip down ApiServer to just host ui.html? (easiest)
  - [ ] ? push to static assets during CI? (sounds cool)
    - [ ] (how fast are static assets reliably available)
  - [ ] host via some other backend server? (enh)
- [ ] update documentation / references to ApiServer
- [ ] write a blog post

**Comment by pbiggar** [comment]
Relevant but out of date from Darklang-next
