### ISSUE TITLE
Support Tuple User Fn arguments and return types.

### ISSUE THREAD

**Issue by StachuDotNet** [darklang/dark#4239]
As of #4182 we won't be allowing users to _use_ tuples quite yet, so this functionality seems safe for now.

There are a few parts:
- type checking in the backend (see below comment)
- add TTuple to allowedParamTypes in Autocomplete.res, 
  - this will currently also effect allowedParamTipes
- testing of type checking (TypeChecker.Tests.fs)
- some stdlib functions to be used here^

**Comment by StachuDotNet** [comment]
Draft of TypeChecker.fs work:

```
  | TTuple (firstType, secondType, otherTypes), DTuple (first, second, theRest) ->
    // TODO: there's definitely a simpler way to gather these errors, but I'm blanking.
    let errors =
      [ (firstType, first); (secondType, second) ] @ List.zip otherTypes theRest
      |> List.filterMap (fun (t, v) ->
        match unify userTypes t v with
        | Ok () -> None
        | Error err -> Some err)
      |> List.collect (fun errs -> errs)

    match errors with
    | [] -> Ok()
    | errors -> Error errors
 ```

**Comment by StachuDotNet** [comment]
Some commentary here around autocomplete: https://github.com/darklang/dark/pull/4182#discussion_r912372275

**Comment by pbiggar** [comment]
> Some commentary here around autocomplete: [#4182 (comment)](https://github.com/darklang/dark/pull/4182#discussion_r912372275)

Clicking this link doesn't get me anything (I think due to github folding). Might be worth copying the text or conversation if it's valuable.

**Comment by pbiggar** [comment]
Works in daarklang-next (client part not applicable)
