### ISSUE TITLE
Prevent FakeDvalFound Errors

### ISSUE THREAD

**Issue by StachuDotNet** [darklang/dark#4250]
Context: a FakeDval is a value that we use to represent another concept (errorrails, runtime errors, blanks).

We're getting increasingly more `Exception of type 'LibExecution.Errors+FakeDvalFound' was thrown.` rollbars lately.

These are raised by 2 separate situations; there are relevant TODOs here:
- a fakeval in the SQLCompiler
  - [ ] update code to ignore these
- a fakeval that emerges from another function
  - [ ] update code to make a note of what functions generate these
  - [ ] consider deprecating the function causing it

Neither of those is super concerning / high priority, but they're noise, and might happen often enough to page us and possibly wake us sometime.

**Comment by StachuDotNet** [comment]
Relevant (now-muted) rollbar: https://rollbar.com/darkops/darklang/items/3385

**Comment by pbiggar** [comment]
Fakevals are gone as of #5085
