### ISSUE TITLE
Editor bug: Copying/pasting text elements breaks sometimes

### ISSUE THREAD

**Issue by StachuDotNet** [darklang/dark#4258]
If you try to shift-select a complex emoji like 👨‍👩‍👧‍👦, copy, and paste, it can sometimes fail.

This works: highlight the entirety of `"👨‍👩‍👧‍👦"`, copy, paste elsewhere

This fails: highlight just the portion `👨‍👩‍👧‍👦"` from `"👨‍👩‍👧‍👦"`, dragging from the right, copy, paste elsewhere.

Relevant rollbar: https://rollbar.com/darkops/darklang/items/3406

**Comment by StachuDotNet** [comment]
Note: shift-selecting the ECG and making sure you have EVERYTHING within the quotes, does work.

**Comment by pbiggar** [comment]
Closing as it doesn't apply to darklang-next
