### ISSUE TITLE
Rewrite Static Assets Upload in Dark

### ISSUE THREAD

**Issue by StachuDotNet** [darklang/dark#4259]
This is a large issue that forces us to tackle other large things, so won't be done for a while.

- [x] expose more `LibDarkInternal` fns: (implemented in #4278)
  - `startStaticAssetsDeploy` that results in an `INSERT` into the relevant DB
  - `finishStaticAssetsDeploy` that results in an `UPDATE` into the relevant DB (changing status)
- [ ] Dark needs to accept Bytes in HTTP handler requests (see https://github.com/darklang/dark/discussions/4325 and document linked within)
- [ ] Dark needs a new HttpClient that can request bytes (#3840)
- [ ] Then we need to actually write the Dark code

**Comment by StachuDotNet** [comment]
Note: this issue is towards replacing just the Static Assets _upload_ functionality in Dark.

Long-term, we may replace the entire feature in Dark. We can store the deploy references in a Dark Datastore and expose equivalents of the existing functions. The main wrinkle in "removing all Static Assets stuff from the Dark _repo_" project is that the Editor/Client shows the Static Assets within the sidebar, and handles some relevant Pushes. This will be an exciting thing to explore.

#3932 is the best Issue we have of tracking that larger project, though isn't currently being explored, likely ignored until the upload functionality replacement is complete.

**Comment by StachuDotNet** [comment]
The relevant OCaml code can be found starting in `libbackend/webserver.ml`,
- `static_assets_upload_handler` fn [here](https://github.com/darklang/dark/blob/a47dbb37ff460275e5c64911d0e02d58bfc8e6e5/backend/libbackend/webserver.ml#L565)
- the API route [here](https://github.com/darklang/dark/blob/a47dbb37ff460275e5c64911d0e02d58bfc8e6e5/backend/libbackend/webserver.ml#L1911)

This code reaches out to various other parts of the old `backend` - worth digging in more.

**Comment by StachuDotNet** [comment]
Thinking again, I'm not sure why I claimed that we need a new HttpClient that can request bytes for this Issue? If I can't remember why I claimed such, I'll remove it from the list in OP in a day.

**Comment by StachuDotNet** [comment]
There are recent efforts towards a byte-friendly HTTP Client and byte-friendly HTTP handlers [here](#4633) and [here](#4353) respectively. While both still aren't complete, the client feels closer than the handler (which will require several follow-up PRs outlined in [this Discussion](https://github.com/darklang/dark/discussions/4325) and the document linked within)

**Comment by pbiggar** [comment]
Removed static assets in Darklang-next
