### ISSUE TITLE
F# build caching in CI leads to us missing serialization test failures

### ISSUE THREAD

**Issue by StachuDotNet** [darklang/dark#4261]
I got some test failures I wasn't expecting, in CI:
https://app.circleci.com/pipelines/github/darklang/dark/3648/workflows/92203998-cbe8-4fee-ae53-81411c8930f5/jobs/38627

The PR doesn't change anything that would affect serialization, so something else is off.

I hit this issue both before and after increasing the build cache version # in the CI config (from v12 to v13)

I ran F# tests locally and found 4 new json files added in backend/serialization, but they're all `vanilla-` and don't account for these errors.
I haven't looked into this further yet.

**Comment by pbiggar** [comment]
This is odd - nothing obvious comes to mind here.

Those files should be in the repo. To debug this, I would suggest ssh-ing into the build and seeing why the files are missing.

**Comment by StachuDotNet** [comment]
> Maybe the files are hanging around from when we _did_ support them under OCamlCompatible, and that's confusing things?

No, the files aren't there. (ssh'd in). Still digging

**Comment by StachuDotNet** [comment]
Tried to replicate in a new PR, and got a totally different serialization test failure :expressionless: 
https://app.circleci.com/pipelines/github/darklang/dark/3654/workflows/7b39e7b7-67f9-4169-a5d9-da4b5390ddef/jobs/38688

**Comment by StachuDotNet** [comment]
Hm. Removing the caching from the CI build entirely, resolved that issue. I guess one of us (I think I) had set the version # to 13 at some point, so my attempt to increase didn't help, and just caused more confusion. Frustrating!

**Comment by pbiggar** [comment]
Yeah, this sort of thing worries me.

I'm having a similar worrying serialization test-related error: https://app.circleci.com/pipelines/github/darklang/dark/3659/workflows/bd0af303-6f4f-4bed-b397-ffeac011424c/jobs/38729

Maybe something to pair on tomorrow.

**Comment by StachuDotNet** [comment]
> Maybe something to pair on tomorrow.

Let's! any time 9a+ should be fine for me

**Comment by StachuDotNet** [comment]
I haven't seen this since our efforts in #4268. Closing until it pops back up.
