### ISSUE TITLE
Off-by-one Tuple Reconstruction bug

### ISSUE THREAD

**Issue by StachuDotNet** [darklang/dark#4264]
Given the tuple, `("aaa|aa", "c|cccc", "eeeee")` highlighting between the `|`s and cutting should leave `("aaa", "eeeee")` but leaves `("aaaa", "eeeee")`. There's some off-by-one error here.

Once these are done, 2 TUPLETODO commented-out tests are likely to auto-resolve.

**Comment by StachuDotNet** [comment]
Somehow, this has resolved itself? I can't reproduce, for lists or tuples.

**Comment by StachuDotNet** [comment]
Nevermind - I can repro - but seemingly only with mixed types? e.g. I can repro with ("hel|lo", 12|34) but not with 2 strings

**Comment by pbiggar** [comment]
How's this looking now?

**Comment by StachuDotNet** [comment]
Will be fixed by #4531
