### ISSUE TITLE
Migrate Presence to `dark-editor` canvas

### ISSUE THREAD

**Issue by StachuDotNet** [darklang/dark#4266]

**Comment by StachuDotNet** [comment]
So far, I've copied relevant Dark Datastore and code from `ops-presence` to `dark-editor`, and reviewed the code within this repo. I have some minor notes [here](https://dynalist.io/d/DApXWd0Y4xEIc1aymL5FG2UC#collapse&theme=dark) for my own sake, FWIW.

Some TODOs/thinking:
- [ ] try calling the endpoint in local dev and see what happens
- [ ] get that^ actually working
  - [ ] do I need to `ngrok` to test this? Intuitively I should be able to hit the endpoint locally without issue, but maybe there's a CORS issue I'm about to hit when I try
- [ ] get clarity on whether the `post` defined in `api/API.res` actually makes the HTTP call to the URL, or if that happens only when we determine we're in `prod`. If the latter, the code comment there is confusing and should be updated.

Some questions for @pbiggar:
- [ ] is there a minimal version of using darklang.io URLs for canvases that should be applied here, (I'm guessing it's overkill - just thinking) or should the resultant endpoint of this work simply be `POST https://dark-editor.builtwithdark.com/presence`?

**Comment by StachuDotNet** [comment]
#4271 was also required for this, done now

**Comment by pbiggar** [comment]
> fsharp-backend/src/HttpMiddleware/CorsV0.fs

This thing here was to make CORS work on the canvas. This used to be setting we could set on a canvas but it didn't make much sense as a feature and didn't get much use, so it's being slowly phased out. I removed the feature during the rewrite and any remaining users were hardcoded.

**Comment by pbiggar** [comment]
The post should be to https://editor.darklang.com/presence

**Comment by pbiggar** [comment]
> figure out where m.origin comes from in client

I could be wrong, but I think this was to address deficiencies in TestCafe, and is only used in integration tests. Perhaps it could be removed, I'm not sure.

**Comment by StachuDotNet** [comment]
FYI the subdomain was already set up.

**Comment by StachuDotNet** [comment]
Per work in #4294, I've tested the ported code, and it all feels good, including Pusher.com pushes coming in and being processed.
