### ISSUE TITLE
Replace `userIsAdmin`; allow users to opt in to the relevant functionality

### ISSUE THREAD

**Issue by StachuDotNet** [darklang/dark#4276]
UI.fs/ui.html exposes a `USER_IS_ADMIN`/`userIsAdmin` value.

That value is currently used in a few places in `client`:
- in `appsupport.js`' `FullStory.init` call - it's `devMode` for admins
- to determine if package fn upload UI should show in the left sidebar menu
- to determine if "variant" links should appear in the sidebar (the only one currently relevant, it seems, is ngrok-related?)
- `showAdminDebugger`

We're trying to get rid of the idea of an "admin" - rather, some functionality (incl. `DarkInternal::` fns) should only be available to the `dark-` canvases.

How should we go about removing `userIsAdmin` and allowing users to opt into these bits of functionality?
Specifically, `showAdminDebugger` sounds like a great thing to expose - I know I've been reaching for it.

**Comment by pbiggar** [comment]
AFAICT, all these uses are really meant to be "is the user a dark employee". Which is not so much a thing anymore, so we should look at how we allow contributors to opt in to these settings and uses.

I don't _think_ any of them relate to whether the canvas is an admin canvas.

**Comment by StachuDotNet** [comment]
Fair!

I've updated the title+description to reflect a better path forward.

I think `showAdminDebugger` could be a user setting / toggle, but I'm not sure where the UI would be.

What about the others?
- FullStory devMode
- package fn upload UI
- variant links
  I'm still pretty unclear what the variant links are for - some clarity there may help me think through this

**Comment by pbiggar** [comment]
I don't know what the variant links are either.

The others are just shortcuts so that we don't waste limited recordings, and so users aren't shown things they don't have access to. They don't seem like good candidates for toggles. But I could see someone identifying themselves as a contributor: maybe we need "contributor-mode" which gives you these options.

It could be set in settings and stored along with the other options in LocalStorage.

**Comment by StachuDotNet** [comment]
> to determine if "variant" links should appear in the sidebar 

Maybe 'variants' should all just be settings in the Contributors settings tab?

**Comment by pbiggar** [comment]
Not in the general case. A lot of these, we don't really want users to know about or use. Certainly though, a subset could be enabled.

**Comment by StachuDotNet** [comment]
This is pretty much done - the only remaining usage of `userIsAdmin` is the `FullStory.init` call in `appsupport.js`.
Should that stay as-is? If so, we can close this.

**Comment by pbiggar** [comment]
Yeah I guess it's best to leave it as is, since I don't have a better idea
