### ISSUE TITLE
Purge/delete `ops-presence`, after users are migrated to `dark-editor/presence`

### ISSUE THREAD

**Issue by StachuDotNet** [darklang/dark#4295]
Deleting is blocked by #2460, but in the meantime we can purge the code/data there.

**Comment by pbiggar** [comment]
editors often stay open for weeks, so in the greneral case, call it two weeks.

However, this feature isn't used much so I think in retrospect we could just delete it now.

**Comment by StachuDotNet** [comment]
Sounds good - I've reduced the canvas to just these 2 handlers:
![image](https://user-images.githubusercontent.com/906686/179604576-ed2ccfd5-7f5b-4ec6-9462-ede00700ed24.png)

**Comment by pbiggar** [comment]
Yeah, that's a good idea. Probably best not to return 400s or similar.

**Comment by pbiggar** [comment]
We should start dating these things. Maybe suggest a date in the comments when we could remove this canvas.

**Comment by StachuDotNet** [comment]
> We should start dating these things. Maybe suggest a date in the comments when we could remove this canvas.

Will do.
If we had more controllable CRONs, we could have just made it post a Slack message in 2 weeks :)

**Comment by StachuDotNet** [comment]
or better yet: if we had a few fns around meta-Dark-programming, we could have set up a CRON to self-destruct the canvas in 2 weeks. (just dreaming)
