### ISSUE TITLE
Consider/Implement "Presence" user setting under "Privacy" menu

### ISSUE THREAD

**Issue by StachuDotNet** [darklang/dark#4310]
We currently have a "Privacy" setting menu where we have only one setting - whether or not to record data with FullStory.
![image](https://user-images.githubusercontent.com/906686/179767852-d818bd50-0ba2-4894-aa11-a07ef807ef5c.png)

We separately have a "Presence" feature, which shows a users' presence to others on the same canvas.

Some users (incl. I!) could see this as a privacy matter - should we have this be an opt-in feature like FullStory?

**Comment by StachuDotNet** [comment]
i.e. currently watching the Presence icons could be abused as a tool for micro-management

**Comment by pbiggar** [comment]
Really don't think this is a good idea. How would it look if the code is just changing but you weren't aware of it or you couldn't see who is doing it. Think about Google docs, you need to see who's editing what you're working on.

**Comment by pbiggar** [comment]
Maybe for a better metaphor there's no anonymous pull requests on github. Are
