### ISSUE TITLE
Persisted list of registered converters (serialization)?

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#4338]
### Discussed in https://github.com/darklang/dark/discussions/4329

<div type='discussions-op-text'>

<sup>Originally posted by **StachuDotNet** July 25, 2022</sup>
After reading this comment (https://github.com/darklang/dark/pull/4323#discussion_r927194437), I thought it might be useful to be able to see a list of all registered converters, probably only useful for local development to check things like this. Maybe even a .json array saved to disk in the repo? Not sure an ideal implementation, but I reach for such a central list occasionally.

What do you think, @pbiggar?</div>

**Comment by pbiggar** [comment]
I think we did this?

**Comment by StachuDotNet** [comment]
Yeah I'd say so
