### ISSUE TITLE
Each command should be triggerable by keyboard shortcuts

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#4378]
Ideally, we'd like to be able to have every command, refactoring, and editing action (i'll refer to them all as "commands" for now) available as a keyboard shortcut, as well as via the mouse, context menu, and eventually accessible by APIs for other commands to reuse.

There are a number of challenges here. The biggest is assigning keyboard shortcuts to commands, as windows has most of the keyboard shortcuts already allocated, and users have different keyboard layouts, especially for different locales. This is why there's three separate keyboard shortcuts to bring up the context menu: every shortcut we've tried to create has had issues for some users.

To solve this we need to do the following:
- add a system of user-settable keyboard shortcuts
- ensure all existing commands are made available in the system (eg triggering function or handler execution, while not a refactoring, is a valid and useful shortcut)
- ensure new commands all go through this system
- create a good set of shortcuts for existing commands, for different keyboards layouts/OSes/etc

**Comment by pbiggar** [comment]
In addition, all of these commands should be written in dark, and users should be able to import and use their own commands too.

**Comment by StachuDotNet** [comment]
Extracted to #5237 to pick up some day
