### ISSUE TITLE
Multi-line string extends visually _above_ the let binding

### ISSUE THREAD

**Issue by StachuDotNet** [darklang/dark#4389]
![image](https://user-images.githubusercontent.com/906686/184656847-ef5c7e0c-4b1d-4962-830d-eaceb6b4c584.png)

I'm not sure the particular circumstances that cause this, but this can lead to a lot of confusion. I plan to be in Fluid code this week, so plant to take a look.

**Comment by StachuDotNet** [comment]
I took a stab at this here: #4739

**Comment by pbiggar** [comment]
Not applicable to darklang-next.
