### ISSUE TITLE
Canvas Zoom [ui][enhancement]

### ISSUE THREAD

**Issue by sanderjson** [darklang/dark#4407]
Missing a keyboard command + track pad gesture  to Zoom navigate the canvas.

**Comment by pbiggar** [comment]
A good first step here would be a description of what to see at different zoom levels. In other words, how should this differ from standard browser zoom which is already available.

**Comment by sanderjson** [comment]
- smooth, continious zoom with trackpad + key command (alt)
- centers on cursor location 
- faster navigation than pan alone (especially for larger canvases)
- alternative to snap viewing that keeps canvas positioning in context of working memory

**Comment by pbiggar** [comment]
Thanks!

**Comment by pbiggar** [comment]
Closing as it doesn't apply to darklang-next
