### ISSUE TITLE
Fluid: Can't add an additional string concatonation next to ++

### ISSUE THREAD

**Issue by StachuDotNet** [darklang/dark#4416]
![image](https://user-images.githubusercontent.com/906686/186562843-b27de4ae-ad12-4f66-9926-cb598af4656c.png)

In order to work, currently, the cursor has to be right at "foo"| ++ "bar" , not at "foo" |++ "bar"

**Comment by pbiggar** [comment]
This is a bit of a challenge. How do we know that the plus is adding another infix operation, not editing the current operator?

**Comment by StachuDotNet** [comment]
That's a good point. My expectations when hitting `+` at the following locations would be:
- `"foo" |++ "bar"` -> `"foo" +|+ "bar"`
- `"foo" +|+ "bar"` -> `"foo" ++| "bar"`

and indeed this one is confusing:
- `"foo" ++| "bar"`

`"foo" ++ __ +|+ "bar"` seems _almost_ right but also isn't what I want.

There are some ambiguous situations like this where I'd _almost_ want a tiny dialog to show up, with the 2 options in a keyboard-navigatable drop-down.

There might not be a good solution here - current behavior may actually be best.

**Comment by pbiggar** [comment]
> That's a good point. My expectations when hitting `+` at the following locations would be:
> 
> * `"foo" |++ "bar"` -> `"foo" +|+ "bar"`
> * `"foo" +|+ "bar"` -> `"foo" ++| "bar"`

This doesn't match the intuitions that we want people to have for fluid. We should only be skipping over built-in syntax, everything else should be treated as an insertion.

> 
> and indeed this one is confusing:
> 
> * `"foo" ++| "bar"`
> 
> `"foo" ++ __ +|+ "bar"` seems _almost_ right but also isn't what I want.

I think with this points to, is that we make this sort of thing a little bit rigid in the current implementation, and that we probably need new constructs (and new UI paradigms) to allow intermediate states to have a better UX. Perhaps looking at how other structured editors handle this, would be a good start.

**Comment by pbiggar** [comment]
Closing as it doesn't apply to darklang-next
