### ISSUE TITLE
Can't click on handler type in handler-creation dialog

### ISSUE THREAD

**Issue by StachuDotNet** [darklang/dark#4419]
instead, I must use my keyboard to make my selection
<img width="576" alt="Screen Shot 2022-08-24 at 10 54 51 PM" src="https://user-images.githubusercontent.com/906686/186563971-be2123f8-f86b-4e71-9663-2ad8b87c2db9.png">

**Comment by pbiggar** [comment]
Closing as it doesn't apply to darklang-next
