### ISSUE TITLE
Investigate switching to discord

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#4441]
- [x] add all channels
- [x] add long-term invite link
- [x] check permissions are ok
- [x] disable [at]channel in main channels

# pull the trigger
- [x] change slack link
- [x] send invites to all Slack members (email)
- [x] send email announcement to all users
- [x] tweet link
- [x] change links (docs, homepage footer, homepage header, readme)

# not strictly required for switching
- [ ] add rollbar notifications (via webhooks)
- [ ] add pagerduty notifications (via webhooks)
- [ ] add betteruptime notifications (via webhooks)
- [ ] add CircleCI notifications (via webhooks)
- [ ] add new darklang user notifications (via webhooks)
- [ ] apply for discovery

**Comment by pbiggar** [comment]
- [ ] disable [at]channel in main channels

**Comment by pbiggar** [comment]
- [ ] apply for discovery

**Comment by StachuDotNet** [comment]
we did this
