### ISSUE TITLE
Snap to grid [ui][enhancement]

### ISSUE THREAD

**Issue by sanderjson** [darklang/dark#4442]
User options -> snap to grid (default)

Add toggle grid mode

Shift + drag to snap to grid 

Helps align canvas elements for aesthetics and ease of processing

**Comment by StachuDotNet** [comment]
Is this the sort of experience you'd like: http://jsfiddle.net/fabricjs/S9sLu ?

**Comment by sanderjson** [comment]
Exactly! Might just be me, but I spend way to much time aligning boxes.

<img width="635" alt="image" src="https://user-images.githubusercontent.com/20689537/195485199-6d466b18-302b-4209-88aa-93d35bbc69cd.png">

**Comment by pbiggar** [comment]
Closing as it doesn't apply to darklang-next
