### ISSUE TITLE
Show structure of multi-line strings a little bit better

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#4461]
I'm playing with the design of multiline strings, trying to make it easier to see the string is multiline, and where the boundary is.

The question when evaluating these: is the space at the start of the second line more obvious?

"unstyled": Here it is unstyled:

<img width="513" alt="Screen Shot 2022-09-08 at 9 55 26 AM" src="https://user-images.githubusercontent.com/181762/189140982-15cec4f2-0906-4d37-8dac-8563b02a0819.png">

"black border": This one is an extremely rough effort, which I think shows that doing the simple and obvious thing is probably worse than doing nothing.
<img width="600" alt="Screen Shot 2022-09-08 at 8 59 41 AM" src="https://user-images.githubusercontent.com/181762/189132963-763dbcee-4c8b-4466-afeb-2cda417365d9.png">

(Note that I'm assuming the issue with the quote can be overcome)

"subtle border 1": With this one I tried to be a lot more subtle; you'd really have to squint to explicitly noticed the line, which is kind of the point
<img width="525" alt="Screen Shot 2022-09-08 at 9 07 17 AM" src="https://user-images.githubusercontent.com/181762/189132965-b71971fe-0574-4e9b-acd9-3a889008ccec.png">

"light background 1": This one adds a subtle background to the string itself
<img width="512" alt="Screen Shot 2022-09-08 at 9 09 53 AM" src="https://user-images.githubusercontent.com/181762/189132968-af8fd6f8-e07a-49fa-8ee2-f3ff43a6d957.png">

"dark background 1": This one has a subtle background as well, but while the previous background was slightly lighter than the overall background, this one is slightly darker.
<img width="504" alt="Screen Shot 2022-09-08 at 9 20 03 AM" src="https://user-images.githubusercontent.com/181762/189132974-211f96e1-0747-4bc0-b0c0-f795fa332a18.png">

"light background border 1": This one has a background and the border on the left. The presence of the border on the left makes the background less obvious
<img width="520" alt="Screen Shot 2022-09-08 at 9 11 19 AM" src="https://user-images.githubusercontent.com/181762/189132972-6d5e9678-0704-410c-9a5d-4ac98d05d40f.png">

"light background border 2": Same thing, but thinner border
<img width="520" alt="Screen Shot 2022-09-08 at 9 16 54 AM" src="https://user-images.githubusercontent.com/181762/189132973-32c6e083-bd75-463e-81ef-71bcb335ffdc.png">

**Comment by StachuDotNet** [comment]
I like the thick border of the second-last option:
![image](https://user-images.githubusercontent.com/906686/189138771-92175b51-8c0f-46b1-90df-468b457670fa.png)

The thin border is too thin for me. That may or may not be related to my colorblindness.

Can I see what that option would look like with the 'dark background' option?

**Comment by StachuDotNet** [comment]
The light background feels barely lighter to me - I probably wouldn't have noticed if you didn't point it out.
The second option (thin light border) feels like a glitch/mistake

**Comment by pbiggar** [comment]
Darker background with thicker line
<img width="512" alt="Screen Shot 2022-09-08 at 9 51 35 AM" src="https://user-images.githubusercontent.com/181762/189139928-133bec35-0f05-4e02-9cc4-3d5a13fcae65.png">

> The light background feels barely lighter to me - I probably wouldn't have noticed if you didn't point it out.
> The thin border is too thin for me. That may or may not be related to my colorblindness.

Well that's the point. I don't want you to see the border (or the background), I want you to see the space on the second line.

**Comment by pbiggar** [comment]
Thin with light background, but more subtle than above

<img width="501" alt="Screen Shot 2022-09-08 at 9 49 21 AM" src="https://user-images.githubusercontent.com/181762/189140404-742946d7-44a4-4ab9-8092-4ca77c1b017d.png">

**Comment by pbiggar** [comment]
For comparison, here it is with no extra styling

<img width="513" alt="Screen Shot 2022-09-08 at 9 55 26 AM" src="https://user-images.githubusercontent.com/181762/189140816-fc7cb7ab-87b7-4262-b4d0-0b0facd70376.png">

**Comment by pbiggar** [comment]
> > The question when evaluating these: is the space at the start of the second line more obvious?
> 
> The answer that to that question for me is 'no' for all of these - my brain interprets that formatting as "right-justified text alignment _just worked out like that_" rather than the second (and last?) line(s) being intentionally indented.
> 
> I'm not sure the point of the second line being indented, in any case? Maybe that's some pattern I'm not familiar with

It's just where the spacing ended up.

I'm going to do a different layout algorithm so that they won't be the space in this case, that there will be other cases (such as JS code for example) that will have spaces at the start of the line.

**Comment by pbiggar** [comment]
OK, for now I'll do a subtle background and move on. I might revisit something better when the layout is closer to its final state

**Comment by StachuDotNet** [comment]
Ahh ok, I was misinterpreting - I thought you _wanted_ the second line to be indented, and wasn't sure why.

Towards:
> trying to make it easier to see the string is multiline, and where the boundary is.

, I think the thicker left border does that nicely.

I think that's a general practice we could use throughout to show off where blocks of code start/end. (sometimes I have trouble tracing indentations).

---

This could be a just-me thing, but the color of the light border looks the same as a text selection - so it almost looks like you're about to type a character and affect the start of every line. Again, probably a colorblindness thing I should be able to user-setting my way out of, some day.

(by text selection, I mean: 
![image](https://user-images.githubusercontent.com/906686/189145165-eebb7a4e-18f8-4010-9aa3-a65c42bb6760.png)
)

**Comment by pbiggar** [comment]
> This could be a just-me thing, but the color of the light border looks the same as a text selection - so it almost looks like you're about to type a character and affect the start of every line. Again, probably a colorblindness thing I should be able to user-setting my way out of, some day.

Oh right, I could see that!
