### ISSUE TITLE
Tuple2 and Tuple3 stdlib functions not available with "enable tuples" flag set

### ISSUE THREAD

**Issue by StachuDotNet** [darklang/dark#4471]
https://github.com/darklang/dark/pull/4342 disabled them. We need to somehow conditionally re-enable them based on this setting.

**Comment by StachuDotNet** [comment]
I have no immediate ideas of how to handle this. @pbiggar any ideas?

**Comment by pbiggar** [comment]
I think you would undeprecate them, then use the setting when generating AutoComplete entries
