### ISSUE TITLE
DB fields configured with [UUID] type are accepting [string]

### ISSUE THREAD

**Issue by StachuDotNet** [darklang/dark#4473]
![image](https://user-images.githubusercontent.com/906686/190400871-8ce25596-43de-4e34-84d3-50bcb9556558.png)

![image](https://user-images.githubusercontent.com/906686/190400836-15a94f97-bb4e-4f98-810a-28cc5ab55557.png)

**Comment by pbiggar** [comment]
Looks like these were never checked: [ocaml](https://github.com/darklang/dark/blob/dee9a48b8b757ce99c558677b7b83ddccf5bfd6c/backend/libbackend/user_db.ml#L143) and [fsharp](https://github.com/darklang/dark/blob/dee9a48b8b757ce99c558677b7b83ddccf5bfd6c/fsharp-backend/src/LibBackend/UserDB.fs#L116)


Same with [functions](https://github.com/darklang/dark/blob/dee9a48b8b757ce99c558677b7b83ddccf5bfd6c/fsharp-backend/src/LibBackend/UserDB.fs#L116).

To solve this, we would need a new version of the type checkers, and then new versions of the DB functions to use them. (There are also a few other packs in there that would be worth removing as part of this: the "id" key hack, and type checking for functions as well)

**Comment by pbiggar** [comment]
Fixed
