### ISSUE TITLE
Reconsider what should happen when a `,` is deleted

### ISSUE THREAD

**Issue by StachuDotNet** [darklang/dark#4474]
There's a lengthy conversation here worth reading through:
https://github.com/darklang/dark/issues/4465#issuecomment-1242216916_

When we backspace over a `,` in a list expr or tuple expr/pattern, we delete the expr/pattern to the right of the `,` along with the `,`.

What _should_ we do?

It feels a bit inappropriate to delete the expr/pattern to the right of the `,`, unless that expr/pat is `___` blank.

**Comment by pbiggar** [comment]
> * jump significantly more than 1 'visual character' to the left

Do we do this? I don't think we do.

**Comment by StachuDotNet** [comment]
You're right - we don't - I was confusing myself based on our other conversation.

**Comment by pbiggar** [comment]
When we backspace over other keywords, like `let`, `match`, or `if`, we only delete them if the contents is also empty

**Comment by pbiggar** [comment]
Closing as it doesn't apply to darklang-next
