### ISSUE TITLE
Function called multiple times from single handler returning different data (missing Date::now)

### ISSUE THREAD

**Issue by sanderjson** [darklang/dark#4476]
I have one handler that calls a function multiple times. The function returns a dict, and one field is a date.

In one instance the function call the returned data does not contain this field . I have tried to reproduce in a REPL but it seems to work fine.

Please see attached images.

![image](https://user-images.githubusercontent.com/20689537/190462218-bdb89b60-8af6-4a8a-bbf0-04f711dc48ac.png)

![image](https://user-images.githubusercontent.com/20689537/190462295-38c156bb-926c-43fb-879c-750f84ef567a.png)

![image](https://user-images.githubusercontent.com/20689537/190462337-7476caba-d1c6-4eef-8a2c-5b7e3275f4d0.png)

**Comment by pbiggar** [comment]
Thanks for the report. I'm also unable to reproduce this in a Repl. Are you able to link to a canvas where this is happening?

**Comment by sanderjson** [comment]
https://darklang.com/a/sanderjson-rocketsolid-content#handler=1603708710

Probably user error. But please also notice that in the handler return the final term `routes: routes |...` is generating an error (due to the above issue) but the error is not show in the trace.

I think this may be from the list map DB::set?

**Comment by sanderjson** [comment]
Issue was resolved by forcing each call to execute again. Still having some buggy behaviour within the editor around functions and dates. Will try to isolate and open a separate issue if possible.

**Comment by pbiggar** [comment]
Thanks, appreciate it!
