### ISSUE TITLE
Placeholders are calculated by allowed functions

### ISSUE THREAD

**Issue by StachuDotNet** [darklang/dark#4484]
non-allowed functions should have the expected placeholders regardless if they are deprecated

**Comment by StachuDotNet** [comment]
I feel like the OP is phrased poorly, so I'll write it again in other words - maybe this is better.

If you load a canvas that includes now-deprecated functions, 'placeholders' are shown in the UI for each of the fn's parameters:
![image](https://user-images.githubusercontent.com/906686/191086921-c683980e-dfc0-48b3-b2d6-3ff00ca8bc37.png)

In testing #4481, we had a function in use, and its placeholders were not shown - this is because `calculateAllowedFunctionsList` deemed the function to be _unavailable_. Thus, it seems the placeholder information is being pulled from the `allowedFunctions` list, and not the full set of functions.

**Comment by pbiggar** [comment]
Closing as it doesn't apply to darklang-next
