### ISSUE TITLE
Integration tests keep timing out in CI (again)

### ISSUE THREAD

**Issue by StachuDotNet** [darklang/dark#4486]
e.g. https://app.circleci.com/pipelines/github/darklang/dark/4123/workflows/6a66d4d4-d212-4420-97de-4f621f9e5edf/jobs/42946

Usually it's not a big deal, but when it happens in `main`, you have to restart the build _from the start_, which gets annoying.

**Comment by pbiggar** [comment]
Fixed by #4534
