### ISSUE TITLE
String::toDate [feature request][good first pull request?]

### ISSUE THREAD

**Issue by sanderjson** [darklang/dark#4503]
```
let date_initial = Date::now
let date_string_from_client = date_initial
                              |>toString
let date_for_db = date_string_from_client
                  |>**String::toDatev1**
date_for_db
```

<img width="620" alt="image" src="https://user-images.githubusercontent.com/20689537/192846774-3921d2c8-275d-4ce6-9201-12a082fca4c9.png">

**Comment by pbiggar** [comment]
I can see why this is confusing! `String::toDate` was deprecated and renamed to `Date::parse`.

For conversions, we're working on the idea that the more specific type should have the conversion functions. Eg Float is more specific than int, int is more specific than string, as are dates and uuids. String is more specific than bytes, etc.

So:
- String::toFloat should become Float::parse (this would be a good first PR)
- Maybe String::toList should become String::toCharList? I'm unsure.

This is also showing me that it's valuable to show that a function is deprecated in autocomplete (as `String::toUUID` is deprecated, which might have been a hint if it was marked)

This also has me thinking again about adding aliases (if you're looking for `String::toDate`, maybe we should show you `String::toDate` which would tell you the name is `Date::parse`)

**Comment by sanderjson** [comment]
> I can see why this is confusing! String::toDate was deprecated and renamed to Date::parse.

This is fine. Happy to close on **user error**.

> For conversions, we're working on the idea that the more specific type should have the conversion functions. Eg Float is more specific than int, int is more specific than string, as are dates and uuids. String is more specific than bytes, etc.

I recommend this move to discussions.

My thoughts are that while specificity might make sense from a logical perspective this type of "hidden reasoning" is generally inaccessible to new users. That is not to say that business logic should be twisted to fit a "users amateur understanding". I believe in the opposite, that the issue here is with education — _teaching new users to think_ like the 'pros' in a fun, engaging manner. Let me know if you have any developer advocate positions opening 😄

> String::toFloat should become Float::parse (this would be a good first PR)

New issue _"Rename all String::toX standard library calls to X::parse"_ ?

> This also has me thinking again about adding aliases (if you're looking for String::toDate, maybe we should show you String::toDate which would tell you the name is Date::parse)

I have not looked into the search implementation but it might be an easy fix with an alias for string~parse? Thinking aloud here...there is likely already a way to capture user search canvas search and "plow the cow paths" and make great reference content?

**Comment by pbiggar** [comment]
> New issue _"Rename all String::toX standard library calls to X::parse"_ ?

Not all of them, I think just this `String::toFloat` - the others have been done.
