### ISSUE TITLE
Changing code makes broken traces work again

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#4506]
When a request comes in that causes a problem, let's say a 500, we'd like to see that. If that trace is captured, the dev will see the trace and fix it. By fixing it, all the evidence is gone. The 500 in the trace was never recorded, it was generated from analysis of the inputs, and the same inputs now give a different result.

To solve this, we'd like to have some sort of "original result" concept. This matters most as part of building an exception tracking framework.

**Comment by StachuDotNet** [comment]
Closing; only really applicable to old editor.
