### ISSUE TITLE
New design for the documentation box

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#4508]
The current documentation box looks like this:

<img width="486" alt="Screen Shot 2022-09-29 at 12 55 02 PM" src="https://user-images.githubusercontent.com/181762/193092249-08deec51-ecc0-4ef9-8f36-f84aa5a3ad44.png">

In context:

<img width="417" alt="Screen Shot 2022-09-29 at 1 00 58 PM" src="https://user-images.githubusercontent.com/181762/193111740-8ff70458-f0a1-4161-987b-50fefd55065c.png">

Basically, we just jam text in there, and we can probably do better.

## type errors 

- [ ] Type errors don't display when showing the docs

<img width="416" alt="Screen Shot 2022-09-29 at 2 31 35 PM" src="https://user-images.githubusercontent.com/181762/193114188-62acacaa-7ccb-4751-965f-948799ec6139.png">

(only when showing due to autocomplete)
<img width="417" alt="Screen Shot 2022-09-29 at 1 00 58 PM" src="https://user-images.githubusercontent.com/181762/193114187-fb36168d-9442-41ec-be54-f09f9b49bb11.png">

- [ ] Type errors are verbose and not well aligned

<img width="417" alt="Screen Shot 2022-09-29 at 1 00 58 PM" src="https://user-images.githubusercontent.com/181762/193114187-fb36168d-9442-41ec-be54-f09f9b49bb11.png">

- [ ] Parameters only show when the argument is highlighted

<img width="416" alt="Screen Shot 2022-09-29 at 2 31 35 PM" src="https://user-images.githubusercontent.com/181762/193114441-d4bd6f24-8683-4515-8121-347f11788778.png">

vs

<img width="427" alt="Screen Shot 2022-09-29 at 2 33 08 PM" src="https://user-images.githubusercontent.com/181762/193114480-e554489f-38a8-4fe6-94e8-0db1dcdfb9c1.png">

- [ ] parameters dont have their description included

Deprecated doc 

- [ ] Deprecated is ugly

<img width="481" alt="Screen Shot 2022-09-22 at 4 23 50 PM" src="https://user-images.githubusercontent.com/181762/193114828-9a2fbcb6-fcff-47f2-abdb-57147d593ac5.png">

## Errorrail doc

- [ ] The errorRail doc is verbose and dominates

Also #4507 applies here

**Comment by pbiggar** [comment]
Here's some figma designs


## Normal
<img width="338" alt="Default" src="https://user-images.githubusercontent.com/181762/193118758-a3520b82-4ba9-43ea-9b3d-a17f34414de5.png">


## Deprecated

First attempt 
<img width="338" alt="Inline Deprecated" src="https://user-images.githubusercontent.com/181762/193118684-55824fcd-7b5e-4309-b50f-cab0fcf3ee10.png">

2nd draft
<img width="381" alt="Deprecated" src="https://user-images.githubusercontent.com/181762/193118701-33a0d71c-2fa7-4a87-bde9-df3384d4a05e.png">


## Type error

First draft
<img width="338" alt="Inline error" src="https://user-images.githubusercontent.com/181762/193118841-0578dd38-fbff-4966-bc1b-079bba97a1d8.png">

2nd draft: Attempt at inline
<img width="338" alt="Inline error 2" src="https://user-images.githubusercontent.com/181762/193118880-bb7671e5-639a-402a-8dd5-273afee29020.png">

3rd draft:
<img width="617" alt="Out of line error" src="https://user-images.githubusercontent.com/181762/193118882-58b850e7-108a-4868-94bf-0d9ea8122012.png">

**Comment by pbiggar** [comment]
## On errorrail tooltip

<img width="338" alt="Default (1)" src="https://user-images.githubusercontent.com/181762/193120821-b371b2e5-8aee-4c8a-8345-2ebb34eba026.png">

**Comment by sanderjson** [comment]
From a universal design and accessibility perspective I recommend to not only use colour as a signal. The design should be a working solution in greyscale and then _enhanced_ with colour. 

I believe the lowest contrast (worst offender) is in `2nd draft: Attempt at inline` where both the green and red text might be difficult to read on that light pink background.

**Comment by pbiggar** [comment]
Agreed, and thanks for the greyscale suggestion! These mockups were really about the layout - I just picked some colors randomly but they weren't intended to be final. Will try doing it greyscale and see what happens.

**Comment by pbiggar** [comment]
Closing as it doesn't apply to darklang-next
