### ISSUE TITLE
String match patterns are not wrapped in Fluid tokenization

### ISSUE THREAD

**Issue by StachuDotNet** [darklang/dark#4514]
String Expressions wrap during tokenization, but their match pattern equivalents do not, allowing `match` expressions to end up like this:

![image](https://user-images.githubusercontent.com/906686/193916208-59c8b4e7-a461-4995-a5e0-afc33951f0b0.png)

This is rare, but will be good for us to tackle at some point.

**Comment by pbiggar** [comment]
Closing as it doesn't apply to darklang-next
