### ISSUE TITLE
Implement match pattern 'partials'

### ISSUE THREAD

**Issue by StachuDotNet** [darklang/dark#4515]
We've had some relevant discussion in these threads:
- https://github.com/darklang/dark/pull/4513#issuecomment-1267574217
- https://github.com/darklang/dark/issues/4494
- https://github.com/darklang/dark/issues/4493
- https://github.com/darklang/dark/issues/4499

I haven't thought this through, but it's something Paul and I have both reached for recently.
It impacts the language (ProgramTypes), ~interpreter,~ and many scenarios within Fluid editing incl. reconstruction.

Feel free to move to a Discussion if you suspect this might take some back-and-forth. I think a timeboxed sketch impl. could raise most of the important questions here quickly; maybe I'll circle to that soon after my current tasks.

**Comment by pbiggar** [comment]
I don't think it will affect the interpreter, as partials will be removed before getting there (I would expect to not have partials in runtime types)

**Comment by pbiggar** [comment]
Closing as it doesn't apply to darklang-next
