### ISSUE TITLE
A match should always have at least one pattern/expr

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#4529]
Right now they can have zero which looks weird, and probably breaks some stuff.

Similar to how we implement pipes using two expressions before a list of the rest, matches should have a single required pattern/expr.

**Comment by StachuDotNet** [comment]
Great. I've removed a few of these scenarios but will be happy to resolve the remaining ones soon.

**Comment by StachuDotNet** [comment]
one option, which may be annoying: make illegal states unrepresentable.

update
`| EMatch of id * Expr * List<Pattern * Expr>`
to 
`type MatchCase = Pattern * Expr
`| EMatch of id * Expr * MatchCase * List<MatchCase>`

**Comment by pbiggar** [comment]
Yeah, this is what I thought as well.

**Comment by pbiggar** [comment]
We decided to allow this to support users typing code which is invalid but on a journey to being valid.
