### ISSUE TITLE
Experience report from debugging DB load

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#4549]
- [ ] User doesn't appear when pausing worker
- [ ] Queue count does number does not update
- [ ] Crons don't have traces? At least, not one trace
- [ ] Don't know users' discord names
- [ ] One user can hog the queue
- [ ] Lots of storing function storing function arguments/results when users write their own functions
- [ ] can't go "back" from fn
- [ ] can't see how many items are in the DB

**Comment by StachuDotNet** [comment]
most of this is irrelevant to dark-next, at least in its current form
