### ISSUE TITLE
A Feedback button in the platform should point to github discussions

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#4558]
Let's add a feedback button somewhere

### Discussed in https://github.com/darklang/dark/discussions/4553

<div type='discussions-op-text'>

<sup>Originally posted by **jtwaleson** October 24, 2022</sup>
Right now I had to ask on Discord where to post feedback. Which is here apparently :) It would be great if there was a "feedback" button in the product.</div>

**Comment by OceanOak** [comment]
**Brainstorming some ideas for the feedback button**

### 1. Add the feedback button to the dropdown menu
![dropdown menu (1)](https://user-images.githubusercontent.com/87861924/211222554-7554060e-4da7-42dd-b2bf-097b52e6b1ac.png)

### 2. Add the feedback button to the sidebar
![feedback-sidebar](https://user-images.githubusercontent.com/87861924/211222838-48ad5246-65e1-4a2f-a682-06428fd3a57d.png)

### 3. New menu
![bottom-menu-close](https://user-images.githubusercontent.com/87861924/211222760-ef1fa464-c9a6-470f-a1d0-e8c60fbd0aaf.png)
![bottom-menu-open](https://user-images.githubusercontent.com/87861924/211222780-e127f997-90de-45e2-8c9f-e36b905d0d03.png)
![bottom-menu-hover (1)](https://user-images.githubusercontent.com/87861924/211222786-fb604b7e-31e4-4d32-aa18-dc2b74e2b99d.png)

**Comment by pbiggar** [comment]
I think going with 1 seems right to me.

2 looks good but I worry it splits our users' attention: you can now click on special things at the bottom left, bottom-right, or top-right - that's a lot.

3 looks good but I don't think feedback is important enough to go here. Also, the icon makes it look like you're going to message us - you might not click it if you dont want to, and you might be disappointed when you do click it and find we've dumped you in a forum instead of listening to you message.

With 1, I like the 4th one, separated into sections. It seems the sections are:
- user stuff
- docs
- company stuff

I think this highlights that "Share Dark" is out of place. We could move it to the bottom or remove it entirely.
