### ISSUE TITLE
Make Integration tests easier to run locally

### ISSUE THREAD

**Issue by StachuDotNet** [darklang/dark#4611]
The last time I tried to run integration tests within the container, it failed - I forget how.

So, I instead run the integration tests outside of the container, "locally."

Doing this involves a 2-step dance:
- follow the instructions at the top of `integration-tests/run.sh` to set up env vars for the execution
  (usually, I `cat integration-tests/run.sh` and then copy the command from there)
- comment out the 3 lines of `run.sh` that reference the `PUBLISHED` variable

This is annoying and unobvious, so we should remove these hurdles.

**Comment by pbiggar** [comment]
Closing as it doesn't apply to darklang-next
