### ISSUE TITLE
Support "local" functions in the Editor

### ISSUE THREAD

**Issue by StachuDotNet** [darklang/dark#4612]
It's often useful to define and then use a function 'inline':
```fsharp
let fn = \val -> ...
let items = List::filter original fn
```

You can currently define a `Block` and use it like this, but the editor only allows you to use it in functions that explicitly request a `Block` such as `List::map` (at least, as far as I can tell). For example, you can't currently do the following:
```fsharp
let increment = \i -> i + 1
let ten = increment 9
```
The new version of the language (in the backend) currently supports this, but the Editor does not.

TODOs:
- [ ] design/discuss an interaction model
- [ ] update Fluid to support this

**Comment by StachuDotNet** [comment]
In the meantime, one can define an `applyBlock` fn like this:
![image](https://user-images.githubusercontent.com/906686/203861449-d9fecea7-fa7e-4298-a56d-e6e4c12eb078.png)

and then use it like
```fsharp
let increment = \i -> i + 1
applyFn increment 9
```

**Comment by pbiggar** [comment]
> The new version of the language (in the backend) currently supports this, but the Editor does not.

I misunderstood the issue, apologies. I thought we were talking about calling higher-order functions with stdlib functions. Anyway, this isn't currently supported in the language. I guess it should probably be supported? I'd prefer folks used real functions in general but it's undeniable that local functions have their place.

So if we want this we'll need a semantics defined as well the interaction model (basically, a definition of what the AST would be, and what the interpreter would do. This is usually pretty simple, though we'll need to account for incompletes, errorrails and derrors).

Note that `9 |> increment` should currently work.

**Comment by StachuDotNet** [comment]
needs to be reassessed for modern day; folded into #5239, will reference this doc when it comes up
