### ISSUE TITLE
Don't require user to scroll many times to 'copy' a trace value

### ISSUE THREAD

**Issue by StachuDotNet** [darklang/dark#4615]
For large trace values, it can be really annoying to 'copy' the value for external inspection:
![Peek 2022-11-28 10-05](https://user-images.githubusercontent.com/906686/204311364-51224d5a-cf2f-4564-9d82-6a65f9a8bc88.gif)

We could resolve this by limiting the height of the trace value display to the height of the relevant code body, including a scrollbar to handle the overflow.

**Comment by pbiggar** [comment]
Closing as it doesn't apply to darklang-next
