### ISSUE TITLE
Fix the inability to reorder User Function parameters

### ISSUE THREAD

**Issue by StachuDotNet** [darklang/dark#4616]
We used to be able to click and drag Function parameters to reorder them.
Attempting this now results in an "Invalid invocation" javascript error being displayed, along with a Rollbar.

![Peek 2022-11-28 16-44](https://user-images.githubusercontent.com/906686/204387507-ce80954f-30fc-4d41-887a-61afc692e66b.gif)

**Comment by pbiggar** [comment]
Thanks! That must be the changes I made to rescript-tea in the last release.

**Comment by pbiggar** [comment]
Closing as it doesn't apply to darklang-next
