### ISSUE TITLE
Lack of integer division is confusing

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#4627]
In discord, @matthiasportzel asked about integer division. We do actually have integer division but he didn't notice it and used float division instead (with truncation, etc).

We used to have a warning in the error message, it was removed to speed along the migration. Instead, let's add it back in the editor. Possibly we want to give namesIDs or similar to error messages and then in the editor we can configure their display.

We also shouldn't have `/` be just a synonym for `Float::divide` - it should really be `Float::divide` in the AST with a "display" of `/`. This way, we could have `/` be a synonym for `Int::divide` as well.

**Comment by StachuDotNet** [comment]
folded into #5239
