### ISSUE TITLE
"Unfortunately we only support Dark on desktop Chrome right now" displayed on Darklang-1.7.0.AppImage

### ISSUE THREAD

**Issue by nodakai** [darklang/dark#4637]
![dark-appimage-1 7 0](https://user-images.githubusercontent.com/90726/206727353-15305e4d-17c2-4ee8-ac71-c4b86b46b3d6.png)

Let me know if there's any debug logs I can share with you

**Comment by StachuDotNet** [comment]
Thank you for reporting - looking into this now.
