### ISSUE TITLE
Re-enable flaky integration tests

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#4661]
@StachuDotNet is working on making the integration tests less flaky. For now I'm going to disable the bad integration test, which is rename_db_fields. We should re-enable once it's less flaky.

**Comment by StachuDotNet** [comment]
I think it's worth disabling both `rename_db_` tests - I've seen them both flake.

**Comment by pbiggar** [comment]
Closing as it doesn't apply to darklang-next
