### ISSUE TITLE
Outbound IP address

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#4675]
Users occasionally ask what IP address Httpclient requests made from within a darklang program come from - they currently come from a changing set of ephemeral IP addresses. It would be useful to have a single known IP addresses so that users can config firewall rules.

We can achieve this fairly easily with Cloud NAT.

In the future, it may be useful to allow individual canvases (or groups of canvases or sub-canvas regions) to have a particular IP address for requests to come from. This would presumably be a paid feature as it's mostly useful for companies (and need IP addresses, which cost money), but it's probably not too hard to implement.

**Comment by StachuDotNet** [comment]
folding this into a larger issue to be reassessed later
