### ISSUE TITLE
Add a Streaming mode

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#4685]
I've found myself a little reluctant to stream in dark, as user data might be present in traces.

Perhaps we could have a streaming mode, where live values, trace inputs and trace results are displayed in a popped out window which you can choose to not stream (or even just a docked place on the screen which can be blurred)

**Comment by StachuDotNet** [comment]
Maybe working on this could overlap with efforts towards 'public' canvases.
e.g. with query param `?view=public`, a non-public canvas can share the same experience as a 'public' canvas

**Comment by StachuDotNet** [comment]
I'm sure this will come again in dark-next, but killing for now until it does. Probably, the relevant work would be almost totally in the language server and extension.
