### ISSUE TITLE
Show the package name less

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#4710]
In recent PRs like #4706, the width of the package names have overflowed or made the autocomplete excessively wide. I'd suggest that to handle that we:

- in the doc box, put the package name (eg `dark/asana`) on its own line and remove it from the rest of the name (eg `Asana::getIssue_v0`)
- in the autocomplete, just don't show the package name at all (eg just show the `Asana::getIssue_v0` portion.

**Comment by StachuDotNet** [comment]
Maybe we have a package icon just to the left of `Asana::` - like :package:

**Comment by OceanOak** [comment]
These are just some initial ideas. The spacing is a little off, and we're thinking about removing the return type now that we have a signature.
<img width="1010" alt="Frame 4 (1)" src="https://user-images.githubusercontent.com/87861924/212901654-7faa8b6d-2554-4ea5-8f0f-15053bd867ab.png">
<img width="1010" alt="Frame 2" src="https://user-images.githubusercontent.com/87861924/212901207-7c2b5826-68a4-4e3f-a590-2ef65e04f697.png">
<img width="1010" alt="Frame 3" src="https://user-images.githubusercontent.com/87861924/212901279-392281fa-8590-4a60-ade9-cad729bc578c.png">

**Comment by StachuDotNet** [comment]
Those screenshots look great! Will be nice to have the listing more concise like this.
Can you describe the difference between the 2nd and 3rd?
Also - now that I see the package icon in the listings, I'm not sure how I feel about it - feels a bit redundant/noisy, but maybe I'm looking at it too hard.

**Comment by pbiggar** [comment]
This looks great. Thoughts:

- perhaps put the package name to the right of the function name (that is, the function name is the most important thing, but the package name is useful metadata, so it gets reasonably high billing). So like the 2nd image but:

```
Asana::createTask       📦 dark/asana       Not Deprecated
```

I agree the package icon (1st image) might be overdoing it but also maybe it is useful. How about we try it for now and we can remove it if it's annoying. Ideally that would actually be the icon from the package (eg a stripe logo, an asana logo, etc), but small steps for now. can you add the color back?

**Comment by OceanOak** [comment]
> Can you describe the difference between the 2nd and 3rd? I see the third lists the "📦 `dark/asana`" which I really like (and is probably a better approach to repeating the icon like I previously suggested), but I'm not sure what's different with the types above it.
 
There isn't much difference appart from the placement of the package name (on the top or on the bottom of the doc box)

> can you add the color back?

I am not sure what color are referring to, could you please elaborate?

**Comment by pbiggar** [comment]
> > perhaps put the package name to the right of the function name (that is, the function name is the most important thing, but the package name is useful metadata, so it gets reasonably high billing).
> 
> It would look something like:
> 
> 1. AC
>    ![image](https://user-images.githubusercontent.com/87861924/214562455-af4336a4-cdff-402d-8061-2f6fc6ba696c.png)

I forgot about the spacing situation. I guess let's just do what you think is best here rather than me backseat drive this.


> > can you add the color back?
> 
> I am not sure what color are you referring to, could you please elaborate?

Ah, I thought this was the 📦 emoji, but in grey, so I was suggesting to no longer make it gray. But I guess that's not right?

**Comment by OceanOak** [comment]
> Ah, I thought this was the 📦 emoji, but in grey, so I was suggesting to no longer make it gray. But I guess that's not right?

It is an icon, I've tried using the emoji but it turned into symbols for some reason even though we have the UTF-8 character encoding method added. 
A possible reason is the font-family. I can try to make it work if we want an emoji instead of an icon.

Alternatively we can use a color for the icon. Something like:

![image](https://user-images.githubusercontent.com/87861924/214597201-ae515526-1ab0-459b-9de0-20d68f56b653.png)

**Comment by pbiggar** [comment]
That works too!

**Comment by pbiggar** [comment]
Closing as it doesn't apply to darklang-next
