### ISSUE TITLE
Rate-limit Pusher.com pushes

### ISSUE THREAD

**Issue by StachuDotNet** [darklang/dark#4712]
Our pusher.com account has a daily quota of "pushes" we can perform each day.

If something goes awry, (and rarely under normal conditions,) it's possible for one canvas to generate _many_ pusher.com pushes.

For example, if many new traces come in for some http handler, many NewTrace messages will be pushed out.

We could prevent quota-exhaustion by rate-limiting how many pushes a canvas may make in a day.

**Comment by pbiggar** [comment]
I think we could similarly look at not-storing traces when they're occurring frequently. Today's requests came in at 500 req/s for 5 hours, which our backend handled with ease but which created around 9m unnecessary DB records (which will be GCed in time).

So perhaps the thing to do is rate limit trace storage (which would presumably include not sending a NewTrace message).
