### ISSUE TITLE
Revert pusher.com account upgrade?

### ISSUE THREAD

**Issue by StachuDotNet** [darklang/dark#4715]
Yesterday, we upgraded our account because we met our daily usage limit.

Can/should we switch our Pusher.com plan back tomorrow?
It seems safe to (there's a daily quota, not a monthly quota), and saves a bit of $.

Besides, the constraint is nice so we're encouraged to throttle the pushes
(maybe by way of throttling how often we record traces, as you mentioned)

**Comment by pbiggar** [comment]
I downgraded. We'll be on the old plan until the end of the billing period.
