### ISSUE TITLE
When switching user accounts, you end up on a "not authorized" page

### ISSUE THREAD

**Issue by StachuDotNet** [darklang/dark#4717]
Error report from a user:
>  if you log out, then log in to another dark user, you get redirected to the original canvas url (of the user you logged out of) and go to a 'not authorized

**Comment by pbiggar** [comment]
I'm not following what happened. Can you share an example?

**Comment by StachuDotNet** [comment]
- Login as UserA. (Url is /a/UserA)
- log out
- log in as UserB

You'd expect to land in your main UserB Canvas, but instead the URL of /a/UserA is retained, and you get an Unauthorized message as you don't have access

**Comment by pbiggar** [comment]
Closing as it doesn't apply to darklang-next
