### ISSUE TITLE
Highlight current live value where it occurs in the return value

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#4723]
We could highlight the current live value in the return value if it exists (eg, the string `"this string"` could be highlighted if it occurs in a record being returned, such as 

```
{ 
  x: "this string"
}
```

**Comment by StachuDotNet** [comment]
I don't think I understand - do you mean the following?

```
let a = "this string"
...
{ x: a }
```
(the result of this would be `{ x: "this string" }`, and show below the code as the return value)

Then, if you have your cursor somewhere within `"this string"` in the actual code, "this string" is highlighted within the return value.

**Comment by pbiggar** [comment]
yes, right!

**Comment by pbiggar** [comment]
Closing as it doesn't apply to darklang-next
