### ISSUE TITLE
Unlocked user DBs can have fields uneditable if types previously were invalid

### ISSUE THREAD

**Issue by StachuDotNet** [darklang/dark#4724]
![bug demonstration](https://user-images.githubusercontent.com/906686/214373218-c5e76aaf-4cab-4da3-b0b2-b8d52d6e46c6.gif)

Repro:
- create new user DB
- add a new field of name `aaa` and type `aaa` (anything invalid)
- remove the field
You should be able to add new fields at this point, but you can't.

**Comment by OceanOak** [comment]
Would adding something like this be a good solution?
![image](https://user-images.githubusercontent.com/87861924/215276599-135b8fea-9e09-4982-baf1-34d598fb8020.png)
Similar to what we have for function parameters 
![image](https://user-images.githubusercontent.com/87861924/215276660-5f6daebb-27b0-42c7-9783-8816881e864d.png)

Or is it better to find a way to fix it without any new additions?

**Comment by pbiggar** [comment]
We want to redo this the DB to use fluid, so I'm not sure it's worth looking at right now.

**Comment by pbiggar** [comment]
Closing as it doesn't apply to darklang-next
