### ISSUE TITLE
Fix DMARC on outgoing emails from mailchimp

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#4725]
Emails sent via mailchimp sometimes return with DMARC warnings, making us seem unprofessional, and lowering deliverability. Let's figure out how to fix it.

**Comment by pbiggar** [comment]
I think I fixed this, using the mailchimp UI at https://us16.admin.mailchimp.com/domains/ and this tutorial https://www.youtube.com/watch?v=beUEa6Ft3f4.

**Comment by StachuDotNet** [comment]
merged into #5246
