### ISSUE TITLE
E: Unable to locate package terraform on arm64 (MacBook M1 Pro)

### ISSUE THREAD

**Issue by ditansu** [darklang/dark#4746]
When I try setup a dev environment on my laptop I get error "E: Unable to locate package terraform". 
It seems to have no way to install terraform from a package, only from binary.
Proof: 
https://developer.hashicorp.com/terraform/cli/install/apt#supported-architectures

_There are no official packages available for other architectures, such as arm64. If you wish to use Terraform on a non-amd64 system, [download a normal release .zip file](https://developer.hashicorp.com/terraform/downloads) instead._

The possible workaround:

1. comment this line https://github.com/darklang/dark/blob/main/Dockerfile#L119
2. install from binary, add this snippet after this line https://github.com/darklang/dark/blob/main/Dockerfile#L154
```Dockerfile 
# Terraform install  for AMR64 
RUN wget -c https://releases.hashicorp.com/terraform/1.3.9/terraform_1.3.9_linux_arm.zip && \
    unzip terraform_1.3.9_linux_arm.zip && \
    mv ./terraform /usr/bin/terraform && \
    rm ./terraform_1.3.9_linux_arm.zip
```

**Comment by pbiggar** [comment]
Thanks!

We have a little script that downloads tar.gz files, based on architecture, and checks their checksums. It could easily be adapted to .zip files, which would make it appropriate for solving this (needed to check the architecture).

https://github.com/darklang/dark/blob/main/Dockerfile#L221

**Comment by ditansu** [comment]
Cool. I try to do a PR for that.

**Comment by StachuDotNet** [comment]
Closing this - the issue has been resolved in the `light` repo, which should be merged in here soon.
