### ISSUE TITLE
Prevent conflicts of type names

### ISSUE THREAD

**Issue by StachuDotNet** [darklang/dark#4783]
e.g. users shouldn't be allowed to define a `List` type - right?

In addition to prevent conflicts of existing types, it might be worth considering preventing conflicts with some set of "reserved" types (e.g. `Set`)

**Comment by pbiggar** [comment]
I think this is handled - users can't have Builtin.List?

**Comment by StachuDotNet** [comment]
I don't think there's anything preventing a user from defining a `Builtin` module in userspace currently, and/or a `List` module within that. It's true that the current NameResolver will use anything in _the_ builtins before trying to use anything in a user-defined Builtin module.

The call-out I intended with this issue is that we should maybe warn/error at definition of such a module? I think this is part of a larger "what do we do with keywords and reserved names?" story

**Comment by StachuDotNet** [comment]
folded into #5259
