### ISSUE TITLE
Cleanup items related to string interpolation

### ISSUE THREAD

**Issue by OceanOak** [darklang/dark#4795]
Cleanup items related to string interpolation
https://github.com/darklang/dark/blob/main/backend/tests/FuzzTests/ExecutePureFunctions.FuzzTests.fs#L59
https://github.com/darklang/dark/blob/main/backend/tests/FuzzTests/ExecutePureFunctions.FuzzTests.fs#L64
https://github.com/darklang/dark/blob/main/backend/tests/FuzzTests/ExecutePureFunctions.FuzzTests.fs#L151
https://github.com/darklang/dark/blob/main/backend/tests/FuzzTests/ExecutionRegression.FuzzTests.fs#L65
https://github.com/darklang/dark/blob/main/backend/tests/FuzzTests/Generators.fs#L246
https://github.com/darklang/dark/blob/main/backend/tests/FuzzTests/Generators.fs#L496
https://github.com/darklang/dark/blob/main/backend/tests/Tests/Execution.Tests.fs#L172
https://github.com/darklang/dark/blob/main/backend/tests/Tests/Execution.Tests.fs#L275
https://github.com/darklang/dark/blob/main/backend/tests/Tests/Execution.Tests.fs#L279
https://github.com/darklang/dark/blob/main/backend/tests/Tests/Execution.Tests.fs#L329
https://github.com/darklang/dark/blob/main/backend/tests/Tests/Execution.Tests.fs#L351
https://github.com/darklang/dark/blob/main/backend/tests/Tests/Serialization.TestValues.fs#L74
https://github.com/darklang/dark/blob/main/backend/tests/Tests/Serialization.TestValues.fs#L112
https://github.com/darklang/dark/blob/main/backend/tests/TestUtils/RTShortcuts.fs#L45
https://github.com/darklang/dark/blob/main/backend/tests/TestUtils/TestUtils.fs#L569

**Comment by pbiggar** [comment]
I never followed why these were marked as CLEANUP? Is there CLEANUP to do here?

**Comment by StachuDotNet** [comment]
I think that's my fault - we were going through string interpolation together at some point, and my temp goal was to just get to a point where we compile, so I recommended she add CLEANUP in a few places, and circle back to them.

FYI ocean, feel free to disregard everything in FuzzTests - we'll just delete that full project.

**Comment by OceanOak** [comment]
Should we close this issue?

**Comment by OceanOak** [comment]
Fixed in #4796 and #4800
