### ISSUE TITLE
DB UI gets stuck without add field name on unlocked state

### ISSUE THREAD

**Issue by sanderjson** [darklang/dark#4906]
Happens sometimes after DB::DeleteAll, workaround is to delete DB then recreate (type out all fields again)

<img width="72" alt="image" src="https://github.com/darklang/dark/assets/20689537/13f533ef-738d-43d6-bfb4-b108acc79797">

Also, delete is no longer available.

<img width="362" alt="image" src="https://github.com/darklang/dark/assets/20689537/9cf65bb1-dd0b-4cd6-a520-f29a5888d7a8">

**Comment by pbiggar** [comment]
Thanks for the report. Going to close this since we're not working on this editor anymore and don't plan to bring it back. We're keeping issues that still apply on the new version though!
