### ISSUE TITLE
Feedback parallel compiler flags

### ISSUE THREAD

**Issue by nojaf** [darklang/dark#5113]
Hi there,

I noticed you have added

https://github.com/darklang/dark/blob/abe22c6b5a8c871bb39a33c3e8d9f27f95c522e6/backend/Directory.Build.props#L18

Was (or is) everything still working for you? Did you encounter any problems?
Did you notice any improvements?

**Comment by StachuDotNet** [comment]
Hi there. Things have been working OK for me since @pbiggar made this adjustment. I haven't _noticed_ any change in compilation time - but that could be that I just haven't been paying attention to that metric lately.

**Comment by pbiggar** [comment]
I think these flags didn't take effect for us - I believe we accidentally overwrote the setting by setting OtherFlags in every fsproj. I found this out recently when trying to add warnings in https://github.com/darklang/dark/pull/5112.

So now that it's been enabled by https://github.com/darklang/dark/pull/5112, I checked before and after:

Debug, clean build:
Before (no optimization): 35s
After (with parallelization flags): 34s

Release, clean build:
Before (no parallelization flags): 95s
After (with parallelization flags): 95s

So I'm not seeing a difference.

**Comment by pbiggar** [comment]
Yes, I reran it with --verbosity detailed, looks like they are present:

<details>
<code>
[m[30;1m       Using "Fsc" task from assembly "/usr/share/dotnet/sdk/7.0.400/FSharp/FSharp.Build.dll".
[m[36m       Task "Fsc"
[m[30;1m         /usr/share/dotnet/dotnet "/usr/share/dotnet/sdk/7.0.400/FSharp/fsc.dll" -o:/home/dark/app/backend/Build/obj/Prelude/Debug/net7.0/Prelude.dll
-g
--debug:portable
--langversion:7.0
--noframework
--define:TRACE
--define:DEBUG
--define:NET
--define:NET7_0
--define:NETCOREAPP
--define:NET5_0_OR_GREATER
--define:NET6_0_OR_GREATER
--define:NET7_0_OR_GREATER
--define:NETCOREAPP1_0_OR_GREATER
--define:NETCOREAPP1_1_OR_GREATER
--define:NETCOREAPP2_0_OR_GREATER
--define:NETCOREAPP2_1_OR_GREATER
--define:NETCOREAPP2_2_OR_GREATER
--define:NETCOREAPP3_0_OR_GREATER
--define:NETCOREAPP3_1_OR_GREATER
--optimize-
--tailcalls-
-r:/home/dark/.nuget/packages/faithlife.utility/0.12.2/lib/net6.0/Faithlife.Utility.dll
-r:/home/dark/.nuget/packages/fsharp.control.asyncseq/3.2.0/lib/netstandard2.1/FSharp.Control.AsyncSeq.dll
-r:/home/dark/.nuget/packages/fsharp.core/7.0.300/lib/netstandard2.1/FSharp.Core.dll
-r:/home/dark/.nuget/packages/fsharp.systemtextjson/1.1.23/lib/netstandard2.0/FSharp.SystemTextJson.dll
-r:/home/dark/.nuget/packages/fsharpplus/1.4.1/lib/net6.0/FSharpPlus.dll
-r:/home/dark/.nuget/packages/fsharpx.async/1.14.1/lib/netstandard2.0/FSharpx.Async.dll
-r:/home/dark/.nuget/packages/fsharpx.collections/3.0.1/lib/netstandard2.0/FSharpx.Collections.dll
-r:/home/dark/.nuget/packages/fsharpx.extras/3.1.0/lib/netstandard2.0/FSharpx.Extras.dll
-r:/home/dark/.nuget/packages/microsoft.bcl.asyncinterfaces/7.0.0/lib/netstandard2.1/Microsoft.Bcl.AsyncInterfaces.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/Microsoft.CSharp.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/Microsoft.VisualBasic.Core.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/Microsoft.VisualBasic.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/Microsoft.Win32.Primitives.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/Microsoft.Win32.Registry.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/mscorlib.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/netstandard.dll
-r:/home/dark/.nuget/packages/nodatime/3.1.9/lib/net6.0/NodaTime.dll
-r:/home/dark/.nuget/packages/nodatime.serialization.systemtextjson/1.0.0/lib/netstandard2.0/NodaTime.Serialization.SystemTextJson.dll
-r:/home/dark/.nuget/packages/ply/0.3.1/lib/netstandard2.0/Ply.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.AppContext.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Buffers.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Collections.Concurrent.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Collections.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Collections.Immutable.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Collections.NonGeneric.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Collections.Specialized.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.ComponentModel.Annotations.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.ComponentModel.DataAnnotations.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.ComponentModel.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.ComponentModel.EventBasedAsync.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.ComponentModel.Primitives.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.ComponentModel.TypeConverter.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Configuration.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Console.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Core.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Data.Common.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Data.DataSetExtensions.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Data.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Diagnostics.Contracts.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Diagnostics.Debug.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Diagnostics.DiagnosticSource.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Diagnostics.FileVersionInfo.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Diagnostics.Process.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Diagnostics.StackTrace.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Diagnostics.TextWriterTraceListener.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Diagnostics.Tools.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Diagnostics.TraceSource.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Diagnostics.Tracing.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Drawing.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Drawing.Primitives.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Dynamic.Runtime.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Formats.Asn1.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Formats.Tar.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Globalization.Calendars.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Globalization.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Globalization.Extensions.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.IO.Compression.Brotli.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.IO.Compression.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.IO.Compression.FileSystem.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.IO.Compression.ZipFile.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.IO.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.IO.FileSystem.AccessControl.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.IO.FileSystem.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.IO.FileSystem.DriveInfo.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.IO.FileSystem.Primitives.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.IO.FileSystem.Watcher.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.IO.IsolatedStorage.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.IO.MemoryMappedFiles.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.IO.Pipes.AccessControl.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.IO.Pipes.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.IO.UnmanagedMemoryStream.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Linq.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Linq.Expressions.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Linq.Parallel.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Linq.Queryable.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Memory.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Net.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Net.Http.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Net.Http.Json.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Net.HttpListener.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Net.Mail.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Net.NameResolution.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Net.NetworkInformation.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Net.Ping.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Net.Primitives.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Net.Quic.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Net.Requests.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Net.Security.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Net.ServicePoint.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Net.Sockets.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Net.WebClient.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Net.WebHeaderCollection.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Net.WebProxy.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Net.WebSockets.Client.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Net.WebSockets.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Numerics.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Numerics.Vectors.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.ObjectModel.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Reflection.DispatchProxy.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Reflection.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Reflection.Emit.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Reflection.Emit.ILGeneration.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Reflection.Emit.Lightweight.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Reflection.Extensions.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Reflection.Metadata.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Reflection.Primitives.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Reflection.TypeExtensions.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Resources.Reader.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Resources.ResourceManager.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Resources.Writer.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Runtime.CompilerServices.Unsafe.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Runtime.CompilerServices.VisualC.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Runtime.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Runtime.Extensions.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Runtime.Handles.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Runtime.InteropServices.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Runtime.InteropServices.JavaScript.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Runtime.InteropServices.RuntimeInformation.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Runtime.Intrinsics.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Runtime.Loader.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Runtime.Numerics.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Runtime.Serialization.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Runtime.Serialization.Formatters.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Runtime.Serialization.Json.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Runtime.Serialization.Primitives.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Runtime.Serialization.Xml.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Security.AccessControl.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Security.Claims.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Security.Cryptography.Algorithms.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Security.Cryptography.Cng.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Security.Cryptography.Csp.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Security.Cryptography.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Security.Cryptography.Encoding.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Security.Cryptography.OpenSsl.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Security.Cryptography.Primitives.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Security.Cryptography.X509Certificates.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Security.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Security.Principal.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Security.Principal.Windows.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Security.SecureString.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.ServiceModel.Web.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.ServiceProcess.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Text.Encoding.CodePages.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Text.Encoding.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Text.Encoding.Extensions.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Text.Encodings.Web.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Text.Json.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Text.RegularExpressions.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Threading.Channels.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Threading.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Threading.Overlapped.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Threading.Tasks.Dataflow.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Threading.Tasks.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Threading.Tasks.Extensions.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Threading.Tasks.Parallel.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Threading.Thread.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Threading.ThreadPool.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Threading.Timer.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Transactions.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Transactions.Local.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.ValueTuple.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Web.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Web.HttpUtility.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Windows.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Xml.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Xml.Linq.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Xml.ReaderWriter.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Xml.Serialization.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Xml.XDocument.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Xml.XmlDocument.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Xml.XmlSerializer.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Xml.XPath.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/System.Xml.XPath.XDocument.dll
-r:/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.10/ref/net7.0/WindowsBase.dll
--target:library
--nowarn:NU1603,NU1604,NU1605,NU1608
--warn:3
--warnaserror:3239
--fullpaths
--flaterrors
--highentropyva+
--targetprofile:netcore
--nocopyfsharpcore
--deterministic+
--simpleresolution
--test:GraphBasedChecking
--test:ParallelOptimization
--test:ParallelIlxGen
--warnaserror
--warnon:1182,3387,3366
--refout:/home/dark/app/backend/Build/obj/Prelude/Debug/net7.0/refint/Prelude.dll
/home/dark/app/backend/Build/obj/Prelude/Debug/net7.0/.NETCoreApp,Version=v7.0.AssemblyAttributes.fs
/home/dark/app/backend/Build/obj/Prelude/Debug/net7.0/Prelude.AssemblyInfo.fs
Exception.fs
NEList.fs
Regex.fs
Uuid.fs
Tuple2.fs
Base64.fs
UTF8.fs
Lazy.fs
String.fs
Map.fs
List.fs
Option.fs
Result.fs
HashSet.fs
Dictionary.fs
ResizeArray.fs
Task.fs
Ply.fs
NonBlockingConsole.fs
Prelude.fs
Json.fs
</code>
</details>

**Comment by nojaf** [comment]
Alright, thanks for confirming. It really depends on the project whether it has much effect or not.
Happy to hear it is at least working out as expected. Thanks for the feedback.

**Comment by pbiggar** [comment]
No worries! If you want to investigate further, the repo is really easy to build and you can easily do a complete rebuild by going into the devcontainer (`scripts/run-in-docker bash` or opening a terminal in VSCode) and:

- set desired dotnet flags in `./scripts/build/compile` or `backend/Directory.Build.props`
- clean build directory: `rm -rf backend/Build/*`
- ./scripts/build/compile-project backend
