### ISSUE TITLE
CLI: Implement self-updating mechanism for Darklang's executable

### ISSUE THREAD

**Issue by OceanOak** [darklang/dark#5256]
We need to implement a self-updating mechanism for Darklang's executable. This self-update should enable the executable to check for updates upon launch, download the update if available, and apply it without interrupting the user's workflow.

**Proposed solution:**

When the user launches Darklang's CLI, a `self-update` process should run in the background:
  - [x]  integrate the self-update functionality directly into the darklang executable, no need for a separate self-update script
  - [x] Version Comparison: The script should first compare the user's current version of Darklang with the latest available version.
  - [x] Download Update: If the user's version is not the latest, download the new executable, ensuring compatibility with the user's OS and architecture.
  - [x] Apply Update: After the download, the script should safely replace the old executable with the new one.
  - [x] The .darklang directory should exist; it contains backups, etc.

Upon corruption  or other issues, it is okay if the user has to reinstall the exe or perform any necessary actions to fix it

**In addressing this issue, we also need to:**

- [x] Build binaries for remaining runtimes ( osx-x64, osx-arm64, win-x64, and win-arm64) 
- [ ] Handle self-update for windows
- [x] Handle different shells (bash)
- [x] Create single-line installation instructions: users should be able to type darklang in terminal and have it run, without `cd`ing to some directory

**Comment by OceanOak** [comment]
Notes while working on the self-updating exe (to organize/ maybe move to the PR desctiption):

- Currently, we run the self-update every time we run a command, which could potentially lead to several issues:
   - gitHub rate limit for unauthenticated requests (due to frequent requests for the release version)
   - Users without internet access. (maybe the self update will just fail and we continue running the commands?)

If it's the same version, we are just  displaying it's already up-to-date now. However, we maybe should find a better solution to not run it every time)

- Is it ok to have two `processRun` functions, One is the old `processRun` function, and the other is designed to handle user input (used in the case when we need to ask the user if they want to add the executable to the PATH). or should it be one function that handles both cases? (I don't see how to do it in a single function)
   

- On Windows, commands like `uname -s`, which determine the operating system, may not work. 
We might consider something like the following?
   ```
   let os = Stdlib.Process.runCommand "uname -s"
   if os.exitCode != 0L then 
   // try the windows equivalent command
   ```
- is it ok to save the executable as just `darklang`  instead of `darklang-alpha-11ae66ea3ccbe90c3ccf21e991a40eeceecc9320-linux-arm64`
   This way, when we add it to the PATH, I believe users can simply run darklang, or should we keep the full name and create an alias?
   
 - after extracting the executable I am deleting the compressed file, is that the right thing to do?
 
 - code signing for mac

**Comment by OceanOak** [comment]
Notes from discussions on Discord regarding improvements to be made after the merge of #5276. (to organize/turn to todos)

- All of these Builtin.printLines are making me think we should built a Builtin.Tracing.log thing instead, allow users to choose how their app should be traced, and log to a file or something instead, if so configured.

- (mostly, anticipating these printLines breaking the LangServer, run by the CLI runtime)
When we're running the lang server via CLI, we should (for now) include a --skip-self-update flag or something, to prevent the self-update dance, so we don't hit those logs

- (currently) every time we run a command, we 'start the CLI' -- there's no long-running service yet, that hangs around. (though there will be, probably)

if the langserver fails, it fails, and someone can reload the extension. Not a big deal in the short term. Just want to make sure that circling back to this is on a list somewhere

- To check: I'm not totally sold on our Process.Result type - it's just stderr, stdout, and exitCode -- I find it a bit annoying to have to check the exitCode for each Process.run.

- Publish build for windows + handle self-update
define a type Host = | Windows of Architecture * ... | Linux of Arch * ... | MacOS of ... and pass that Host into the helper fns

- Handle different shells (bash)

- Improve error messages : I suppose that should say "couldn't fetch details of the latest darklang release" approx
Maybe with a preamble of "issue occurred when trying to self update:"

- When the self-update occurs, we don't switch to using the new version that is located in the .darklang/bin/darklang. Instead, the next time the user runs the 'darklang' command, it references the new version (is this ok?)
(We redownload the latest version when the user first runs the executable, because the self-update runs and since the config file is freshly created it thinks that the executable is not up-to-date, leading to a re-download)

- one idea I had would be to have the output be something like
Running self-update...
    - fetching list of releases
    - ...
    - ...
Now, processing normally
Just something to visually divide the operations

**Comment by StachuDotNet** [comment]
At this point, the goal of this Issue has been accomplished! I've extracted remaining notes from here into other issues (mostly the main CLI Runtime one)
